<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Описание-проекта-и-цель" data-toc-modified-id="Описание-проекта-и-цель-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Описание проекта и цель</a></span></li><li><span><a href="#Описание-данных" data-toc-modified-id="Описание-данных-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Описание данных</a></span></li><li><span><a href="#Загрузка-библиотек" data-toc-modified-id="Загрузка-библиотек-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Загрузка библиотек</a></span></li><li><span><a href="#Число-государственных,-частных-и-участковых-(сельских)-больничных-учреждений.-Ресурсы-и-деятельность-организаций-здравоохранения." data-toc-modified-id="Число-государственных,-частных-и-участковых-(сельских)-больничных-учреждений.-Ресурсы-и-деятельность-организаций-здравоохранения.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Число государственных, частных и участковых (сельских) больничных учреждений. Ресурсы и деятельность организаций здравоохранения.</a></span><ul class="toc-item"><li><span><a href="#Предположение" data-toc-modified-id="Предположение-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Предположение</a></span></li><li><span><a href="#Загрузка-и-предобработка-данных" data-toc-modified-id="Загрузка-и-предобработка-данных-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Загрузка и предобработка данных</a></span></li><li><span><a href="#Соединение-в-общий-датасет" data-toc-modified-id="Соединение-в-общий-датасет-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Соединение в общий датасет</a></span></li><li><span><a href="#Создание-датасетов" data-toc-modified-id="Создание-датасетов-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Создание датасетов</a></span><ul class="toc-item"><li><span><a href="#Датасет-с-общими-значениями" data-toc-modified-id="Датасет-с-общими-значениями-4.4.1"><span class="toc-item-num">4.4.1&nbsp;&nbsp;</span>Датасет с общими значениями</a></span></li><li><span><a href="#Датасет-городских-поселений" data-toc-modified-id="Датасет-городских-поселений-4.4.2"><span class="toc-item-num">4.4.2&nbsp;&nbsp;</span>Датасет городских поселений</a></span></li><li><span><a href="#Датасет-сельской-местности" data-toc-modified-id="Датасет-сельской-местности-4.4.3"><span class="toc-item-num">4.4.3&nbsp;&nbsp;</span>Датасет сельской местности</a></span></li></ul></li><li><span><a href="#Транспонирование-ранее-созданных-3-х-датасетов" data-toc-modified-id="Транспонирование-ранее-созданных-3-х-датасетов-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Транспонирование ранее созданных 3-х датасетов</a></span><ul class="toc-item"><li><span><a href="#Транспонированный-датасет-с-общими-значениями" data-toc-modified-id="Транспонированный-датасет-с-общими-значениями-4.5.1"><span class="toc-item-num">4.5.1&nbsp;&nbsp;</span>Транспонированный датасет с общими значениями</a></span></li><li><span><a href="#Транспонированный-датасет-с-городскими-поселениями" data-toc-modified-id="Транспонированный-датасет-с-городскими-поселениями-4.5.2"><span class="toc-item-num">4.5.2&nbsp;&nbsp;</span>Транспонированный датасет с городскими поселениями</a></span></li><li><span><a href="#Транспонированный-датасет-сельской-местности" data-toc-modified-id="Транспонированный-датасет-сельской-местности-4.5.3"><span class="toc-item-num">4.5.3&nbsp;&nbsp;</span>Транспонированный датасет сельской местности</a></span></li></ul></li><li><span><a href="#Сохранение-датасетов-в-csv-файл-для-дальнейшей-визуализации" data-toc-modified-id="Сохранение-датасетов-в-csv-файл-для-дальнейшей-визуализации-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Сохранение датасетов в csv файл для дальнейшей визуализации</a></span></li><li><span><a href="#Ссылка-на-дашборд" data-toc-modified-id="Ссылка-на-дашборд-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Ссылка на дашборд</a></span></li><li><span><a href="#Выводы-по-разделу" data-toc-modified-id="Выводы-по-разделу-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>Выводы по разделу</a></span></li></ul></li><li><span><a href="#Дома-ребенка.-Ресурсы-и-деятельность-организаций-здравоохранения." data-toc-modified-id="Дома-ребенка.-Ресурсы-и-деятельность-организаций-здравоохранения.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Дома ребенка. Ресурсы и деятельность организаций здравоохранения.</a></span><ul class="toc-item"><li><span><a href="#Предположение" data-toc-modified-id="Предположение-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Предположение</a></span></li><li><span><a href="#Загрузка-и-предобработка-файлов" data-toc-modified-id="Загрузка-и-предобработка-файлов-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Загрузка и предобработка файлов</a></span></li><li><span><a href="#Соединяем-данные-из-всех-папок-в-один-датафрейм" data-toc-modified-id="Соединяем-данные-из-всех-папок-в-один-датафрейм-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Соединяем данные из всех папок в один датафрейм</a></span></li><li><span><a href="#Ссылка-на-дашборд" data-toc-modified-id="Ссылка-на-дашборд-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Ссылка на дашборд</a></span></li><li><span><a href="#Выводы-по-разделу" data-toc-modified-id="Выводы-по-разделу-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Выводы по разделу</a></span></li></ul></li><li><span><a href="#Коечный-фонд-по-специализации-в-Субъектах-Российской-Федерации.-Ресурсы-и-деятельность-организаций-здравоохранения." data-toc-modified-id="Коечный-фонд-по-специализации-в-Субъектах-Российской-Федерации.-Ресурсы-и-деятельность-организаций-здравоохранения.-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Коечный фонд по специализации в Субъектах Российской Федерации. Ресурсы и деятельность организаций здравоохранения.</a></span><ul class="toc-item"><li><span><a href="#Предположение" data-toc-modified-id="Предположение-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Предположение</a></span></li><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Предобработка-данных" data-toc-modified-id="Предобработка-данных-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Предобработка данных</a></span><ul class="toc-item"><li><span><a href="#Данные-из-папки-за-2005-год" data-toc-modified-id="Данные-из-папки-за-2005-год-6.3.1"><span class="toc-item-num">6.3.1&nbsp;&nbsp;</span>Данные из папки за 2005 год</a></span></li><li><span><a href="#Данные-из-папки-2007-года" data-toc-modified-id="Данные-из-папки-2007-года-6.3.2"><span class="toc-item-num">6.3.2&nbsp;&nbsp;</span>Данные из папки 2007 года</a></span></li><li><span><a href="#Данные-из-папки-2009-года" data-toc-modified-id="Данные-из-папки-2009-года-6.3.3"><span class="toc-item-num">6.3.3&nbsp;&nbsp;</span>Данные из папки 2009 года</a></span></li><li><span><a href="#Данные-из-папки-за-2011-год" data-toc-modified-id="Данные-из-папки-за-2011-год-6.3.4"><span class="toc-item-num">6.3.4&nbsp;&nbsp;</span>Данные из папки за 2011 год</a></span></li><li><span><a href="#Данные-из-папки-за-2013-год" data-toc-modified-id="Данные-из-папки-за-2013-год-6.3.5"><span class="toc-item-num">6.3.5&nbsp;&nbsp;</span>Данные из папки за 2013 год</a></span></li></ul></li><li><span><a href="#Сохранение-данных" data-toc-modified-id="Сохранение-данных-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Сохранение данных</a></span></li><li><span><a href="#Дополнительное-соединение-и-сохранение-датасета" data-toc-modified-id="Дополнительное-соединение-и-сохранение-датасета-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Дополнительное соединение и сохранение датасета</a></span></li><li><span><a href="#Ссылка-на-дашборд" data-toc-modified-id="Ссылка-на-дашборд-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Ссылка на дашборд</a></span></li><li><span><a href="#Выводы-по-разделу" data-toc-modified-id="Выводы-по-разделу-6.7"><span class="toc-item-num">6.7&nbsp;&nbsp;</span>Выводы по разделу</a></span></li></ul></li><li><span><a href="#Техническое-состояние-и-благоустройство-зданий-лечебно-профилактических-учреждений-здравоохранения.-Ресурсы-и-деятельность-организаций-здравоохранения." data-toc-modified-id="Техническое-состояние-и-благоустройство-зданий-лечебно-профилактических-учреждений-здравоохранения.-Ресурсы-и-деятельность-организаций-здравоохранения.-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Техническое состояние и благоустройство зданий лечебно-профилактических учреждений здравоохранения. Ресурсы и деятельность организаций здравоохранения.</a></span><ul class="toc-item"><li><span><a href="#Предположение" data-toc-modified-id="Предположение-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Предположение</a></span></li><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Предобработка-данных" data-toc-modified-id="Предобработка-данных-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Предобработка данных</a></span></li><li><span><a href="#Соединение-в-единый-датасет" data-toc-modified-id="Соединение-в-единый-датасет-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>Соединение в единый датасет</a></span></li><li><span><a href="#Сохранение-получившихся-датасетов-и-разделение-их-на-стационар-и-амбулатории" data-toc-modified-id="Сохранение-получившихся-датасетов-и-разделение-их-на-стационар-и-амбулатории-7.5"><span class="toc-item-num">7.5&nbsp;&nbsp;</span>Сохранение получившихся датасетов и разделение их на стационар и амбулатории</a></span></li><li><span><a href="#Ссылка-на-дашборд" data-toc-modified-id="Ссылка-на-дашборд-7.6"><span class="toc-item-num">7.6&nbsp;&nbsp;</span>Ссылка на дашборд</a></span></li><li><span><a href="#Вывод-по-разделу" data-toc-modified-id="Вывод-по-разделу-7.7"><span class="toc-item-num">7.7&nbsp;&nbsp;</span>Вывод по разделу</a></span></li></ul></li></ul></div>

# Визуализация медицинской статистики по данным [Росстата](https://rosstat.gov.ru/folder/210/document/13218)

## Описание проекта и цель

**Выполнил Данилов Евгений**

Целью проекта является изучение данных сайта Росстата, которые были получены путём парсинга, с дальнейшей визуализацией полученных результатов в виде дашбордов.

## Описание данных

Раздел сайта [Здравоохранение в России](https://rosstat.gov.ru/folder/210/document/13218) содержит сборник данных.  
При подготовке сборника использованы данные, получаемые органами государственной статистики от юридических лиц, населения путем проведения федерального статистического наблюдения, выборочных обследований и других форм статистического наблюдения, данные министерств и ведомств Российской Федерации.  
В сборнике публикуются сведения о медико-демографических аспектах здоровья населения и его отдельных социально-демографических групп, организации лечебно-профилактической помощи и санаторно-курортного лечения населения, а также о состоянии рынка труда в здравоохранении, производстве товаров медицинского назначения, потребительском рынке товаров и услуг здравоохранения. Приведена информация о состоянии окружающей среды и санитарно-эпидемиологическом контроле.  
Статистические данные в разрезе субъектов Российской Федерации начиная с 2015 года выделены в отдельное электронное приложение. Сборник издается начиная с 2001 года с периодичностью один раз в два года, с 2015 года – только в электронном виде.  
В данном проекте делаем дашборды по подразделу **Ресурсы и деятельность организаций здравоохранения**, который имеется в сборнике данных

## Загрузка библиотек

In [1]:
import pandas as pd
import numpy as np
import re

## Число государственных, частных и участковых (сельских) больничных учреждений. Ресурсы и деятельность организаций здравоохранения.

### Предположение

За период 1990 - 2022 число государственных больничных организаций снизилось на 20%, число частных больничных организаций выросло в 4 раза, а количество участковых (сельских) больниц уменьшилось в 20 раз.

### Загрузка и предобработка данных

In [2]:
hospital_facilities_2005 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2005/Ресурсы и деятельность учреждений здравоохранения/больничные учреждения.csv')

hospital_facilities_2005.columns = hospital_facilities_2005.iloc[0]

hospital_facilities_2005.rename(columns = {np.nan:'name'}, inplace=True)

hospital_facilities_2005 = hospital_facilities_2005.drop(index = [0, 1]).reset_index(drop=True)

hospital_facilities_2005.head()

,name,1990,1995,2000,2001,2002,2003,2004
0,Число больничных учреждений,12762,12064,10704,10561,10320,10101,9851
1,из них негосударственные,...,29,87,105,97,111,122
2,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"всего, тыс.",2037.6,1850.5,1671.6,1653.4,1619.7,1596.6,1600.7
4,из них в негосударственных учреждениях,...,2.5,7.7,7.9,7.8,7.9,9.8

Посмотрим на уникальные названия колонки name, так как после изучения каждой таблицы "больничные учреждения" из каждой папки по годам, будем всё это соединять в единую таблицу по колонкам. Колонка name может содержать неодинаковые (неунифицированные) названия

In [3]:
hospital_facilities_2005['name'].unique()

array(['Число больничных учреждений', 'из них негосударственные',
       'Число коек в больничных учреждениях:', 'всего, тыс.',
       'из них в негосударственных учреждениях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan,
       'Число центральных районних больниц'], dtype=object)

In [4]:
hospital_facilities_2007 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2007/Ресурсы и деятельность учреждений здравоохранения/больничные учреждения.csv')

hospital_facilities_2007.columns = hospital_facilities_2007.iloc[0]

hospital_facilities_2007.rename(columns = {np.nan:'name'}, inplace=True)

hospital_facilities_2007 = hospital_facilities_2007.drop(index = [0, 1]).reset_index(drop=True)

hospital_facilities_2007.head()

,name,1990,1995,2000,2005,2006
0,Число больничных учреждений,12762,12064,10704,9479,7478
1,из них негосударственные,...,29,87,293,320
2,из них частной формы собственности,...,...,...,...,148
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6

In [5]:
hospital_facilities_2007['name'].unique()

array(['Число больничных учреждений', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных учреждениях:', 'всего, тыс.',
       'из них в негосударственных  учреждениях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной  больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan,
       'из них частной формы  собственности'], dtype=object)

In [6]:
hospital_facilities_2009 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2009/Ресурсы и деятельность учреждений здравоохранения/больничные учреждения.csv')

hospital_facilities_2009.columns = hospital_facilities_2009.iloc[0]

hospital_facilities_2009.rename(columns = {np.nan:'name'}, inplace=True)

hospital_facilities_2009 = hospital_facilities_2009.drop(index = [0, 1]).reset_index(drop=True)

hospital_facilities_2009.head()

,name,1995,2000,2005,2007,2008
0,Число больничных учреждений,12064,10704,9479,6777,6545
1,из них негосударственные,29,87,293,333,253
2,из них частной формы собственности,...,...,...,177,120
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",1850.5,1671.6,1575.4,1522.1,"1398,52"

In [7]:
hospital_facilities_2009['name'].unique()

array(['Число больничных учреждений', 'из них негосударственные',
       'из них частной формы  собственности',
       'Число коек в больничных учреждениях:', 'всего, тыс.',
       'из них в негосударственных  учреждениях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной  больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

In [8]:
hospital_facilities_2011 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2011/Ресурсы и деятельность учреждений здравоохранения/больничные учреждения.csv')

hospital_facilities_2011.columns = hospital_facilities_2011.iloc[0]

hospital_facilities_2011.rename(columns = {np.nan:'name'}, inplace=True)

hospital_facilities_2011 = hospital_facilities_2011.drop(index = [0, 1]).reset_index(drop=True)

hospital_facilities_2011.head()

,name,1995,2000,2005,2009,2010
0,Число больничных учреждений,12064,10704,9479,6454,6308
1,из них негосударственные,29,87,293,224,224
2,из них частной формы собственности,-,-,...,107,115
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",1850.5,1671.6,1575.4,1373.4,1339.5

In [9]:
hospital_facilities_2011['name'].unique()

array(['Число больничных учреждений', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных учреждениях:', 'всего, тыс.',
       'из них в негосударственных учреждениях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

In [10]:
hospital_facilities_2013 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2013/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.1. больничные организации.csv')

hospital_facilities_2013 = hospital_facilities_2013.drop(index = [0]).reset_index(drop=True)

hospital_facilities_2013.rename(columns = {'Unnamed: 0':'name'}, inplace=True)

hospital_facilities_2013.head()

,name,2000,2005,2010,2011,2012
0,Число больничных организаций,10704,9479,6308,6343,6172
1,из них негосударственные,87,293,224,220,225
2,из них частной формы собственности,-,…,115,116,127
3,Число коек в больничных организациях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1671,6","1575,4","1339,51","1347,11","1332,31"

In [11]:
hospital_facilities_2013['name'].unique()

array(['Число больничных организаций', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных организациях:', 'всего, тыс.',
       'из них в негосударственных организациях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

In [12]:
hospital_facilities_2011['name'].unique() == hospital_facilities_2013['name'].unique()

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False])

In [13]:
print(hospital_facilities_2011['name'][[0, 3, 5]])

print('-'*50)

print(hospital_facilities_2013['name'][[0, 3, 5]])

0               Число больничных учреждений
3      Число коек в больничных учреждениях:
5    из них в негосударственных учреждениях
Name: name, dtype: object
--------------------------------------------------
0               Число больничных организаций
3      Число коек в больничных организациях:
5    из них в негосударственных организациях
Name: name, dtype: object

При сравнению с названиями колонки name 2011 года с 2013 есть несовпадающие значения. Видно, что слово "учреждения" изменили на "организации".

Создадим новую переменную `res` в которой будет словарь со старыми значениями из строк колонки "name" 2013 года и новые значения из строк колонки "name" 2011 года.

In [14]:
res = {list(hospital_facilities_2013['name'])[i]: list(hospital_facilities_2011['name'])[i] for i in range(len(list(hospital_facilities_2013['name'])))}

res

{'Число больничных организаций': 'Число больничных учреждений',
 'из них негосударственные': 'из них негосударственные',
 'из них частной формы собственности': 'из них частной формы собственности',
 'Число коек в больничных организациях:': 'Число коек в больничных учреждениях:',
 'всего, тыс.': 'всего, тыс.',
 'из них в негосударственных организациях': 'из них в негосударственных учреждениях',
 'на 10 000 человек населения': 'на 10 000 человек населения',
 'Число центральных районных больниц': 'Число центральных районных больниц',
 'в них коек, тыс.': 'в них коек, тыс.',
 'средняя мощность одной больницы, коек': 'средняя мощность одной больницы, коек',
 'Число районных больниц': 'Число районных больниц',
 'Число участковых больниц': 'Число участковых больниц',
 nan: nan}

In [15]:
hospital_facilities_2013['name'] = hospital_facilities_2013['name'].map(res)

hospital_facilities_2013['name']

0                Число больничных учреждений
1                   из них негосударственные
2         из них частной формы собственности
3       Число коек в больничных учреждениях:
4                                всего, тыс.
5     из них в негосударственных учреждениях
6         из них частной формы собственности
7                на 10 000 человек населения
8         Число центральных районных больниц
9                           в них коек, тыс.
10     средняя мощность одной больницы, коек
11                    Число районных больниц
12                          в них коек, тыс.
13     средняя мощность одной больницы, коек
14                  Число участковых больниц
15                          в них коек, тыс.
16     средняя мощность одной больницы, коек
17                                       NaN
18               Число больничных учреждений
19                  из них негосударственные
20        из них частной формы собственности
21      Число коек в больничных учреждениях:
22                               всего, тыс.
23    из них в негосударственных учреждениях
24        из них частной формы собственности
25               на 10 000 человек населения
26        Число центральных районных больниц
27                    Число районных больниц
28                  Число участковых больниц
29                                       NaN
30               Число больничных учреждений
31                  из них негосударственные
32        из них частной формы собственности
33      Число коек в больничных учреждениях:
34                               всего, тыс.
35    из них в негосударственных учреждениях
36        из них частной формы собственности
37               на 10 000 человек населения
38        Число центральных районных больниц
39                    Число районных больниц
40                  Число участковых больниц
Name: name, dtype: object

In [16]:
hospital_facilities_2015 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2015/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.1. больничные организации.csv')

hospital_facilities_2015 = hospital_facilities_2015.drop(index = [0]).reset_index(drop=True)

hospital_facilities_2015.rename(columns = {'Unnamed: 0':'name'}, inplace=True)

hospital_facilities_2015.head()

,name,2005,2010,2011,2012,2013,2014
0,Число больничных организаций,9479,6308,6343,6172,5870,5638
1,из них негосударственные,293,224,220,225,233,246
2,из них частной формы собственности,…,115,116,127,143,166
3,Число коек в больничных организациях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1347,11","1332,31","1301,91","1266,81"

In [17]:
hospital_facilities_2015['name'].unique()

array(['Число больничных организаций', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных организациях:', 'всего, тыс.',
       'из них в негосударственных организациях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

В 2015 году также видно, что слово "учреждения" заменили на "организации", восплользуемся ранее созданным словарём из переменной `res` и изменим названия для унификации.

In [18]:
hospital_facilities_2015['name'] = hospital_facilities_2015['name'].map(res)

hospital_facilities_2015['name']

0                Число больничных учреждений
1                   из них негосударственные
2         из них частной формы собственности
3       Число коек в больничных учреждениях:
4                                всего, тыс.
5     из них в негосударственных учреждениях
6         из них частной формы собственности
7                на 10 000 человек населения
8         Число центральных районных больниц
9                           в них коек, тыс.
10     средняя мощность одной больницы, коек
11                    Число районных больниц
12                          в них коек, тыс.
13     средняя мощность одной больницы, коек
14                  Число участковых больниц
15                          в них коек, тыс.
16     средняя мощность одной больницы, коек
17                                       NaN
18               Число больничных учреждений
19                  из них негосударственные
20        из них частной формы собственности
21      Число коек в больничных учреждениях:
22                               всего, тыс.
23    из них в негосударственных учреждениях
24        из них частной формы собственности
25               на 10 000 человек населения
26        Число центральных районных больниц
27                    Число районных больниц
28                  Число участковых больниц
29                                       NaN
30               Число больничных учреждений
31                  из них негосударственные
32        из них частной формы собственности
33      Число коек в больничных учреждениях:
34                               всего, тыс.
35    из них в негосударственных учреждениях
36        из них частной формы собственности
37               на 10 000 человек населения
38        Число центральных районных больниц
39                    Число районных больниц
40                  Число участковых больниц
Name: name, dtype: object

In [19]:
hospital_facilities_2017 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2017/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.1. больничные организации.csv')

hospital_facilities_2017 = hospital_facilities_2017.drop(index = [0]).reset_index(drop=True)

hospital_facilities_2017.rename(columns = {'Unnamed: 0':'name'}, inplace=True)

hospital_facilities_2017.head()

,name,2005,2010,2013,2014,2015,2016
0,Число больничных организаций,9479,6308,5870,5638,5433,5357
1,из них негосударственные,293,224,233,246,245,266
2,из них частной формы собственности,…,115,143,166,180,205
3,Число коек в больничных организациях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1301,91","1266,81","1222,0","1197,2"

In [20]:
hospital_facilities_2017['name'].unique()

array(['Число больничных организаций', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных организациях:', 'всего, тыс.',
       'из них в негосударственных организациях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

Изменим названия строк колонки name 2017 с применением ранее созданного словаря в переменной `res`

In [21]:
hospital_facilities_2017['name'] = hospital_facilities_2017['name'].map(res)

In [22]:
hospital_facilities_2017

,name,2005,2010,2013,2014,2015,2016
0,Число больничных учреждений,9479,6308,5870,5638,5433,5357
1,из них негосударственные,293,224,233,246,245,266
2,из них частной формы собственности,…,115,143,166,180,205
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1301,91","1266,81","1222,0","1197,2"
5,из них в негосударственных учреждениях,"32,4","21,7","23,2","24,9","24,1","23,5"
6,из них частной формы собственности,…,"4,1","7,9","11,0","12,8","12,9"
7,на 10 000 человек населения,"110,9","93,8","90,6","86,6","83,4","81,6"
8,Число центральных районных больниц,1734,1754,1690,1470,1426,1388
9,"в них коек, тыс.","345,1","327,1","267,0","224,8","205,6","192,6"
10,"средняя мощность одной больницы, коек",199,186,158,153,144,139
11,Число районных больниц,267,191,206,417,415,425
12,"в них коек, тыс.","30,8","24,2","23,7","54,1","54,5","58,1"
13,"средняя мощность одной больницы, коек",115,126,115,130,131,137
14,Число участковых больниц,2631,400,124,97,69,68
15,"в них коек, тыс.","62,3","11,2","3,3","2,8","2,2","2,4"
16,"средняя мощность одной больницы, коек",24,28,27,29,32,35
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5820,4959,4775,4574,4397,4351
19,из них негосударственные,286,216,227,239,239,263
20,из них частной формы собственности,…,110,140,162,176,203
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1365,9","1186,11","1164,71","1123,51","1060,1",1041.0
23,из них в негосударственных учреждениях,"32,1","20,2","21,8","22,8","21,8","22,2"
24,из них частной формы собственности,…,"3,4","7,4","9,9","12,1","12,7"
25,на 10 000 человек населения,"130,3","112,5","109,3","103,8","97,6","95,5"
26,Число центральных районных больниц,1046,1027,994,902,829,815
27,Число районных больниц,148,112,129,238,230,242
28,Число участковых больниц,40,18,2,4,4,9
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3659,1349,1095,1064,1036,1006
31,из них негосударственные,7,8,6,7,6,3
32,из них частной формы собственности,…,5,3,4,4,2
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","137,21","143,31","161,9","156,2"
35,из них в негосударственных учреждениях,"0,3","1,6","1,4","2,1","2,3","1,3"
36,из них частной формы собственности,…,"0,68","0,46","1,02","0,6","0,2"
37,на 10 000 человек населения,"55,6","40,9","37,0","37,7","42,7","41,4"
38,Число центральных районных больниц,688,727,696,568,597,573
39,Число районных больниц,119,79,77,179,185,183
40,Число участковых больниц,2591,382,122,93,65,59

In [23]:
hospital_facilities_2019 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2019/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.1. больничные организации.csv')

hospital_facilities_2019 = hospital_facilities_2019.drop(index = [0]).reset_index(drop=True)

hospital_facilities_2019.rename(columns = {'Unnamed: 0':'name'}, inplace=True)

hospital_facilities_2019.head()

,name,2005,2010,2015,2016,2017,2018
0,Число больничных организаций,9479,6308,5433,5357,5293,5257
1,из них негосударственные,293,224,245,266,294,319
2,из них частной формы собственности,…,115,180,205,241,259
3,Число коек в больничных организациях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1222,01","1197,21","1182,71","1172,81"

In [24]:
hospital_facilities_2019['name'].unique()

array(['Число больничных организаций', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных организациях:', 'всего, тыс.',
       'из них в негосударственных организациях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

Изменим названия строк колонки name папки 2019 года с применением ранее созданного словаря в переменной `res`

In [25]:
hospital_facilities_2019['name'] = hospital_facilities_2019['name'].map(res)

In [26]:
hospital_facilities_2019

,name,2005,2010,2015,2016,2017,2018
0,Число больничных учреждений,9479,6308,5433,5357,5293,5257
1,из них негосударственные,293,224,245,266,294,319
2,из них частной формы собственности,…,115,180,205,241,259
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1222,01","1197,21","1182,71","1172,81"
5,из них в негосударственных учреждениях,"32,4","21,7","24,1","23,5","25,4","27,0"
6,из них частной формы собственности,…,"4,1","12,8","12,9","15,2","17,3"
7,на 10 000 человек населения,"110,9","93,8","83,4","81,6","80,5","79,9"
8,Число центральных районных больниц,1734,1754,1426,1388,1372,1361
9,"в них коек, тыс.","345,1","327,1","205,6","192,6","185,5","183,7"
10,"средняя мощность одной больницы, коек",199,186,144,139,135,135
11,Число районных больниц,267,191,415,425,418,418
12,"в них коек, тыс.","30,8","24,2","54,5","58,1","57,9","55,8"
13,"средняя мощность одной больницы, коек",115,126,131,137,138,134
14,Число участковых больниц,2631,400,69,68,58,47
15,"в них коек, тыс.","62,3","11,2","2,2","2,4","1,9","1,5"
16,"средняя мощность одной больницы, коек",24,28,32,35,33,33
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5820,4959,4397,4351,4297,4275
19,из них негосударственные,286,216,239,263,288,309
20,из них частной формы собственности,…,110,176,203,236,252
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1365,9","1186,11","1060,11","1041,01","1026,91","1018,71"
23,из них в негосударственных учреждениях,"32,1","20,2","21,8","22,2","23,0","24,4"
24,из них частной формы собственности,…,"3,4","12,1","12,7","14,6","16,5"
25,на 10 000 человек населения,"130,3","112,5","97,6","95,5","93,9","93,1"
26,Число центральных районных больниц,1046,1027,829,815,809,801
27,Число районных больниц,148,112,230,242,225,224
28,Число участковых больниц,40,18,4,9,6,5
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3659,1349,1036,1006,996,982
31,из них негосударственные,7,8,6,3,6,10
32,из них частной формы собственности,…,5,4,2,5,7
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","161,91","156,21","155,81","154,11"
35,из них в негосударственных учреждениях,"0,3","1,6","2,3","1,3","2,4","2,6"
36,из них частной формы собственности,…,"0,68","0,6","0,2","0,6","0,8"
37,на 10 000 человек населения,"55,6","40,9","42,7","41,4","41,5","41,3"
38,Число центральных районных больниц,688,727,597,573,563,560
39,Число районных больниц,119,79,185,183,193,194
40,Число участковых больниц,2591,382,65,59,52,42

In [27]:
hospital_facilities_2021 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2021/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.1. больничные организации.csv')

hospital_facilities_2021 = hospital_facilities_2021.drop(index = [0]).reset_index(drop=True)

hospital_facilities_2021.rename(columns = {'Unnamed: 0':'name'}, inplace=True)

hospital_facilities_2021.head()

,name,2005,2010,2015,2018,2019,2020
0,Число больничных организаций,9 479,6 308,5 433,5 257,5 130,5 065
1,из них негосударственные,293,224,245,319,328,344
2,из них частной формы собственности,…,115,180,259,274,294
3,Число коек в больничных организациях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1 575,4","1 339,51","1 222,01","1 172,81","1 173,61","1 188,81"

In [28]:
hospital_facilities_2021['name'].unique()

array(['Число больничных организаций', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных организациях:', 'всего, тыс.',
       'из них в негосударственных организациях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

In [29]:
hospital_facilities_2021['name'] = hospital_facilities_2021['name'].map(res)

In [30]:
hospital_facilities_2021

,name,2005,2010,2015,2018,2019,2020
0,Число больничных учреждений,9 479,6 308,5 433,5 257,5 130,5 065
1,из них негосударственные,293,224,245,319,328,344
2,из них частной формы собственности,…,115,180,259,274,294
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1 575,4","1 339,51","1 222,01","1 172,81","1 173,61","1 188,81"
5,из них в негосударственных учреждениях,"32,4","21,7","24,1","27,0","29,8","32,7"
6,из них частной формы собственности,…,"4,1","12,8","17,3","20,5","23,3"
7,на 10 000 человек населения,"110,9","93,8","83,4","79,9","80,0","81,3"
8,Число центральных районных больниц,1 734,1 754,1 426,1 361,1 325,1 316
9,"в них коек, тыс.","345,1","327,1","205,6","183,7","177,4","175,4"
10,"средняя мощность одной больницы, коек",199,186,144,135,134,133
11,Число районных больниц,267,191,415,418,416,409
12,"в них коек, тыс.","30,8","24,2","54,5","55,8","52,6","51,5"
13,"средняя мощность одной больницы, коек",115,126,131,134,126,126
14,Число участковых больниц,2 631,400,69,47,32,29
15,"в них коек, тыс.","62,3","11,2","2,2","1,5","1,0","0,9"
16,"средняя мощность одной больницы, коек",24,28,32,33,31,31
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5 820,4 959,4 397,4 275,4 186,4 136
19,из них негосударственные,286,216,239,309,318,340
20,из них частной формы собственности,…,110,176,252,265,290
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1 365,9","1 186,11","1 060,11","1 018,71","1 017,61","1 031,11"
23,из них в негосударственных учреждениях,"32,1","20,2","21,8","24,4","25,7","29,6"
24,из них частной формы собственности,…,"3,4","12,1","16,5","17,8","21,1"
25,на 10 000 человек населения,"130,3","112,5","97,6","93,1","92,9","94,4"
26,Число центральных районных больниц,1 046,1 027,829,801,789,784
27,Число районных больниц,148,112,230,224,217,208
28,Число участковых больниц,40,18,4,5,4,4
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3 659,1 349,1 036,982,944,929
31,из них негосударственные,7,8,6,10,10,4
32,из них частной формы собственности,…,5,4,7,9,4
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","161,91","154,11","155,91","157,61"
35,из них в негосударственных учреждениях,"0,3","1,6","2,3","2,6","4,1","3,1"
36,из них частной формы собственности,…,"0,68","0,6","0,8","2,7","2,3"
37,на 10 000 человек населения,"55,6","40,9","42,7","41,3","41,9","42,7"
38,Число центральных районных больниц,688,727,597,560,536,532
39,Число районных больниц,119,79,185,194,199,201
40,Число участковых больниц,2 591,382,65,42,28,25

In [31]:
hospital_facilities_2023 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2023/БОЛЬНИЧНЫЕ ОРГАНИЗАЦИИ - 3.1.csv')

hospital_facilities_2023.columns = hospital_facilities_2023.iloc[0]

hospital_facilities_2023 = hospital_facilities_2023.drop(index = [0, 1]).reset_index(drop=True)

hospital_facilities_2023.rename(columns = {np.nan:'name'}, inplace=True)

hospital_facilities_2023.head()

,name,2010,2015,2019,2020,2021,2022
0,Число больничных организаций,6 308,5 433,5 130,5 065,5 072,5 167
1,из них негосударственные,224,245,328,344,410,458
2,из них частной формы собственности,115,180,274,294,367,409
3,Число коек в больничных организациях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1 339,51","1 222,01","1 173,61","1 188,81","1 162,11","1 141,91"

In [32]:
hospital_facilities_2023['name'].unique()

array(['Число больничных организаций', 'из них негосударственные',
       'из них частной формы собственности',
       'Число коек в больничных организациях:', 'всего, тыс.',
       'из них в негосударственных организациях',
       'на 10 000 человек населения',
       'Число центральных районных больниц', 'в них коек, тыс.',
       'средняя мощность одной больницы, коек', 'Число районных больниц',
       'Число участковых больниц', nan], dtype=object)

In [33]:
hospital_facilities_2023['name'] = hospital_facilities_2023['name'].map(res)

hospital_facilities_2023

,name,2010,2015,2019,2020,2021,2022
0,Число больничных учреждений,6 308,5 433,5 130,5 065,5 072,5 167
1,из них негосударственные,224,245,328,344,410,458
2,из них частной формы собственности,115,180,274,294,367,409
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1 339,51","1 222,01","1 173,61","1 188,81","1 162,11","1 141,91"
5,из них в негосударственных учреждениях,"21,7","24,1","29,8","32,7","32,6","36,1"
6,из них частной формы собственности,"4,1","12,8","20,5","23,3","24,9","28,0"
7,на 10 000 человек населения,"93,8","83,4","80,0","81,3",NaN,NaN
8,Число центральных районных больниц,1 754,1 426,1 325,1 316,1 311,1 280
9,"в них коек, тыс.","327,1","205,6","177,4","175,4","171,6",164
10,"средняя мощность одной больницы, коек",186,144,134,133,131,128
11,Число районных больниц,191,415,416,409,391,396
12,"в них коек, тыс.","24,2","54,5","52,6","51,5","49,1","48,4"
13,"средняя мощность одной больницы, коек",126,131,126,126,126,122
14,Число участковых больниц,400,69,32,29,28,21
15,"в них коек, тыс.","11,2","2,2","1,0","0,9","0,9","0,7"
16,"средняя мощность одной больницы, коек",28,32,31,31,31,33
17,NaN,В городских поселениях,NaN,NaN,NaN,NaN,NaN
18,Число больничных учреждений,4 959,4 397,4 186,4 136,4 146,4 219
19,из них негосударственные,216,239,318,340,398,446
20,из них частной формы собственности,110,176,265,290,355,397
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1 186,11","1 060,11","1 017,61","1 031,11","1 009,81","991,11"
23,из них в негосударственных учреждениях,"20,2","21,8","25,7","29,6","28,7","31,8"
24,из них частной формы собственности,"3,4","12,1","17,8","21,1","21,8","24,5"
25,на 10 000 человек населения,"112,5","97,6","92,9","94,4",NaN,NaN
26,Число центральных районных больниц,1 027,829,789,784,778,757
27,Число районных больниц,112,230,217,208,202,211
28,Число участковых больниц,18,4,4,4,4,4
29,NaN,В сельской местности,NaN,NaN,NaN,NaN,NaN
30,Число больничных учреждений,1 349,1 036,944,929,926,948
31,из них негосударственные,8,6,10,4,12,12
32,из них частной формы собственности,5,4,9,4,12,12
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","153,41","161,91","155,91","157,61","152,41","150,8"
35,из них в негосударственных учреждениях,"1,6","2,3","4,1","3,1","3,9","4,3"
36,из них частной формы собственности,"0,68","0,60","2,70","2,30","3,10","3,40"
37,на 10 000 человек населения,"40,9","42,7","41,9","42,7",NaN,NaN
38,Число центральных районных больниц,727,597,536,532,533,523
39,Число районных больниц,79,185,199,201,189,185
40,Число участковых больниц,382,65,28,25,24,17

In [34]:
hospital_facilities_2005

,name,1990,1995,2000,2001,2002,2003,2004
0,Число больничных учреждений,12762,12064,10704,10561,10320,10101,9851
1,из них негосударственные,...,29,87,105,97,111,122
2,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"всего, тыс.",2037.6,1850.5,1671.6,1653.4,1619.7,1596.6,1600.7
4,из них в негосударственных учреждениях,...,2.5,7.7,7.9,7.8,7.9,9.8
5,на 10 000 человек населения,137.4,125.8,115.0,114.4,112.6,111.6,112.5
6,Число центральных районных больниц,1798,1786,1765,1756,1755,1743,1740
7,"в них коек, тыс.",451.0,409.7,373.6,365.5,359.0,349.8,353.1
8,"средняя мощность одной больницы, коек",251,229,211,208,205,207,203
9,Число районных больниц,324,294,263,266,273,286,278
10,"в них коек, тыс.",33.8,31.6,28.4,29.2,31.0,32.5,31.6
11,"средняя мощность одной больницы, коек",104,107,107,109,113,112,113
12,Число участковых больниц,4813,4409,3310,3290,3140,3020,2862
13,"в них коек, тыс.",156.3,129.0,85.1,83.4,78.0,73.3,68.6
14,"средняя мощность одной больницы, коек",32,29,26,25,25,24,24
15,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
16,Число больничных учреждений,...,6627,6326,6227,6139,6047,6022
17,из них негосударственные,...,29,87,104,94,107,119
18,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"всего, тыс.",...,1569.2,1438.7,1423.9,1399.3,1388.4,1391.4
20,из них в негосударственных учреждениях,...,-,7.7,7.9,7.7,7.8,9.7
21,на 10 000 человек населения,...,145.5,134.8,133.9,132.1,131.7,133.4
22,Число центральных районних больниц,1196,1103,1078,1074,1073,1060,1059
23,Число районных больниц,146,143,145,152,158,169,161
24,Число участковых больниц,-,11,30,29,35,44,43
25,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
26,Число больничных учреждений,...,5437,4378,4334,4181,4054,3829
27,из них негосударственные,...,-,-,1,3,4,3
28,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"всего, тыс.",...,281.3,232.9,229.6,220.4,208.2,209.4
30,из них в негосударственных учреждениях,...,-,-,0.05,0.07,0.08,0.06
31,на 10 000 человек населения,...,71.7,60.4,60.1,58.1,55.4,55.1
32,Число центральных районных больниц,602,683,687,682,682,683,681
33,Число районных больниц,178,151,118,114,115,117,117
34,Число участковых больниц,4813,4398,3280,3261,3105,2976,2819

In [35]:
hospital_facilities_2007

,name,1990,1995,2000,2005,2006
0,Число больничных учреждений,12762,12064,10704,9479,7478
1,из них негосударственные,...,29,87,293,320
2,из них частной формы собственности,...,...,...,...,148
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6
5,из них в негосударственных учреждениях,...,2.5,7.7,32.4,35.9
6,из них частной формы собственности,...,...,...,...,5.1
7,на 10 000 человек населения,137.4,125.8,115.0,111.3,109.2
8,Число центральных районных больниц,1798,1786,1765,1734,1748
9,"в них коек, тыс.",451.0,409.7,373.6,345.1,393.0
10,"средняя мощность одной больницы, коек",251,229,211,199,225
11,Число районных больниц,324,294,263,267,223
12,"в них коек, тыс.",33.8,31.6,28.4,30.8,26.8
13,"средняя мощность одной больницы, коек",104,107,107,116,120
14,Число участковых больниц,4813,4409,3310,2631,628
15,"в них коек, тыс.",156.3,129.0,85.1,62.3,18.1
16,"средняя мощность одной больницы, коек",32,29,26,24,29
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,...,6627,6326,5820,5512
19,из них негосударственные,...,29,87,286,313
20,из них частной формы собственности,...,...,...,...,144
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.",...,1569.2,1438.7,1365.9,1349.5
23,из них в негосударственных учреждениях,...,-,7.7,32.1,35.5
24,из них частной формы собственности,...,...,...,...,4.9
25,на 10 000 человек населения,...,145.5,134.8,131.7,130.0
26,Число центральных районных больниц,1196,1103,1078,1046,989
27,Число районных больниц,146,143,145,148,132
28,Число участковых больниц,-,11,30,40,32
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,...,5437,4378,3659,1966
31,из них негосударственные,...,-,-,7,7
32,из них частной формы собственности,...,...,...,...,4
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.",...,281.3,232.9,209.5,204.1
35,из них в негосударственных учреждениях,...,-,-,0.3,0.5
36,из них частной формы собственности,...,...,...,...,0.2
37,на 10 000 человек населения,...,71.7,60.4,55.3,53.1
38,Число центральных районных больниц,602,683,687,688,759
39,Число районных больниц,178,151,118,119,91
40,Число участковых больниц,4813,4398,3280,2591,596

In [36]:
hospital_facilities_2009

,name,1995,2000,2005,2007,2008
0,Число больничных учреждений,12064,10704,9479,6777,6545
1,из них негосударственные,29,87,293,333,253
2,из них частной формы собственности,...,...,...,177,120
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",1850.5,1671.6,1575.4,1522.1,"1398,52"
5,из них в негосударственных учреждениях,2.5,7.7,32.4,30.3,29.9
6,из них частной формы собственности,...,...,...,5.1,3.9
7,на 10 000 человек населения,125.8,115.0,111.3,107.2,98.6
8,Число центральных районных больниц,1786,1765,1734,1747,1749
9,"в них коек, тыс.",409.7,373.6,345.1,380.6,363.5
10,"средняя мощность одной больницы, коек",229,211,199,218,208
11,Число районных больниц,294,263,267,215,205
12,"в них коек, тыс.",31.6,28.4,30.8,26.6,25.7
13,"средняя мощность одной больницы, коек",107,107,116,124,125
14,Число участковых больниц,4409,3310,2631,510,481
15,"в них коек, тыс.",129.0,85.1,62.3,14.9,14.1
16,"средняя мощность одной больницы, коек",29,26,24,29,29
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,6627,6326,5820,5315,5131
19,из них негосударственные,29,87,286,326,246
20,из них частной формы собственности,...,...,...,173,116
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.",1569.2,1438.7,1365.9,1331.6,"1226,22"
23,из них в негосударственных учреждениях,-,7.7,32.1,29.9,28.5
24,из них частной формы собственности,...,...,...,4.9,3.8
25,на 10 000 человек населения,145.5,134.8,131.7,128.3,118.3
26,Число центральных районных больниц,1103,1078,1046,1028,1028
27,Число районных больниц,143,145,148,118,116
28,Число участковых больниц,11,30,40,29,25
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,5437,4378,3659,1462,1414
31,из них негосударственные,-,-,7,7,7
32,из них частной формы собственности,...,...,...,4,4
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.",281.3,232.9,209.5,190.4,"172,32"
35,из них в негосударственных учреждениях,-,-,0.3,0.4,1.4
36,из них частной формы собственности,...,...,...,0.2,0.1
37,на 10 000 человек населения,71.7,60.4,55.3,49.8,45.1
38,Число центральных районных больниц,683,687,688,719,721
39,Число районных больниц,151,118,119,97,89
40,Число участковых больниц,4398,3280,2591,481,456

In [37]:
hospital_facilities_2011

,name,1995,2000,2005,2009,2010
0,Число больничных учреждений,12064,10704,9479,6454,6308
1,из них негосударственные,29,87,293,224,224
2,из них частной формы собственности,-,-,...,107,115
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",1850.5,1671.6,1575.4,1373.4,1339.5
5,из них в негосударственных учреждениях,2.5,7.7,32.4,24.0,21.7
6,из них частной формы собственности,-,-,...,...,4.1
7,на 10 000 человек населения,125.8,115.0,111.3,96.8,93.7
8,Число центральных районных больниц,1786,1765,1734,1752,1754
9,"в них коек, тыс.",409.7,373.6,345.1,350.1,327.1
10,"средняя мощность одной больницы, коек",229,211,199,200,186
11,Число районных больниц,294,263,267,200,191
12,"в них коек, тыс.",31.6,28.4,30.8,24.8,24.2
13,"средняя мощность одной больницы, коек",107,107,116,124,126
14,Число участковых больниц,4409,3310,2631,438,400
15,"в них коек, тыс.",129.0,85.1,62.3,12.4,11.2
16,"средняя мощность одной больницы, коек",29,26,24,28,28
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,6627,6326,5820,5079,4959
19,из них негосударственные,29,87,286,220,216
20,из них частной формы собственности,-,-,...,105,110
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.",1569.2,1438.7,1365.9,1210.0,1186.1
23,из них в негосударственных учреждениях,...,7.7,32.1,23.2,20.2
24,из них частной формы собственности,-,-,...,...,3.3
25,на 10 000 человек населения,145.5,134.8,131.7,116.8,112.5
26,Число центральных районных больниц,1103,1078,1046,1029,1027
27,Число районных больниц,143,145,148,116,112
28,Число участковых больниц,11,30,40,23,18
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,5437,4378,3659,1375,1349
31,из них негосударственные,-,-,7,4,8
32,из них частной формы собственности,-,-,...,2,5
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.",281.3,232.9,209.5,163.4,153.4
35,из них в негосударственных учреждениях,...,-,0.3,0.7,1.6
36,из них частной формы собственности,-,-,...,...,0.68
37,на 10 000 человек населения,71.7,60.4,55.3,42.3,40.9
38,Число центральных районных больниц,683,687,688,723,727
39,Число районных больниц,151,118,119,84,79
40,Число участковых больниц,4398,3280,2591,415,382

In [38]:
hospital_facilities_2013

,name,2000,2005,2010,2011,2012
0,Число больничных учреждений,10704,9479,6308,6343,6172
1,из них негосударственные,87,293,224,220,225
2,из них частной формы собственности,-,…,115,116,127
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1671,6","1575,4","1339,51","1347,11","1332,31"
5,из них в негосударственных учреждениях,"7,7","32,4","21,7","20,6","22,6"
6,из них частной формы собственности,-,…,"4,1","4,1","6,5"
7,на 10 000 человек населения,"115,0","110,9","93,8","94,2","92,9"
8,Число центральных районных больниц,1765,1734,1754,1755,1719
9,"в них коек, тыс.","373,6","345,1","327,1","324,1","281,0"
10,"средняя мощность одной больницы, коек",211,199,186,185,163
11,Число районных больниц,263,267,191,177,195
12,"в них коек, тыс.","28,4","30,8","24,2","22,9","21,6"
13,"средняя мощность одной больницы, коек",107,115,126,129,111
14,Число участковых больниц,3310,2631,400,301,237
15,"в них коек, тыс.","85,1","62,3","11,2","8,3","5,4"
16,"средняя мощность одной больницы, коек",26,24,28,27,23
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,6326,5820,4959,5048,4956
19,из них негосударственные,87,286,216,215,220
20,из них частной формы собственности,-,…,110,113,124
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1438,7","1365,9","1186,11","1198,31","1188,91"
23,из них в негосударственных учреждениях,"7,7","32,1","20,2","20,0","21,3"
24,из них частной формы собственности,-,…,"3,4","3,7","6,1"
25,на 10 000 человек населения,"134,8","130,3","112,5","113,3","112,0"
26,Число центральных районных больниц,1078,1046,1027,1033,985
27,Число районных больниц,145,148,112,101,127
28,Число участковых больниц,30,40,18,11,9
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,4378,3659,1349,1295,1216
31,из них негосударственные,-,7,8,5,5
32,из них частной формы собственности,-,…,5,3,3
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","232,9","209,5","153,41","148,81","143,41"
35,из них в негосударственных учреждениях,-,"0,3","1,6","0,6","1,3"
36,из них частной формы собственности,-,…,"0,68","0,46","0,46"
37,на 10 000 человек населения,"60,4","55,6","40,9","39,9","38,5"
38,Число центральных районных больниц,687,688,727,722,734
39,Число районных больниц,118,119,79,76,68
40,Число участковых больниц,3280,2591,382,290,228

In [39]:
hospital_facilities_2015

,name,2005,2010,2011,2012,2013,2014
0,Число больничных учреждений,9479,6308,6343,6172,5870,5638
1,из них негосударственные,293,224,220,225,233,246
2,из них частной формы собственности,…,115,116,127,143,166
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1347,11","1332,31","1301,91","1266,81"
5,из них в негосударственных учреждениях,"32,4","21,7","20,6","22,6","23,2","24,9"
6,из них частной формы собственности,…,"4,1","4,1","6,5","7,9","11,0"
7,на 10 000 человек населения,"110,9","93,8","94,2","92,9","90,6","86,6"
8,Число центральных районных больниц,1734,1754,1755,1719,1690,1470
9,"в них коек, тыс.","345,1","327,1","324,1","281,0","267,0","224,8"
10,"средняя мощность одной больницы, коек",199,186,185,163,158,153
11,Число районных больниц,267,191,177,195,206,417
12,"в них коек, тыс.","30,8","24,2","22,9","21,6","23,7","54,1"
13,"средняя мощность одной больницы, коек",115,126,129,111,115,130
14,Число участковых больниц,2631,400,301,237,124,97
15,"в них коек, тыс.","62,3","11,2","8,3","5,4","3,3","2,8"
16,"средняя мощность одной больницы, коек",24,28,27,23,27,29
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5820,4959,5048,4956,4775,4574
19,из них негосударственные,286,216,215,220,227,239
20,из них частной формы собственности,…,110,113,124,140,162
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1365,9","1186,11","1198,31","1188,91","1164,71","1123,51"
23,из них в негосударственных учреждениях,"32,1","20,2","20,0","21,3","21,8","22,8"
24,из них частной формы собственности,…,"3,4","3,7","6,1","7,4","9,9"
25,на 10 000 человек населения,"130,3","112,5","113,3","112,0","109,3","103,8"
26,Число центральных районных больниц,1046,1027,1033,985,994,902
27,Число районных больниц,148,112,101,127,129,238
28,Число участковых больниц,40,18,11,9,2,4
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3659,1349,1295,1216,1095,1064
31,из них негосударственные,7,8,5,5,6,7
32,из них частной формы собственности,…,5,3,3,3,4
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","148,81","143,41","137,21","143,31"
35,из них в негосударственных учреждениях,"0,3","1,6","0,6","1,3","1,4","2,1"
36,из них частной формы собственности,…,"0,68","0,46","0,46","0,46","1,02"
37,на 10 000 человек населения,"55,6","40,9","39,9","38,5","37,0","37,7"
38,Число центральных районных больниц,688,727,722,734,696,568
39,Число районных больниц,119,79,76,68,77,179
40,Число участковых больниц,2591,382,290,228,122,93

In [40]:
hospital_facilities_2017

,name,2005,2010,2013,2014,2015,2016
0,Число больничных учреждений,9479,6308,5870,5638,5433,5357
1,из них негосударственные,293,224,233,246,245,266
2,из них частной формы собственности,…,115,143,166,180,205
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1301,91","1266,81","1222,0","1197,2"
5,из них в негосударственных учреждениях,"32,4","21,7","23,2","24,9","24,1","23,5"
6,из них частной формы собственности,…,"4,1","7,9","11,0","12,8","12,9"
7,на 10 000 человек населения,"110,9","93,8","90,6","86,6","83,4","81,6"
8,Число центральных районных больниц,1734,1754,1690,1470,1426,1388
9,"в них коек, тыс.","345,1","327,1","267,0","224,8","205,6","192,6"
10,"средняя мощность одной больницы, коек",199,186,158,153,144,139
11,Число районных больниц,267,191,206,417,415,425
12,"в них коек, тыс.","30,8","24,2","23,7","54,1","54,5","58,1"
13,"средняя мощность одной больницы, коек",115,126,115,130,131,137
14,Число участковых больниц,2631,400,124,97,69,68
15,"в них коек, тыс.","62,3","11,2","3,3","2,8","2,2","2,4"
16,"средняя мощность одной больницы, коек",24,28,27,29,32,35
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5820,4959,4775,4574,4397,4351
19,из них негосударственные,286,216,227,239,239,263
20,из них частной формы собственности,…,110,140,162,176,203
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1365,9","1186,11","1164,71","1123,51","1060,1",1041.0
23,из них в негосударственных учреждениях,"32,1","20,2","21,8","22,8","21,8","22,2"
24,из них частной формы собственности,…,"3,4","7,4","9,9","12,1","12,7"
25,на 10 000 человек населения,"130,3","112,5","109,3","103,8","97,6","95,5"
26,Число центральных районных больниц,1046,1027,994,902,829,815
27,Число районных больниц,148,112,129,238,230,242
28,Число участковых больниц,40,18,2,4,4,9
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3659,1349,1095,1064,1036,1006
31,из них негосударственные,7,8,6,7,6,3
32,из них частной формы собственности,…,5,3,4,4,2
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","137,21","143,31","161,9","156,2"
35,из них в негосударственных учреждениях,"0,3","1,6","1,4","2,1","2,3","1,3"
36,из них частной формы собственности,…,"0,68","0,46","1,02","0,6","0,2"
37,на 10 000 человек населения,"55,6","40,9","37,0","37,7","42,7","41,4"
38,Число центральных районных больниц,688,727,696,568,597,573
39,Число районных больниц,119,79,77,179,185,183
40,Число участковых больниц,2591,382,122,93,65,59

In [41]:
hospital_facilities_2019

,name,2005,2010,2015,2016,2017,2018
0,Число больничных учреждений,9479,6308,5433,5357,5293,5257
1,из них негосударственные,293,224,245,266,294,319
2,из них частной формы собственности,…,115,180,205,241,259
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1575,4","1339,51","1222,01","1197,21","1182,71","1172,81"
5,из них в негосударственных учреждениях,"32,4","21,7","24,1","23,5","25,4","27,0"
6,из них частной формы собственности,…,"4,1","12,8","12,9","15,2","17,3"
7,на 10 000 человек населения,"110,9","93,8","83,4","81,6","80,5","79,9"
8,Число центральных районных больниц,1734,1754,1426,1388,1372,1361
9,"в них коек, тыс.","345,1","327,1","205,6","192,6","185,5","183,7"
10,"средняя мощность одной больницы, коек",199,186,144,139,135,135
11,Число районных больниц,267,191,415,425,418,418
12,"в них коек, тыс.","30,8","24,2","54,5","58,1","57,9","55,8"
13,"средняя мощность одной больницы, коек",115,126,131,137,138,134
14,Число участковых больниц,2631,400,69,68,58,47
15,"в них коек, тыс.","62,3","11,2","2,2","2,4","1,9","1,5"
16,"средняя мощность одной больницы, коек",24,28,32,35,33,33
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5820,4959,4397,4351,4297,4275
19,из них негосударственные,286,216,239,263,288,309
20,из них частной формы собственности,…,110,176,203,236,252
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1365,9","1186,11","1060,11","1041,01","1026,91","1018,71"
23,из них в негосударственных учреждениях,"32,1","20,2","21,8","22,2","23,0","24,4"
24,из них частной формы собственности,…,"3,4","12,1","12,7","14,6","16,5"
25,на 10 000 человек населения,"130,3","112,5","97,6","95,5","93,9","93,1"
26,Число центральных районных больниц,1046,1027,829,815,809,801
27,Число районных больниц,148,112,230,242,225,224
28,Число участковых больниц,40,18,4,9,6,5
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3659,1349,1036,1006,996,982
31,из них негосударственные,7,8,6,3,6,10
32,из них частной формы собственности,…,5,4,2,5,7
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","161,91","156,21","155,81","154,11"
35,из них в негосударственных учреждениях,"0,3","1,6","2,3","1,3","2,4","2,6"
36,из них частной формы собственности,…,"0,68","0,6","0,2","0,6","0,8"
37,на 10 000 человек населения,"55,6","40,9","42,7","41,4","41,5","41,3"
38,Число центральных районных больниц,688,727,597,573,563,560
39,Число районных больниц,119,79,185,183,193,194
40,Число участковых больниц,2591,382,65,59,52,42

In [42]:
hospital_facilities_2021

,name,2005,2010,2015,2018,2019,2020
0,Число больничных учреждений,9 479,6 308,5 433,5 257,5 130,5 065
1,из них негосударственные,293,224,245,319,328,344
2,из них частной формы собственности,…,115,180,259,274,294
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1 575,4","1 339,51","1 222,01","1 172,81","1 173,61","1 188,81"
5,из них в негосударственных учреждениях,"32,4","21,7","24,1","27,0","29,8","32,7"
6,из них частной формы собственности,…,"4,1","12,8","17,3","20,5","23,3"
7,на 10 000 человек населения,"110,9","93,8","83,4","79,9","80,0","81,3"
8,Число центральных районных больниц,1 734,1 754,1 426,1 361,1 325,1 316
9,"в них коек, тыс.","345,1","327,1","205,6","183,7","177,4","175,4"
10,"средняя мощность одной больницы, коек",199,186,144,135,134,133
11,Число районных больниц,267,191,415,418,416,409
12,"в них коек, тыс.","30,8","24,2","54,5","55,8","52,6","51,5"
13,"средняя мощность одной больницы, коек",115,126,131,134,126,126
14,Число участковых больниц,2 631,400,69,47,32,29
15,"в них коек, тыс.","62,3","11,2","2,2","1,5","1,0","0,9"
16,"средняя мощность одной больницы, коек",24,28,32,33,31,31
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,5 820,4 959,4 397,4 275,4 186,4 136
19,из них негосударственные,286,216,239,309,318,340
20,из них частной формы собственности,…,110,176,252,265,290
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1 365,9","1 186,11","1 060,11","1 018,71","1 017,61","1 031,11"
23,из них в негосударственных учреждениях,"32,1","20,2","21,8","24,4","25,7","29,6"
24,из них частной формы собственности,…,"3,4","12,1","16,5","17,8","21,1"
25,на 10 000 человек населения,"130,3","112,5","97,6","93,1","92,9","94,4"
26,Число центральных районных больниц,1 046,1 027,829,801,789,784
27,Число районных больниц,148,112,230,224,217,208
28,Число участковых больниц,40,18,4,5,4,4
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,3 659,1 349,1 036,982,944,929
31,из них негосударственные,7,8,6,10,10,4
32,из них частной формы собственности,…,5,4,7,9,4
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","209,5","153,41","161,91","154,11","155,91","157,61"
35,из них в негосударственных учреждениях,"0,3","1,6","2,3","2,6","4,1","3,1"
36,из них частной формы собственности,…,"0,68","0,6","0,8","2,7","2,3"
37,на 10 000 человек населения,"55,6","40,9","42,7","41,3","41,9","42,7"
38,Число центральных районных больниц,688,727,597,560,536,532
39,Число районных больниц,119,79,185,194,199,201
40,Число участковых больниц,2 591,382,65,42,28,25

In [43]:
hospital_facilities_2023

,name,2010,2015,2019,2020,2021,2022
0,Число больничных учреждений,6 308,5 433,5 130,5 065,5 072,5 167
1,из них негосударственные,224,245,328,344,410,458
2,из них частной формы собственности,115,180,274,294,367,409
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.","1 339,51","1 222,01","1 173,61","1 188,81","1 162,11","1 141,91"
5,из них в негосударственных учреждениях,"21,7","24,1","29,8","32,7","32,6","36,1"
6,из них частной формы собственности,"4,1","12,8","20,5","23,3","24,9","28,0"
7,на 10 000 человек населения,"93,8","83,4","80,0","81,3",NaN,NaN
8,Число центральных районных больниц,1 754,1 426,1 325,1 316,1 311,1 280
9,"в них коек, тыс.","327,1","205,6","177,4","175,4","171,6",164
10,"средняя мощность одной больницы, коек",186,144,134,133,131,128
11,Число районных больниц,191,415,416,409,391,396
12,"в них коек, тыс.","24,2","54,5","52,6","51,5","49,1","48,4"
13,"средняя мощность одной больницы, коек",126,131,126,126,126,122
14,Число участковых больниц,400,69,32,29,28,21
15,"в них коек, тыс.","11,2","2,2","1,0","0,9","0,9","0,7"
16,"средняя мощность одной больницы, коек",28,32,31,31,31,33
17,NaN,В городских поселениях,NaN,NaN,NaN,NaN,NaN
18,Число больничных учреждений,4 959,4 397,4 186,4 136,4 146,4 219
19,из них негосударственные,216,239,318,340,398,446
20,из них частной формы собственности,110,176,265,290,355,397
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.","1 186,11","1 060,11","1 017,61","1 031,11","1 009,81","991,11"
23,из них в негосударственных учреждениях,"20,2","21,8","25,7","29,6","28,7","31,8"
24,из них частной формы собственности,"3,4","12,1","17,8","21,1","21,8","24,5"
25,на 10 000 человек населения,"112,5","97,6","92,9","94,4",NaN,NaN
26,Число центральных районных больниц,1 027,829,789,784,778,757
27,Число районных больниц,112,230,217,208,202,211
28,Число участковых больниц,18,4,4,4,4,4
29,NaN,В сельской местности,NaN,NaN,NaN,NaN,NaN
30,Число больничных учреждений,1 349,1 036,944,929,926,948
31,из них негосударственные,8,6,10,4,12,12
32,из них частной формы собственности,5,4,9,4,12,12
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.","153,41","161,91","155,91","157,61","152,41","150,8"
35,из них в негосударственных учреждениях,"1,6","2,3","4,1","3,1","3,9","4,3"
36,из них частной формы собственности,"0,68","0,60","2,70","2,30","3,10","3,40"
37,на 10 000 человек населения,"40,9","42,7","41,9","42,7",NaN,NaN
38,Число центральных районных больниц,727,597,536,532,533,523
39,Число районных больниц,79,185,199,201,189,185
40,Число участковых больниц,382,65,28,25,24,17

### Соединение в общий датасет

Так как число строк меньше только в данных из папки за 2005 год, остальные все данные по годам имеют одинаковое кол-во заполненных строк, то начнём конкатенацию с данных из папки 2007. Данные из папки 2005 присоединим в самом конце.

In [44]:
hospital_facilities_1 = pd.concat([hospital_facilities_2007, hospital_facilities_2009], axis=1)

hospital_facilities_1

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,2007,2008
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,6777,6545
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,333,253
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,177,120
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,1522.1,"1398,52"
5,из них в негосударственных учреждениях,...,2.5,7.7,32.4,35.9,из них в негосударственных учреждениях,2.5,7.7,32.4,30.3,29.9
6,из них частной формы собственности,...,...,...,...,5.1,из них частной формы собственности,...,...,...,5.1,3.9
7,на 10 000 человек населения,137.4,125.8,115.0,111.3,109.2,на 10 000 человек населения,125.8,115.0,111.3,107.2,98.6
8,Число центральных районных больниц,1798,1786,1765,1734,1748,Число центральных районных больниц,1786,1765,1734,1747,1749
9,"в них коек, тыс.",451.0,409.7,373.6,345.1,393.0,"в них коек, тыс.",409.7,373.6,345.1,380.6,363.5
10,"средняя мощность одной больницы, коек",251,229,211,199,225,"средняя мощность одной больницы, коек",229,211,199,218,208
11,Число районных больниц,324,294,263,267,223,Число районных больниц,294,263,267,215,205
12,"в них коек, тыс.",33.8,31.6,28.4,30.8,26.8,"в них коек, тыс.",31.6,28.4,30.8,26.6,25.7
13,"средняя мощность одной больницы, коек",104,107,107,116,120,"средняя мощность одной больницы, коек",107,107,116,124,125
14,Число участковых больниц,4813,4409,3310,2631,628,Число участковых больниц,4409,3310,2631,510,481
15,"в них коек, тыс.",156.3,129.0,85.1,62.3,18.1,"в них коек, тыс.",129.0,85.1,62.3,14.9,14.1
16,"средняя мощность одной больницы, коек",32,29,26,24,29,"средняя мощность одной больницы, коек",29,26,24,29,29
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
18,Число больничных учреждений,...,6627,6326,5820,5512,Число больничных учреждений,6627,6326,5820,5315,5131
19,из них негосударственные,...,29,87,286,313,из них негосударственные,29,87,286,326,246
20,из них частной формы собственности,...,...,...,...,144,из них частной формы собственности,...,...,...,173,116
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.",...,1569.2,1438.7,1365.9,1349.5,"всего, тыс.",1569.2,1438.7,1365.9,1331.6,"1226,22"
23,из них в негосударственных учреждениях,...,-,7.7,32.1,35.5,из них в негосударственных учреждениях,-,7.7,32.1,29.9,28.5
24,из них частной формы собственности,...,...,...,...,4.9,из них частной формы собственности,...,...,...,4.9,3.8
25,на 10 000 человек населения,...,145.5,134.8,131.7,130.0,на 10 000 человек населения,145.5,134.8,131.7,128.3,118.3
26,Число центральных районных больниц,1196,1103,1078,1046,989,Число центральных районных больниц,1103,1078,1046,1028,1028
27,Число районных больниц,146,143,145,148,132,Число районных больниц,143,145,148,118,116
28,Число участковых больниц,-,11,30,40,32,Число участковых больниц,11,30,40,29,25
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности
30,Число больничных учреждений,...,5437,4378,3659,1966,Число больничных учреждений,5437,4378,3659,1462,1414
31,из них негосударственные,...,-,-,7,7,из них негосударственные,-,-,7,7,7
32,из них частной формы собственности,...,...,...,...,4,из них частной формы собственности,...,...,...,4,4
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.",...,281.3,232.9,209.5,204.1,"всего, тыс.",281.3,232.9,209.5,190.4,"172,32"
35,из них в негосударственных учреждениях,...,-,-,0.3,0.5,из них в негосударственных учреждениях,-,-,0.3,0.4,1.4
36,из них частной формы собственности,...,...,...,...,0.2,из них частной формы собственности,...,...,...,0.2,0.1
37,на 10 000 человек населения,...,71.7,60.4,55.3,53.1,на 10 000 человек населения,71.7,60.4,55.3,49.8,45.1
38,Число центральных районных больниц,602,683,687,688,759,Число центральных районных больниц,683,687,688,719,721
39,Число районных больниц,178,151,118,119,91,Число районных больниц,151,118,119,97,89
40,Число участковых больниц,4813,4398,3280,2591,596,Число участковых больниц,4398,3280,2591,481,456

In [45]:
hospital_facilities_2 = pd.concat([hospital_facilities_1, hospital_facilities_2011], axis=1)

hospital_facilities_2.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,2007,2008,name,1995,2000,2005,2009,2010
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,6777,6545,Число больничных учреждений,12064,10704,9479,6454,6308
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,333,253,из них негосударственные,29,87,293,224,224
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,177,120,из них частной формы собственности,-,-,...,107,115
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,1522.1,"1398,52","всего, тыс.",1850.5,1671.6,1575.4,1373.4,1339.5

In [46]:
hospital_facilities_3 = pd.concat([hospital_facilities_2, hospital_facilities_2013], axis=1)

hospital_facilities_3.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,...,2000,2005,2009,2010,name,2000,2005,2010,2011,2012
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,...,10704,9479,6454,6308,Число больничных учреждений,10704,9479,6308,6343,6172
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,...,87,293,224,224,из них негосударственные,87,293,224,220,225
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,...,-,...,107,115,из них частной формы собственности,-,…,115,116,127
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,...,1671.6,1575.4,1373.4,1339.5,"всего, тыс.","1671,6","1575,4","1339,51","1347,11","1332,31"

In [47]:
hospital_facilities_4 = pd.concat([hospital_facilities_3, hospital_facilities_2015], axis=1)

hospital_facilities_4.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,...,2010,2011,2012,name,2005,2010,2011,2012,2013,2014
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,...,6308,6343,6172,Число больничных учреждений,9479,6308,6343,6172,5870,5638
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,...,224,220,225,из них негосударственные,293,224,220,225,233,246
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,...,115,116,127,из них частной формы собственности,…,115,116,127,143,166
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,...,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,...,"1339,51","1347,11","1332,31","всего, тыс.","1575,4","1339,51","1347,11","1332,31","1301,91","1266,81"

In [48]:
hospital_facilities_5 = pd.concat([hospital_facilities_4, hospital_facilities_2017], axis=1)

hospital_facilities_5.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,...,2012,2013,2014,name,2005,2010,2013,2014,2015,2016
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,...,6172,5870,5638,Число больничных учреждений,9479,6308,5870,5638,5433,5357
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,...,225,233,246,из них негосударственные,293,224,233,246,245,266
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,...,127,143,166,из них частной формы собственности,…,115,143,166,180,205
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,...,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,...,"1332,31","1301,91","1266,81","всего, тыс.","1575,4","1339,51","1301,91","1266,81","1222,0","1197,2"

In [49]:
hospital_facilities_6 = pd.concat([hospital_facilities_5, hospital_facilities_2019], axis=1)

hospital_facilities_6.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,...,2014,2015,2016,name,2005,2010,2015,2016,2017,2018
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,...,5638,5433,5357,Число больничных учреждений,9479,6308,5433,5357,5293,5257
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,...,246,245,266,из них негосударственные,293,224,245,266,294,319
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,...,166,180,205,из них частной формы собственности,…,115,180,205,241,259
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,...,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,...,"1266,81","1222,0","1197,2","всего, тыс.","1575,4","1339,51","1222,01","1197,21","1182,71","1172,81"

In [50]:
hospital_facilities_7 = pd.concat([hospital_facilities_6, hospital_facilities_2021], axis=1)

hospital_facilities_7.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,...,2016,2017,2018,name,2005,2010,2015,2018,2019,2020
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,...,5357,5293,5257,Число больничных учреждений,9 479,6 308,5 433,5 257,5 130,5 065
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,...,266,294,319,из них негосударственные,293,224,245,319,328,344
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,...,205,241,259,из них частной формы собственности,…,115,180,259,274,294
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,...,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,...,"1197,21","1182,71","1172,81","всего, тыс.","1 575,4","1 339,51","1 222,01","1 172,81","1 173,61","1 188,81"

In [51]:
hospital_facilities_8 = pd.concat([hospital_facilities_7, hospital_facilities_2023], axis=1)

hospital_facilities_8.head()

,name,1990,1995,2000,2005,2006,name,1995,2000,2005,...,2018,2019,2020,name,2010,2015,2019,2020,2021,2022
0,Число больничных учреждений,12762,12064,10704,9479,7478,Число больничных учреждений,12064,10704,9479,...,5 257,5 130,5 065,Число больничных учреждений,6 308,5 433,5 130,5 065,5 072,5 167
1,из них негосударственные,...,29,87,293,320,из них негосударственные,29,87,293,...,319,328,344,из них негосударственные,224,245,328,344,410,458
2,из них частной формы собственности,...,...,...,...,148,из них частной формы собственности,...,...,...,...,259,274,294,из них частной формы собственности,115,180,274,294,367,409
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,...,NaN,NaN,NaN,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,"всего, тыс.",1850.5,1671.6,1575.4,...,"1 172,81","1 173,61","1 188,81","всего, тыс.","1 339,51","1 222,01","1 173,61","1 188,81","1 162,11","1 141,91"

Теперь удалим столбцы дубликаты по названию

In [52]:
hospital_facilities_8 = hospital_facilities_8.loc[:, ~hospital_facilities_8.columns.duplicated()].copy()

In [53]:
hospital_facilities_8

,name,1990,1995,2000,2005,2006,2007,2008,2009,2010,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Число больничных учреждений,12762,12064,10704,9479,7478,6777,6545,6454,6308,...,5870,5638,5433,5357,5293,5257,5 130,5 065,5 072,5 167
1,из них негосударственные,...,29,87,293,320,333,253,224,224,...,233,246,245,266,294,319,328,344,410,458
2,из них частной формы собственности,...,...,...,...,148,177,120,107,115,...,143,166,180,205,241,259,274,294,367,409
3,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,1522.1,"1398,52",1373.4,1339.5,...,"1301,91","1266,81","1222,0","1197,2","1182,71","1172,81","1 173,61","1 188,81","1 162,11","1 141,91"
5,из них в негосударственных учреждениях,...,2.5,7.7,32.4,35.9,30.3,29.9,24.0,21.7,...,"23,2","24,9","24,1","23,5","25,4","27,0","29,8","32,7","32,6","36,1"
6,из них частной формы собственности,...,...,...,...,5.1,5.1,3.9,...,4.1,...,"7,9","11,0","12,8","12,9","15,2","17,3","20,5","23,3","24,9","28,0"
7,на 10 000 человек населения,137.4,125.8,115.0,111.3,109.2,107.2,98.6,96.8,93.7,...,"90,6","86,6","83,4","81,6","80,5","79,9","80,0","81,3",NaN,NaN
8,Число центральных районных больниц,1798,1786,1765,1734,1748,1747,1749,1752,1754,...,1690,1470,1426,1388,1372,1361,1 325,1 316,1 311,1 280
9,"в них коек, тыс.",451.0,409.7,373.6,345.1,393.0,380.6,363.5,350.1,327.1,...,"267,0","224,8","205,6","192,6","185,5","183,7","177,4","175,4","171,6",164
10,"средняя мощность одной больницы, коек",251,229,211,199,225,218,208,200,186,...,158,153,144,139,135,135,134,133,131,128
11,Число районных больниц,324,294,263,267,223,215,205,200,191,...,206,417,415,425,418,418,416,409,391,396
12,"в них коек, тыс.",33.8,31.6,28.4,30.8,26.8,26.6,25.7,24.8,24.2,...,"23,7","54,1","54,5","58,1","57,9","55,8","52,6","51,5","49,1","48,4"
13,"средняя мощность одной больницы, коек",104,107,107,116,120,124,125,124,126,...,115,130,131,137,138,134,126,126,126,122
14,Число участковых больниц,4813,4409,3310,2631,628,510,481,438,400,...,124,97,69,68,58,47,32,29,28,21
15,"в них коек, тыс.",156.3,129.0,85.1,62.3,18.1,14.9,14.1,12.4,11.2,...,"3,3","2,8","2,2","2,4","1,9","1,5","1,0","0,9","0,9","0,7"
16,"средняя мощность одной больницы, коек",32,29,26,24,29,29,29,28,28,...,27,29,32,35,33,33,31,31,31,33
17,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,...,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,NaN,NaN
18,Число больничных учреждений,...,6627,6326,5820,5512,5315,5131,5079,4959,...,4775,4574,4397,4351,4297,4275,4 186,4 136,4 146,4 219
19,из них негосударственные,...,29,87,286,313,326,246,220,216,...,227,239,239,263,288,309,318,340,398,446
20,из них частной формы собственности,...,...,...,...,144,173,116,105,110,...,140,162,176,203,236,252,265,290,355,397
21,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"всего, тыс.",...,1569.2,1438.7,1365.9,1349.5,1331.6,"1226,22",1210.0,1186.1,...,"1164,71","1123,51","1060,1",1041.0,"1026,91","1018,71","1 017,61","1 031,11","1 009,81","991,11"
23,из них в негосударственных учреждениях,...,-,7.7,32.1,35.5,29.9,28.5,23.2,20.2,...,"21,8","22,8","21,8","22,2","23,0","24,4","25,7","29,6","28,7","31,8"
24,из них частной формы собственности,...,...,...,...,4.9,4.9,3.8,...,3.3,...,"7,4","9,9","12,1","12,7","14,6","16,5","17,8","21,1","21,8","24,5"
25,на 10 000 человек населения,...,145.5,134.8,131.7,130.0,128.3,118.3,116.8,112.5,...,"109,3","103,8","97,6","95,5","93,9","93,1","92,9","94,4",NaN,NaN
26,Число центральных районных больниц,1196,1103,1078,1046,989,1028,1028,1029,1027,...,994,902,829,815,809,801,789,784,778,757
27,Число районных больниц,146,143,145,148,132,118,116,116,112,...,129,238,230,242,225,224,217,208,202,211
28,Число участковых больниц,-,11,30,40,32,29,25,23,18,...,2,4,4,9,6,5,4,4,4,4
29,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,...,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,NaN,NaN
30,Число больничных учреждений,...,5437,4378,3659,1966,1462,1414,1375,1349,...,1095,1064,1036,1006,996,982,944,929,926,948
31,из них негосударственные,...,-,-,7,7,7,7,4,8,...,6,7,6,3,6,10,10,4,12,12
32,из них частной формы собственности,...,...,...,...,4,4,4,2,5,...,3,4,4,2,5,7,9,4,12,12
33,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"всего, тыс.",...,281.3,232.9,209.5,204.1,190.4,"172,32",163.4,153.4,...,"137,21","143,31","161,9","156,2","155,81","154,11","155,91","157,61","152,41","150,8"
35,из них в негосударственных учреждениях,...,-,-,0.3,0.5,0.4,1.4,0.7,1.6,...,"1,4","2,1","2,3","1,3","2,4","2,6","4,1","3,1","3,9","4,3"
36,из них частной формы собственности,...,...,...,...,0.2,0.2,0.1,...,0.68,...,"0,46","1,02","0,6","0,2","0,6","0,8","2,7","2,3","3,10","3,40"
37,на 10 000 человек населения,...,71.7,60.4,55.3,53.1,49.8,45.1,42.3,40.9,...,"37,0","37,7","42,7","41,4","41,5","41,3","41,9","42,7",NaN,NaN
38,Число центральных районных больниц,602,683,687,688,759,719,721,723,727,...,696,568,597,573,563,560,536,532,533,523
39,Число районных больниц,178,151,118,119,91,97,89,84,79,...,77,179,185,183,193,194,199,201,189,185
40,Число участковых больниц,4813,4398,3280,2591,596,481,456,415,382,...,122,93,65,59,52,42,28,25,24,17

Теперь присоединим ко всем данным, данные из папки за 2005 год

In [54]:
hospital_facilities_total = hospital_facilities_8.merge(hospital_facilities_2005, how='left')

hospital_facilities_total

,name,1990,1995,2000,2005,2006,2007,2008,2009,2010,...,2017,2018,2019,2020,2021,2022,2001,2002,2003,2004
0,Число больничных учреждений,12762,12064,10704,9479,7478,6777,6545,6454,6308,...,5293,5257,5 130,5 065,5 072,5 167,10561,10320,10101,9851
1,из них негосударственные,...,29,87,293,320,333,253,224,224,...,294,319,328,344,410,458,105,97,111,122
2,из них негосударственные,...,29,87,293,320,333,253,224,224,...,294,319,328,344,410,458,104,94,107,119
3,из них частной формы собственности,...,...,...,...,148,177,120,107,115,...,241,259,274,294,367,409,NaN,NaN,NaN,NaN
4,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"всего, тыс.",2037.6,1850.5,1671.6,1575.4,1553.6,1522.1,"1398,52",1373.4,1339.5,...,"1182,71","1172,81","1 173,61","1 188,81","1 162,11","1 141,91",1653.4,1619.7,1596.6,1600.7
8,из них в негосударственных учреждениях,...,2.5,7.7,32.4,35.9,30.3,29.9,24.0,21.7,...,"25,4","27,0","29,8","32,7","32,6","36,1",NaN,NaN,NaN,NaN
9,из них частной формы собственности,...,...,...,...,5.1,5.1,3.9,...,4.1,...,"15,2","17,3","20,5","23,3","24,9","28,0",NaN,NaN,NaN,NaN
10,на 10 000 человек населения,137.4,125.8,115.0,111.3,109.2,107.2,98.6,96.8,93.7,...,"80,5","79,9","80,0","81,3",NaN,NaN,114.4,112.6,111.6,112.5
11,Число центральных районных больниц,1798,1786,1765,1734,1748,1747,1749,1752,1754,...,1372,1361,1 325,1 316,1 311,1 280,1756,1755,1743,1740
12,"в них коек, тыс.",451.0,409.7,373.6,345.1,393.0,380.6,363.5,350.1,327.1,...,"185,5","183,7","177,4","175,4","171,6",164,365.5,359.0,349.8,353.1
13,"средняя мощность одной больницы, коек",251,229,211,199,225,218,208,200,186,...,135,135,134,133,131,128,NaN,NaN,NaN,NaN
14,Число районных больниц,324,294,263,267,223,215,205,200,191,...,418,418,416,409,391,396,266,273,286,278
15,"в них коек, тыс.",33.8,31.6,28.4,30.8,26.8,26.6,25.7,24.8,24.2,...,"57,9","55,8","52,6","51,5","49,1","48,4",29.2,31.0,32.5,31.6
16,"средняя мощность одной больницы, коек",104,107,107,116,120,124,125,124,126,...,138,134,126,126,126,122,NaN,NaN,NaN,NaN
17,Число участковых больниц,4813,4409,3310,2631,628,510,481,438,400,...,58,47,32,29,28,21,3290,3140,3020,2862
18,"в них коек, тыс.",156.3,129.0,85.1,62.3,18.1,14.9,14.1,12.4,11.2,...,"1,9","1,5","1,0","0,9","0,9","0,7",83.4,78.0,73.3,68.6
19,"средняя мощность одной больницы, коек",32,29,26,24,29,29,29,28,28,...,33,33,31,31,31,33,NaN,NaN,NaN,NaN
20,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,...,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,NaN,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
21,Число больничных учреждений,...,6627,6326,5820,5512,5315,5131,5079,4959,...,4297,4275,4 186,4 136,4 146,4 219,6227,6139,6047,6022
22,из них негосударственные,...,29,87,286,313,326,246,220,216,...,288,309,318,340,398,446,105,97,111,122
23,из них негосударственные,...,29,87,286,313,326,246,220,216,...,288,309,318,340,398,446,104,94,107,119
24,из них частной формы собственности,...,...,...,...,144,173,116,105,110,...,236,252,265,290,355,397,NaN,NaN,NaN,NaN
25,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"всего, тыс.",...,1569.2,1438.7,1365.9,1349.5,1331.6,"1226,22",1210.0,1186.1,...,"1026,91","1018,71","1 017,61","1 031,11","1 009,81","991,11",1423.9,1399.3,1388.4,1391.4
29,из них в негосударственных учреждениях,...,-,7.7,32.1,35.5,29.9,28.5,23.2,20.2,...,"23,0","24,4","25,7","29,6","28,7","31,8",NaN,NaN,NaN,NaN
30,из них частной формы собственности,...,...,...,...,4.9,4.9,3.8,...,3.3,...,"14,6","16,5","17,8","21,1","21,8","24,5",NaN,NaN,NaN,NaN
31,на 10 000 человек населения,...,145.5,134.8,131.7,130.0,128.3,118.3,116.8,112.5,...,"93,9","93,1","92,9","94,4",NaN,NaN,133.9,132.1,131.7,133.4
32,Число центральных районных больниц,1196,1103,1078,1046,989,1028,1028,1029,1027,...,809,801,789,784,778,757,NaN,NaN,NaN,NaN
33,Число районных больниц,146,143,145,148,132,118,116,116,112,...,225,224,217,208,202,211,152,158,169,161
34,Число участковых больниц,-,11,30,40,32,29,25,23,18,...,6,5,4,4,4,4,29,35,44,43
35,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,...,В сельской местности,В сельской местности,В сельской местности,В сельской местности,NaN,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности
36,Число больничных учреждений,...,5437,4378,3659,1966,1462,1414,1375,1349,...,996,982,944,929,926,948,4334,4181,4054,3829
37,из них негосударственные,...,-,-,7,7,7,7,4,8,...,6,10,10,4,12,12,1,3,4,3
38,из них частной формы собственности,...,...,...,...,4,4,4,2,5,...,5,7,9,4,12,12,NaN,NaN,NaN,NaN
39,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,"всего, тыс.",...,281.3,232.9,209.5,204.1,190.4,"172,32",163.4,153.4,...,"155,81","154,11","155,91","157,61","152,41","150,8",229.6,220.4,208.2,209.4
43,из них в негосударственных учреждениях,...,-,-,0.3,0.5,0.4,1.4,0.7,1.6,...,"2,4","2,6","4,1","3,1","3,9","4,3",NaN,NaN,NaN,NaN
44,из них частной формы собственности,...,...,...,...,0.2,0.2,0.1,...,0.68,...,"0,6","0,8","2,7","2,3","3,10","3,40",NaN,NaN,NaN,NaN
45,на 10 000 человек населения,...,71.7,60.4,55.3,53.1,49.8,45.1,42.3,40.9,...,"41,5","41,3","41,9","42,7",NaN,NaN,60.1,58.1,55.4,55.1
46,Число центральных районных больниц,602,683,687,688,759,719,721,723,727,...,563,560,536,532,533,523,682,682,683,681
47,Число районных больниц,178,151,118,119,91,97,89,84,79,...,193,194,199,201,189,185,114,115,117,117
48,Число участковых больниц,4813,4398,3280,2591,596,481,456,415,382,...,52,42,28,25,24,17,3261,3105,2976,2819

После соединения уберёмя явные полные дубликаты

In [55]:
hospital_facilities_total = hospital_facilities_total.drop_duplicates().reset_index(drop=True)

Теперь заменим запятые между цифрами на точку для корректного отображения "плавающей" точки в программе по визуализации и построению дашборов.

In [56]:
hospital_facilities_total = hospital_facilities_total.apply(lambda x: x.str.replace(',', '.'))

In [57]:
hospital_facilities_total

,name,1990,1995,2000,2005,2006,2007,2008,2009,2010,...,2017,2018,2019,2020,2021,2022,2001,2002,2003,2004
0,Число больничных учреждений,12762,12064,10704,9479,7478,6777,6545,6454,6308,...,5293,5257,5 130,5 065,5 072,5 167,10561,10320,10101,9851
1,из них негосударственные,...,29,87,293,320,333,253,224,224,...,294,319,328,344,410,458,105,97,111,122
2,из них негосударственные,...,29,87,293,320,333,253,224,224,...,294,319,328,344,410,458,104,94,107,119
3,из них частной формы собственности,...,...,...,...,148,177,120,107,115,...,241,259,274,294,367,409,NaN,NaN,NaN,NaN
4,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,всего. тыс.,2037.6,1850.5,1671.6,1575.4,1553.6,1522.1,1398.52,1373.4,1339.5,...,1182.71,1172.81,1 173.61,1 188.81,1 162.11,1 141.91,1653.4,1619.7,1596.6,1600.7
6,из них в негосударственных учреждениях,...,2.5,7.7,32.4,35.9,30.3,29.9,24.0,21.7,...,25.4,27.0,29.8,32.7,32.6,36.1,NaN,NaN,NaN,NaN
7,из них частной формы собственности,...,...,...,...,5.1,5.1,3.9,...,4.1,...,15.2,17.3,20.5,23.3,24.9,28.0,NaN,NaN,NaN,NaN
8,на 10 000 человек населения,137.4,125.8,115.0,111.3,109.2,107.2,98.6,96.8,93.7,...,80.5,79.9,80.0,81.3,NaN,NaN,114.4,112.6,111.6,112.5
9,Число центральных районных больниц,1798,1786,1765,1734,1748,1747,1749,1752,1754,...,1372,1361,1 325,1 316,1 311,1 280,1756,1755,1743,1740
10,в них коек. тыс.,451.0,409.7,373.6,345.1,393.0,380.6,363.5,350.1,327.1,...,185.5,183.7,177.4,175.4,171.6,164,365.5,359.0,349.8,353.1
11,средняя мощность одной больницы. коек,251,229,211,199,225,218,208,200,186,...,135,135,134,133,131,128,NaN,NaN,NaN,NaN
12,Число районных больниц,324,294,263,267,223,215,205,200,191,...,418,418,416,409,391,396,266,273,286,278
13,в них коек. тыс.,33.8,31.6,28.4,30.8,26.8,26.6,25.7,24.8,24.2,...,57.9,55.8,52.6,51.5,49.1,48.4,29.2,31.0,32.5,31.6
14,средняя мощность одной больницы. коек,104,107,107,116,120,124,125,124,126,...,138,134,126,126,126,122,NaN,NaN,NaN,NaN
15,Число участковых больниц,4813,4409,3310,2631,628,510,481,438,400,...,58,47,32,29,28,21,3290,3140,3020,2862
16,в них коек. тыс.,156.3,129.0,85.1,62.3,18.1,14.9,14.1,12.4,11.2,...,1.9,1.5,1.0,0.9,0.9,0.7,83.4,78.0,73.3,68.6
17,средняя мощность одной больницы. коек,32,29,26,24,29,29,29,28,28,...,33,33,31,31,31,33,NaN,NaN,NaN,NaN
18,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,...,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях,NaN,NaN,В городских поселениях,В городских поселениях,В городских поселениях,В городских поселениях
19,Число больничных учреждений,...,6627,6326,5820,5512,5315,5131,5079,4959,...,4297,4275,4 186,4 136,4 146,4 219,6227,6139,6047,6022
20,из них негосударственные,...,29,87,286,313,326,246,220,216,...,288,309,318,340,398,446,105,97,111,122
21,из них негосударственные,...,29,87,286,313,326,246,220,216,...,288,309,318,340,398,446,104,94,107,119
22,из них частной формы собственности,...,...,...,...,144,173,116,105,110,...,236,252,265,290,355,397,NaN,NaN,NaN,NaN
23,всего. тыс.,...,1569.2,1438.7,1365.9,1349.5,1331.6,1226.22,1210.0,1186.1,...,1026.91,1018.71,1 017.61,1 031.11,1 009.81,991.11,1423.9,1399.3,1388.4,1391.4
24,из них в негосударственных учреждениях,...,-,7.7,32.1,35.5,29.9,28.5,23.2,20.2,...,23.0,24.4,25.7,29.6,28.7,31.8,NaN,NaN,NaN,NaN
25,из них частной формы собственности,...,...,...,...,4.9,4.9,3.8,...,3.3,...,14.6,16.5,17.8,21.1,21.8,24.5,NaN,NaN,NaN,NaN
26,на 10 000 человек населения,...,145.5,134.8,131.7,130.0,128.3,118.3,116.8,112.5,...,93.9,93.1,92.9,94.4,NaN,NaN,133.9,132.1,131.7,133.4
27,Число центральных районных больниц,1196,1103,1078,1046,989,1028,1028,1029,1027,...,809,801,789,784,778,757,NaN,NaN,NaN,NaN
28,Число районных больниц,146,143,145,148,132,118,116,116,112,...,225,224,217,208,202,211,152,158,169,161
29,Число участковых больниц,-,11,30,40,32,29,25,23,18,...,6,5,4,4,4,4,29,35,44,43
30,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,В сельской местности,...,В сельской местности,В сельской местности,В сельской местности,В сельской местности,NaN,NaN,В сельской местности,В сельской местности,В сельской местности,В сельской местности
31,Число больничных учреждений,...,5437,4378,3659,1966,1462,1414,1375,1349,...,996,982,944,929,926,948,4334,4181,4054,3829
32,из них негосударственные,...,-,-,7,7,7,7,4,8,...,6,10,10,4,12,12,1,3,4,3
33,из них частной формы собственности,...,...,...,...,4,4,4,2,5,...,5,7,9,4,12,12,NaN,NaN,NaN,NaN
34,всего. тыс.,...,281.3,232.9,209.5,204.1,190.4,172.32,163.4,153.4,...,155.81,154.11,155.91,157.61,152.41,150.8,229.6,220.4,208.2,209.4
35,из них в негосударственных учреждениях,...,-,-,0.3,0.5,0.4,1.4,0.7,1.6,...,2.4,2.6,4.1,3.1,3.9,4.3,NaN,NaN,NaN,NaN
36,из них частной формы собственности,...,...,...,...,0.2,0.2,0.1,...,0.68,...,0.6,0.8,2.7,2.3,3.10,3.40,NaN,NaN,NaN,NaN
37,на 10 000 человек населения,...,71.7,60.4,55.3,53.1,49.8,45.1,42.3,40.9,...,41.5,41.3,41.9,42.7,NaN,NaN,60.1,58.1,55.4,55.1
38,Число центральных районных больниц,602,683,687,688,759,719,721,723,727,...,563,560,536,532,533,523,682,682,683,681
39,Число районных больниц,178,151,118,119,91,97,89,84,79,...,193,194,199,201,189,185,114,115,117,117
40,Число участковых больниц,4813,4398,3280,2591,596,481,456,415,382,...,52,42,28,25,24,17,3261,3105,2976,2819

Для корректного отображения данных с "плавающей" точкой удалим неразрывный пробел во всех строках датафрейма

In [58]:
hospital_facilities_total.iloc[:,1:] = hospital_facilities_total.iloc[:,1:].apply(lambda x: x.str.replace('\xa0', ''))

### Создание датасетов

Создадим датафреймы где будут: 
- общие значения;
- городские поселения;
- сельская местность.

#### Датасет с общими значениями

In [59]:
hospital_facilities_total_copy = hospital_facilities_total.iloc[:18,:].copy()

hospital_facilities_total_copy

,name,1990,1995,2000,2005,2006,2007,2008,2009,2010,...,2017,2018,2019,2020,2021,2022,2001,2002,2003,2004
0,Число больничных учреждений,12762,12064,10704,9479,7478,6777,6545,6454,6308,...,5293,5257,5130,5065,5072,5167,10561,10320,10101,9851
1,из них негосударственные,...,29,87,293,320,333,253,224,224,...,294,319,328,344,410,458,105,97,111,122
2,из них негосударственные,...,29,87,293,320,333,253,224,224,...,294,319,328,344,410,458,104,94,107,119
3,из них частной формы собственности,...,...,...,...,148,177,120,107,115,...,241,259,274,294,367,409,NaN,NaN,NaN,NaN
4,Число коек в больничных учреждениях:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,всего. тыс.,2037.6,1850.5,1671.6,1575.4,1553.6,1522.1,1398.52,1373.4,1339.5,...,1182.71,1172.81,1173.61,1188.81,1162.11,1141.91,1653.4,1619.7,1596.6,1600.7
6,из них в негосударственных учреждениях,...,2.5,7.7,32.4,35.9,30.3,29.9,24.0,21.7,...,25.4,27.0,29.8,32.7,32.6,36.1,NaN,NaN,NaN,NaN
7,из них частной формы собственности,...,...,...,...,5.1,5.1,3.9,...,4.1,...,15.2,17.3,20.5,23.3,24.9,28.0,NaN,NaN,NaN,NaN
8,на 10 000 человек населения,137.4,125.8,115.0,111.3,109.2,107.2,98.6,96.8,93.7,...,80.5,79.9,80.0,81.3,NaN,NaN,114.4,112.6,111.6,112.5
9,Число центральных районных больниц,1798,1786,1765,1734,1748,1747,1749,1752,1754,...,1372,1361,1325,1316,1311,1280,1756,1755,1743,1740
10,в них коек. тыс.,451.0,409.7,373.6,345.1,393.0,380.6,363.5,350.1,327.1,...,185.5,183.7,177.4,175.4,171.6,164,365.5,359.0,349.8,353.1
11,средняя мощность одной больницы. коек,251,229,211,199,225,218,208,200,186,...,135,135,134,133,131,128,NaN,NaN,NaN,NaN
12,Число районных больниц,324,294,263,267,223,215,205,200,191,...,418,418,416,409,391,396,266,273,286,278
13,в них коек. тыс.,33.8,31.6,28.4,30.8,26.8,26.6,25.7,24.8,24.2,...,57.9,55.8,52.6,51.5,49.1,48.4,29.2,31.0,32.5,31.6
14,средняя мощность одной больницы. коек,104,107,107,116,120,124,125,124,126,...,138,134,126,126,126,122,NaN,NaN,NaN,NaN
15,Число участковых больниц,4813,4409,3310,2631,628,510,481,438,400,...,58,47,32,29,28,21,3290,3140,3020,2862
16,в них коек. тыс.,156.3,129.0,85.1,62.3,18.1,14.9,14.1,12.4,11.2,...,1.9,1.5,1.0,0.9,0.9,0.7,83.4,78.0,73.3,68.6
17,средняя мощность одной больницы. коек,32,29,26,24,29,29,29,28,28,...,33,33,31,31,31,33,NaN,NaN,NaN,NaN

#### Датасет городских поселений

In [60]:
hospital_facilities_urban_settlements = hospital_facilities_total.iloc[19:30,:].copy()

hospital_facilities_urban_settlements

,name,1990,1995,2000,2005,2006,2007,2008,2009,2010,...,2017,2018,2019,2020,2021,2022,2001,2002,2003,2004
19,Число больничных учреждений,...,6627,6326,5820,5512,5315,5131,5079,4959,...,4297,4275,4186,4136,4146,4219,6227,6139,6047,6022
20,из них негосударственные,...,29,87,286,313,326,246,220,216,...,288,309,318,340,398,446,105,97,111,122
21,из них негосударственные,...,29,87,286,313,326,246,220,216,...,288,309,318,340,398,446,104,94,107,119
22,из них частной формы собственности,...,...,...,...,144,173,116,105,110,...,236,252,265,290,355,397,NaN,NaN,NaN,NaN
23,всего. тыс.,...,1569.2,1438.7,1365.9,1349.5,1331.6,1226.22,1210.0,1186.1,...,1026.91,1018.71,1017.61,1031.11,1009.81,991.11,1423.9,1399.3,1388.4,1391.4
24,из них в негосударственных учреждениях,...,-,7.7,32.1,35.5,29.9,28.5,23.2,20.2,...,23.0,24.4,25.7,29.6,28.7,31.8,NaN,NaN,NaN,NaN
25,из них частной формы собственности,...,...,...,...,4.9,4.9,3.8,...,3.3,...,14.6,16.5,17.8,21.1,21.8,24.5,NaN,NaN,NaN,NaN
26,на 10 000 человек населения,...,145.5,134.8,131.7,130.0,128.3,118.3,116.8,112.5,...,93.9,93.1,92.9,94.4,NaN,NaN,133.9,132.1,131.7,133.4
27,Число центральных районных больниц,1196,1103,1078,1046,989,1028,1028,1029,1027,...,809,801,789,784,778,757,NaN,NaN,NaN,NaN
28,Число районных больниц,146,143,145,148,132,118,116,116,112,...,225,224,217,208,202,211,152,158,169,161
29,Число участковых больниц,-,11,30,40,32,29,25,23,18,...,6,5,4,4,4,4,29,35,44,43

#### Датасет сельской местности

In [61]:
hospital_facilities_rural_area = hospital_facilities_total.iloc[31:,:].copy()

hospital_facilities_rural_area

,name,1990,1995,2000,2005,2006,2007,2008,2009,2010,...,2017,2018,2019,2020,2021,2022,2001,2002,2003,2004
31,Число больничных учреждений,...,5437,4378,3659,1966,1462,1414,1375,1349,...,996,982,944,929,926,948,4334,4181,4054,3829
32,из них негосударственные,...,-,-,7,7,7,7,4,8,...,6,10,10,4,12,12,1,3,4,3
33,из них частной формы собственности,...,...,...,...,4,4,4,2,5,...,5,7,9,4,12,12,NaN,NaN,NaN,NaN
34,всего. тыс.,...,281.3,232.9,209.5,204.1,190.4,172.32,163.4,153.4,...,155.81,154.11,155.91,157.61,152.41,150.8,229.6,220.4,208.2,209.4
35,из них в негосударственных учреждениях,...,-,-,0.3,0.5,0.4,1.4,0.7,1.6,...,2.4,2.6,4.1,3.1,3.9,4.3,NaN,NaN,NaN,NaN
36,из них частной формы собственности,...,...,...,...,0.2,0.2,0.1,...,0.68,...,0.6,0.8,2.7,2.3,3.10,3.40,NaN,NaN,NaN,NaN
37,на 10 000 человек населения,...,71.7,60.4,55.3,53.1,49.8,45.1,42.3,40.9,...,41.5,41.3,41.9,42.7,NaN,NaN,60.1,58.1,55.4,55.1
38,Число центральных районных больниц,602,683,687,688,759,719,721,723,727,...,563,560,536,532,533,523,682,682,683,681
39,Число районных больниц,178,151,118,119,91,97,89,84,79,...,193,194,199,201,189,185,114,115,117,117
40,Число участковых больниц,4813,4398,3280,2591,596,481,456,415,382,...,52,42,28,25,24,17,3261,3105,2976,2819

### Транспонирование ранее созданных 3-х датасетов

Далее транспорнируем все три датасета, чтобы индексами были года, а колонками наименования.

#### Транспонированный датасет с общими значениями

In [62]:
hospital_facilities_total_copy = hospital_facilities_total_copy.T

hospital_facilities_total_copy

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
name,Число больничных учреждений,из них негосударственные,из них негосударственные,из них частной формы собственности,Число коек в больничных учреждениях:,всего. тыс.,из них в негосударственных учреждениях,из них частной формы собственности,на 10 000 человек населения,Число центральных районных больниц,в них коек. тыс.,средняя мощность одной больницы. коек,Число районных больниц,в них коек. тыс.,средняя мощность одной больницы. коек,Число участковых больниц,в них коек. тыс.,средняя мощность одной больницы. коек
1990,12762,...,...,...,NaN,2037.6,...,...,137.4,1798,451.0,251,324,33.8,104,4813,156.3,32
1995,12064,29,29,...,NaN,1850.5,2.5,...,125.8,1786,409.7,229,294,31.6,107,4409,129.0,29
2000,10704,87,87,...,NaN,1671.6,7.7,...,115.0,1765,373.6,211,263,28.4,107,3310,85.1,26
2005,9479,293,293,...,NaN,1575.4,32.4,...,111.3,1734,345.1,199,267,30.8,116,2631,62.3,24
2006,7478,320,320,148,NaN,1553.6,35.9,5.1,109.2,1748,393.0,225,223,26.8,120,628,18.1,29
2007,6777,333,333,177,NaN,1522.1,30.3,5.1,107.2,1747,380.6,218,215,26.6,124,510,14.9,29
2008,6545,253,253,120,NaN,1398.52,29.9,3.9,98.6,1749,363.5,208,205,25.7,125,481,14.1,29
2009,6454,224,224,107,NaN,1373.4,24.0,...,96.8,1752,350.1,200,200,24.8,124,438,12.4,28
2010,6308,224,224,115,NaN,1339.5,21.7,4.1,93.7,1754,327.1,186,191,24.2,126,400,11.2,28
2011,6343,220,220,116,NaN,1347.11,20.6,4.1,94.2,1755,324.1,185,177,22.9,129,301,8.3,27
2012,6172,225,225,127,NaN,1332.31,22.6,6.5,92.9,1719,281.0,163,195,21.6,111,237,5.4,23
2013,5870,233,233,143,NaN,1301.91,23.2,7.9,90.6,1690,267.0,158,206,23.7,115,124,3.3,27
2014,5638,246,246,166,NaN,1266.81,24.9,11.0,86.6,1470,224.8,153,417,54.1,130,97,2.8,29
2015,5433,245,245,180,NaN,1222.0,24.1,12.8,83.4,1426,205.6,144,415,54.5,131,69,2.2,32
2016,5357,266,266,205,NaN,1197.2,23.5,12.9,81.6,1388,192.6,139,425,58.1,137,68,2.4,35
2017,5293,294,294,241,NaN,1182.71,25.4,15.2,80.5,1372,185.5,135,418,57.9,138,58,1.9,33
2018,5257,319,319,259,NaN,1172.81,27.0,17.3,79.9,1361,183.7,135,418,55.8,134,47,1.5,33
2019,5130,328,328,274,NaN,1173.61,29.8,20.5,80.0,1325,177.4,134,416,52.6,126,32,1.0,31
2020,5065,344,344,294,NaN,1188.81,32.7,23.3,81.3,1316,175.4,133,409,51.5,126,29,0.9,31
2021,5072,410,410,367,NaN,1162.11,32.6,24.9,NaN,1311,171.6,131,391,49.1,126,28,0.9,31
2022,5167,458,458,409,NaN,1141.91,36.1,28.0,NaN,1280,164,128,396,48.4,122,21,0.7,33
2001,10561,105,104,NaN,NaN,1653.4,NaN,NaN,114.4,1756,365.5,NaN,266,29.2,NaN,3290,83.4,NaN
2002,10320,97,94,NaN,NaN,1619.7,NaN,NaN,112.6,1755,359.0,NaN,273,31.0,NaN,3140,78.0,NaN
2003,10101,111,107,NaN,NaN,1596.6,NaN,NaN,111.6,1743,349.8,NaN,286,32.5,NaN,3020,73.3,NaN
2004,9851,122,119,NaN,NaN,1600.7,NaN,NaN,112.5,1740,353.1,NaN,278,31.6,NaN,2862,68.6,NaN

Теперь сделаем первую строку названиями колонок

In [63]:
hospital_facilities_total_copy.columns = list(hospital_facilities_total_copy.iloc[0])

hospital_facilities_total_copy = hospital_facilities_total_copy.drop(index = 'name')

hospital_facilities_total_copy

,Число больничных учреждений,из них негосударственные,из них негосударственные,из них частной формы собственности,Число коек в больничных учреждениях:,всего. тыс.,из них в негосударственных учреждениях,из них частной формы собственности,на 10 000 человек населения,Число центральных районных больниц,в них коек. тыс.,средняя мощность одной больницы. коек,Число районных больниц,в них коек. тыс.,средняя мощность одной больницы. коек,Число участковых больниц,в них коек. тыс.,средняя мощность одной больницы. коек
1990,12762,...,...,...,NaN,2037.6,...,...,137.4,1798,451.0,251,324,33.8,104,4813,156.3,32
1995,12064,29,29,...,NaN,1850.5,2.5,...,125.8,1786,409.7,229,294,31.6,107,4409,129.0,29
2000,10704,87,87,...,NaN,1671.6,7.7,...,115.0,1765,373.6,211,263,28.4,107,3310,85.1,26
2005,9479,293,293,...,NaN,1575.4,32.4,...,111.3,1734,345.1,199,267,30.8,116,2631,62.3,24
2006,7478,320,320,148,NaN,1553.6,35.9,5.1,109.2,1748,393.0,225,223,26.8,120,628,18.1,29
2007,6777,333,333,177,NaN,1522.1,30.3,5.1,107.2,1747,380.6,218,215,26.6,124,510,14.9,29
2008,6545,253,253,120,NaN,1398.52,29.9,3.9,98.6,1749,363.5,208,205,25.7,125,481,14.1,29
2009,6454,224,224,107,NaN,1373.4,24.0,...,96.8,1752,350.1,200,200,24.8,124,438,12.4,28
2010,6308,224,224,115,NaN,1339.5,21.7,4.1,93.7,1754,327.1,186,191,24.2,126,400,11.2,28
2011,6343,220,220,116,NaN,1347.11,20.6,4.1,94.2,1755,324.1,185,177,22.9,129,301,8.3,27
2012,6172,225,225,127,NaN,1332.31,22.6,6.5,92.9,1719,281.0,163,195,21.6,111,237,5.4,23
2013,5870,233,233,143,NaN,1301.91,23.2,7.9,90.6,1690,267.0,158,206,23.7,115,124,3.3,27
2014,5638,246,246,166,NaN,1266.81,24.9,11.0,86.6,1470,224.8,153,417,54.1,130,97,2.8,29
2015,5433,245,245,180,NaN,1222.0,24.1,12.8,83.4,1426,205.6,144,415,54.5,131,69,2.2,32
2016,5357,266,266,205,NaN,1197.2,23.5,12.9,81.6,1388,192.6,139,425,58.1,137,68,2.4,35
2017,5293,294,294,241,NaN,1182.71,25.4,15.2,80.5,1372,185.5,135,418,57.9,138,58,1.9,33
2018,5257,319,319,259,NaN,1172.81,27.0,17.3,79.9,1361,183.7,135,418,55.8,134,47,1.5,33
2019,5130,328,328,274,NaN,1173.61,29.8,20.5,80.0,1325,177.4,134,416,52.6,126,32,1.0,31
2020,5065,344,344,294,NaN,1188.81,32.7,23.3,81.3,1316,175.4,133,409,51.5,126,29,0.9,31
2021,5072,410,410,367,NaN,1162.11,32.6,24.9,NaN,1311,171.6,131,391,49.1,126,28,0.9,31
2022,5167,458,458,409,NaN,1141.91,36.1,28.0,NaN,1280,164,128,396,48.4,122,21,0.7,33
2001,10561,105,104,NaN,NaN,1653.4,NaN,NaN,114.4,1756,365.5,NaN,266,29.2,NaN,3290,83.4,NaN
2002,10320,97,94,NaN,NaN,1619.7,NaN,NaN,112.6,1755,359.0,NaN,273,31.0,NaN,3140,78.0,NaN
2003,10101,111,107,NaN,NaN,1596.6,NaN,NaN,111.6,1743,349.8,NaN,286,32.5,NaN,3020,73.3,NaN
2004,9851,122,119,NaN,NaN,1600.7,NaN,NaN,112.5,1740,353.1,NaN,278,31.6,NaN,2862,68.6,NaN

#### Транспонированный датасет с городскими поселениями

In [64]:
hospital_facilities_urban_settlements = hospital_facilities_urban_settlements.T

# изменение первой строки в названия столбцов

hospital_facilities_urban_settlements.columns = list(hospital_facilities_urban_settlements.iloc[0])

hospital_facilities_urban_settlements = hospital_facilities_urban_settlements.drop(index = 'name')

hospital_facilities_urban_settlements

,Число больничных учреждений,из них негосударственные,из них негосударственные,из них частной формы собственности,всего. тыс.,из них в негосударственных учреждениях,из них частной формы собственности,на 10 000 человек населения,Число центральных районных больниц,Число районных больниц,Число участковых больниц
1990,...,...,...,...,...,...,...,...,1196,146,-
1995,6627,29,29,...,1569.2,-,...,145.5,1103,143,11
2000,6326,87,87,...,1438.7,7.7,...,134.8,1078,145,30
2005,5820,286,286,...,1365.9,32.1,...,131.7,1046,148,40
2006,5512,313,313,144,1349.5,35.5,4.9,130.0,989,132,32
2007,5315,326,326,173,1331.6,29.9,4.9,128.3,1028,118,29
2008,5131,246,246,116,1226.22,28.5,3.8,118.3,1028,116,25
2009,5079,220,220,105,1210.0,23.2,...,116.8,1029,116,23
2010,4959,216,216,110,1186.1,20.2,3.3,112.5,1027,112,18
2011,5048,215,215,113,1198.31,20.0,3.7,113.3,1033,101,11
2012,4956,220,220,124,1188.91,21.3,6.1,112.0,985,127,9
2013,4775,227,227,140,1164.71,21.8,7.4,109.3,994,129,2
2014,4574,239,239,162,1123.51,22.8,9.9,103.8,902,238,4
2015,4397,239,239,176,1060.1,21.8,12.1,97.6,829,230,4
2016,4351,263,263,203,1041.0,22.2,12.7,95.5,815,242,9
2017,4297,288,288,236,1026.91,23.0,14.6,93.9,809,225,6
2018,4275,309,309,252,1018.71,24.4,16.5,93.1,801,224,5
2019,4186,318,318,265,1017.61,25.7,17.8,92.9,789,217,4
2020,4136,340,340,290,1031.11,29.6,21.1,94.4,784,208,4
2021,4146,398,398,355,1009.81,28.7,21.8,NaN,778,202,4
2022,4219,446,446,397,991.11,31.8,24.5,NaN,757,211,4
2001,6227,105,104,NaN,1423.9,NaN,NaN,133.9,NaN,152,29
2002,6139,97,94,NaN,1399.3,NaN,NaN,132.1,NaN,158,35
2003,6047,111,107,NaN,1388.4,NaN,NaN,131.7,NaN,169,44
2004,6022,122,119,NaN,1391.4,NaN,NaN,133.4,NaN,161,43

#### Транспонированный датасет сельской местности

In [65]:
hospital_facilities_rural_area = hospital_facilities_rural_area.T

# изменение первой строки в название столбцов

hospital_facilities_rural_area.columns = list(hospital_facilities_rural_area.iloc[0])

hospital_facilities_rural_area = hospital_facilities_rural_area.drop(index = 'name')

In [66]:
hospital_facilities_rural_area

,Число больничных учреждений,из них негосударственные,из них частной формы собственности,всего. тыс.,из них в негосударственных учреждениях,из них частной формы собственности,на 10 000 человек населения,Число центральных районных больниц,Число районных больниц,Число участковых больниц
1990,...,...,...,...,...,...,...,602,178,4813
1995,5437,-,...,281.3,-,...,71.7,683,151,4398
2000,4378,-,...,232.9,-,...,60.4,687,118,3280
2005,3659,7,...,209.5,0.3,...,55.3,688,119,2591
2006,1966,7,4,204.1,0.5,0.2,53.1,759,91,596
2007,1462,7,4,190.4,0.4,0.2,49.8,719,97,481
2008,1414,7,4,172.32,1.4,0.1,45.1,721,89,456
2009,1375,4,2,163.4,0.7,...,42.3,723,84,415
2010,1349,8,5,153.4,1.6,0.68,40.9,727,79,382
2011,1295,5,3,148.81,0.6,0.46,39.9,722,76,290
2012,1216,5,3,143.41,1.3,0.46,38.5,734,68,228
2013,1095,6,3,137.21,1.4,0.46,37.0,696,77,122
2014,1064,7,4,143.31,2.1,1.02,37.7,568,179,93
2015,1036,6,4,161.9,2.3,0.6,42.7,597,185,65
2016,1006,3,2,156.2,1.3,0.2,41.4,573,183,59
2017,996,6,5,155.81,2.4,0.6,41.5,563,193,52
2018,982,10,7,154.11,2.6,0.8,41.3,560,194,42
2019,944,10,9,155.91,4.1,2.7,41.9,536,199,28
2020,929,4,4,157.61,3.1,2.3,42.7,532,201,25
2021,926,12,12,152.41,3.9,3.10,NaN,533,189,24
2022,948,12,12,150.8,4.3,3.40,NaN,523,185,17
2001,4334,1,NaN,229.6,NaN,NaN,60.1,682,114,3261
2002,4181,3,NaN,220.4,NaN,NaN,58.1,682,115,3105
2003,4054,4,NaN,208.2,NaN,NaN,55.4,683,117,2976
2004,3829,3,NaN,209.4,NaN,NaN,55.1,681,117,2819

### Сохранение датасетов в csv файл для дальнейшей визуализации

In [67]:
hospital_facilities_total_copy.to_csv('hospital_facilities_total_copy.csv')

In [68]:
hospital_facilities_urban_settlements.to_csv('hospital_facilities_urban_settlements.csv')

In [69]:
hospital_facilities_rural_area.to_csv('hospital_facilities_rural_area.csv')

### Ссылка на дашборд

Дашборд выполнен в программе Tableau и доступен по [ссылке](https://public.tableau.com/views/hospital_facilities_corrected/sheet16?:language=en-US&:sid=&:display_count=n&:origin=viz_share_link)

### Выводы по разделу

В период с 1990 по 2022 гг:  

- число государственных больничных организаций снизилось на 40,5%;
- в 2.76 раза увеличилось число частных больниц;
- количество участковых (сельских) больниц уменьшилось в 229 раза.

## Дома ребенка. Ресурсы и деятельность организаций здравоохранения.

### Предположение

За период 1990 - 2022 количество детей в домах ребенка снизилось в 3 раза.

### Загрузка и предобработка файлов

In [70]:
сhildren_homes_2005 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2005/Ресурсы и деятельность учреждений здравоохранения/дома ребенка.csv')

Сделаем понятными названия столбцов - по годам

In [71]:
сhildren_homes_2005.columns = ['name', '1990', '1995', '2000', '2001', '2002', '2003', '2004']

сhildren_homes_2005 = сhildren_homes_2005.drop(index = 0).reset_index(drop=True)

In [72]:
сhildren_homes_2005.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18 non-null     object
 1   1990    14 non-null     float64
 2   1995    14 non-null     float64
 3   2000    14 non-null     float64
 4   2001    14 non-null     float64
 5   2002    14 non-null     float64
 6   2003    14 non-null     float64
 7   2004    14 non-null     float64
dtypes: float64(7), object(1)
memory usage: 1.3+ KB

In [73]:
сhildren_homes_2005

,name,1990,1995,2000,2001,2002,2003,2004
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0
5,3 года и старше,5994.0,5774.0,3662.0,4138.0,4233.0,4100.0,3943.0
6,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,14384.0,14660.0,14520.0,15215.0
7,Поступило детей в течение года,10987.0,11533.0,13291.0,13168.0,13959.0,14626.0,16550.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,5777.0,4475.0,3471.0,3359.0,3368.0,3476.0,3654.0
10,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,9806.0,10591.0,11150.0,12824.0
11,Выбыло детей в течение года,10741.0,10349.0,12895.0,12636.0,13497.0,14231.0,15187.0
12,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0
14,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0
17,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0

In [74]:
сhildren_homes_2007 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2007/Ресурсы и деятельность учреждений здравоохранения/дома ребенка.csv')

сhildren_homes_2007

,0,1,2,3,4,5
0,NaN,1990.0,1995.0,2000.0,2005.0,2006.0
1,Число домов ребенка (на конец года),265.0,252.0,254.0,254.0,249.0
2,"В них детей, человек",18506.0,18346.0,19345.0,20621.0,20342.0
3,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
4,0-12 месяцев,3229.0,3822.0,5178.0,6212.0,5598.0
5,1-3 года,9283.0,8750.0,10505.0,10736.0,11181.0
6,3 года и старше,5994.0,5774.0,3662.0,3673.0,3563.0
7,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,16317.0,13873.0
8,Поступило детей в течение года,10987.0,11533.0,13291.0,15068.0,14440.0
9,в том числе:,NaN,NaN,NaN,NaN,NaN
10,поступившие от родителей,5777.0,4475.0,3471.0,3037.0,2995.0
11,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,12031.0,11445.0
12,Выбыло детей в течение года,10741.0,10349.0,12895.0,13949.0,14412.0
13,в том числе:,NaN,NaN,NaN,NaN,NaN
14,взято родителями,3643.0,3061.0,2871.0,2665.0,2666.0
15,взято для усыновления,2060.0,3727.0,6689.0,7232.0,7770.0
16,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN
17,в физическом развитии,8941.0,10545.0,11174.0,9994.0,9737.0
18,в психическом развитии,12999.0,15271.0,15872.0,15207.0,14956.0

Сделаем понятными названия столбцов - по годам

In [75]:
сhildren_homes_2007.columns = ['name', '1990', '1995', '2000', '2005', '2006']

сhildren_homes_2007 = сhildren_homes_2007.drop(index = 0).reset_index(drop=True)

In [76]:
сhildren_homes_2007.head()

,name,1990,1995,2000,2005,2006
0,Число домов ребенка (на конец года),265.0,252.0,254.0,254.0,249.0
1,"В них детей, человек",18506.0,18346.0,19345.0,20621.0,20342.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,6212.0,5598.0
4,1-3 года,9283.0,8750.0,10505.0,10736.0,11181.0

In [77]:
сhildren_homes_2009 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2009/Ресурсы и деятельность учреждений здравоохранения/дома ребенка.csv')

сhildren_homes_2009

,0,1,2,3,4,5
0,NaN,1995.0,2000.0,2005.0,2007.0,2008.0
1,Число домов ребенка (на конец года),252.0,254.0,254.0,249.0,244.0
2,"В них детей, человек",18346.0,19345.0,20621.0,18480.0,17781.0
3,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
4,0-12 месяцев,3822.0,5178.0,6212.0,4768.0,5052.0
5,1-3 года,8750.0,10505.0,10736.0,9856.0,8988.0
6,3 года и старше,5774.0,3662.0,3673.0,3856.0,3741.0
7,Из общей численности детей - сироты и оставшие...,10455.0,14115.0,16317.0,14792.0,13588.0
8,Поступило детей в течение года,11533.0,13291.0,15068.0,14039.0,14823.0
9,в том числе:,NaN,NaN,NaN,NaN,NaN
10,поступившие от родителей,4475.0,3471.0,3037.0,3188.0,4236.0
11,сироты и оставшиеся без попечения родителей,6773.0,9820.0,12031.0,10851.0,10587.0
12,Выбыло детей в течение года,10349.0,12895.0,13949.0,15543.0,15186.0
13,из них:,NaN,NaN,NaN,NaN,NaN
14,взято родителями,3061.0,2871.0,2665.0,2672.0,3202.0
15,взято для усыновления,3727.0,6689.0,7232.0,7979.0,7318.0
16,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN
17,в физическом развитии,10545.0,11174.0,9994.0,9303.0,8637.0
18,в психическом развитии,15271.0,15872.0,15207.0,13912.0,13377.0

Сделаем понятными названия столбцов - по годам

In [78]:
сhildren_homes_2009.columns = ['name', '1995', '2000', '2005', '2007', '2008']

сhildren_homes_2009 = сhildren_homes_2009.drop(index = 0).reset_index(drop=True)

In [79]:
сhildren_homes_2009.head()

,name,1995,2000,2005,2007,2008
0,Число домов ребенка (на конец года),252.0,254.0,254.0,249.0,244.0
1,"В них детей, человек",18346.0,19345.0,20621.0,18480.0,17781.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3822.0,5178.0,6212.0,4768.0,5052.0
4,1-3 года,8750.0,10505.0,10736.0,9856.0,8988.0

In [80]:
сhildren_homes_2011 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2011/Ресурсы и деятельность учреждений здравоохранения/дома ребенка.csv')

сhildren_homes_2011

,0,1,2,3,4,5
0,NaN,1995.0,2000.0,2005.0,2009.0,2010.0
1,Число домов ребенка (на конец года),252.0,254.0,254.0,243.0,227.0
2,"В них детей, человек",18346.0,19345.0,20621.0,17767.0,17483.0
3,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
4,0-12 месяцев,3822.0,5178.0,6212.0,4942.0,4493.0
5,1-3 года,8750.0,10505.0,10736.0,9322.0,9676.0
6,3 года и старше,5774.0,3662.0,3673.0,3503.0,3314.0
7,Из общей численности детей - сироты и оставшие...,10455.0,14115.0,16317.0,13062.0,12707.0
8,Поступило детей в течение года,11533.0,13291.0,15068.0,15166.0,15010.0
9,в том числе:,NaN,NaN,NaN,NaN,NaN
10,поступившие от родителей,4475.0,3471.0,3037.0,4485.0,4907.0
11,сироты и оставшиеся без попечения родителей,6773.0,9820.0,12031.0,10681.0,10071.0
12,Выбыло детей в течение года,10349.0,12895.0,13949.0,14814.0,14988.0
13,из них:,NaN,NaN,NaN,NaN,NaN
14,взято родителями,3061.0,2871.0,2665.0,3506.0,4332.0
15,взято для усыновления,3727.0,6689.0,7232.0,6912.0,6452.0
16,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN
17,в физическом развитии,10545.0,11174.0,9994.0,7867.0,7681.0
18,в психическом развитии,15271.0,15872.0,15207.0,12596.0,12231.0

Сделаем понятными названия столбцов - по годам

In [81]:
сhildren_homes_2011.columns = ['name', '1995', '2000', '2005', '2009', '2010']

сhildren_homes_2011 = сhildren_homes_2011.drop(index = 0).reset_index(drop=True)

In [82]:
сhildren_homes_2011

,name,1995,2000,2005,2009,2010
0,Число домов ребенка (на конец года),252.0,254.0,254.0,243.0,227.0
1,"В них детей, человек",18346.0,19345.0,20621.0,17767.0,17483.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3822.0,5178.0,6212.0,4942.0,4493.0
4,1-3 года,8750.0,10505.0,10736.0,9322.0,9676.0
5,3 года и старше,5774.0,3662.0,3673.0,3503.0,3314.0
6,Из общей численности детей - сироты и оставшие...,10455.0,14115.0,16317.0,13062.0,12707.0
7,Поступило детей в течение года,11533.0,13291.0,15068.0,15166.0,15010.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,4475.0,3471.0,3037.0,4485.0,4907.0
10,сироты и оставшиеся без попечения родителей,6773.0,9820.0,12031.0,10681.0,10071.0
11,Выбыло детей в течение года,10349.0,12895.0,13949.0,14814.0,14988.0
12,из них:,NaN,NaN,NaN,NaN,NaN
13,взято родителями,3061.0,2871.0,2665.0,3506.0,4332.0
14,взято для усыновления,3727.0,6689.0,7232.0,6912.0,6452.0
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,10545.0,11174.0,9994.0,7867.0,7681.0
17,в психическом развитии,15271.0,15872.0,15207.0,12596.0,12231.0

In [83]:
сhildren_homes_2013 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2013/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.4. дома ребенка1).csv')

сhildren_homes_2013

,Unnamed: 0,2000,2005,2010,2011,2012
0,Число домов ребенка (на конец года),254.0,254.0,227.0,218.0,207.0
1,"В них детей, человек",19345.0,20621.0,17483.0,16296.0,15993.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,5178.0,6212.0,4493.0,3998.0,3977.0
4,1-3 года,10505.0,10736.0,9676.0,8884.0,8427.0
5,3 года и старше,3662.0,3673.0,3314.0,3414.0,3589.0
6,Из общей численности детей – сироты и оставшие...,14115.0,16317.0,12707.0,11803.0,11145.0
7,Поступило детей в течение года,13291.0,15068.0,15010.0,13941.0,13762.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,3471.0,3037.0,4907.0,4580.0,4863.0
10,сироты и оставшиеся без попечения родителей,9820.0,12031.0,10071.0,9361.0,8899.0
11,Выбыло детей в течение года,12895.0,13949.0,14988.0,14842.0,13767.0
12,из них:,NaN,NaN,NaN,NaN,NaN
13,взято родителями,2871.0,2665.0,4332.0,4274.0,4047.0
14,взято для усыновления,6689.0,7232.0,6452.0,6514.0,5639.0
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,11174.0,9994.0,7681.0,7339.0,6512.0
17,в психическом развитии,15872.0,15207.0,12231.0,11339.0,10829.0

Сделаем понятными названия столбцов - по годам

In [84]:
сhildren_homes_2013.columns = ['name', '2000', '2005', '2010', '2011', '2012']

сhildren_homes_2013

,name,2000,2005,2010,2011,2012
0,Число домов ребенка (на конец года),254.0,254.0,227.0,218.0,207.0
1,"В них детей, человек",19345.0,20621.0,17483.0,16296.0,15993.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,5178.0,6212.0,4493.0,3998.0,3977.0
4,1-3 года,10505.0,10736.0,9676.0,8884.0,8427.0
5,3 года и старше,3662.0,3673.0,3314.0,3414.0,3589.0
6,Из общей численности детей – сироты и оставшие...,14115.0,16317.0,12707.0,11803.0,11145.0
7,Поступило детей в течение года,13291.0,15068.0,15010.0,13941.0,13762.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,3471.0,3037.0,4907.0,4580.0,4863.0
10,сироты и оставшиеся без попечения родителей,9820.0,12031.0,10071.0,9361.0,8899.0
11,Выбыло детей в течение года,12895.0,13949.0,14988.0,14842.0,13767.0
12,из них:,NaN,NaN,NaN,NaN,NaN
13,взято родителями,2871.0,2665.0,4332.0,4274.0,4047.0
14,взято для усыновления,6689.0,7232.0,6452.0,6514.0,5639.0
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,11174.0,9994.0,7681.0,7339.0,6512.0
17,в психическом развитии,15872.0,15207.0,12231.0,11339.0,10829.0

In [85]:
сhildren_homes_2015 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2015/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.4. дома ребенка1).csv')

сhildren_homes_2015

,Unnamed: 0,2005,2010,2011,2012,2013,2014
0,Число домов ребенка (на конец года),254.0,227.0,218.0,207.0,194.0,176.0
1,"В них детей, человек",20621.0,17483.0,16296.0,15993.0,13977.0,11530.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,6212.0,4493.0,3998.0,3977.0,3358.0,2821.0
4,1-3 года,10736.0,9676.0,8884.0,8427.0,7219.0,6024.0
5,3 года и старше,3673.0,3314.0,3414.0,3589.0,3400.0,2685.0
6,Из общей численности детей – сироты и оставшие...,16317.0,12707.0,11803.0,11145.0,9333.0,6892.0
7,Поступило детей в течение года,15068.0,15010.0,13941.0,13762.0,13562.0,11655.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,3037.0,4907.0,4580.0,4863.0,5173.0,5091.0
10,сироты и оставшиеся без попечения родителей,12031.0,10071.0,9361.0,8899.0,8389.0,6564.0
11,Выбыло детей в течение года,13949.0,14988.0,14842.0,13767.0,15066.0,13068.0
12,из них:,NaN,NaN,NaN,NaN,NaN,NaN
13,взято родителями,2665.0,4332.0,4274.0,4047.0,4542.0,4494.0
14,взято для усыновления,7232.0,6452.0,6514.0,5639.0,5796.0,4853.0
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,9994.0,7681.0,7339.0,6512.0,5788.0,4884.0
17,в психическом развитии,15207.0,12231.0,11339.0,10829.0,9453.0,7737.0

Сделаем понятными названия столбцов - по годам

In [86]:
сhildren_homes_2015.columns = ['name', '2005', '2010', '2011', '2012', '2013', '2014']

сhildren_homes_2015.head()

,name,2005,2010,2011,2012,2013,2014
0,Число домов ребенка (на конец года),254.0,227.0,218.0,207.0,194.0,176.0
1,"В них детей, человек",20621.0,17483.0,16296.0,15993.0,13977.0,11530.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,6212.0,4493.0,3998.0,3977.0,3358.0,2821.0
4,1-3 года,10736.0,9676.0,8884.0,8427.0,7219.0,6024.0

In [87]:
сhildren_homes_2017 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2017/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.4. дома ребенка1).csv')

сhildren_homes_2017

,Unnamed: 0,2005,2010,2013,2014,2015,2016
0,Число домов ребенка (на конец года),254.0,227.0,194.0,176.0,166.0,161.0
1,"В них детей, человек",20621.0,17483.0,13977.0,11530.0,10245.0,8575.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,6212.0,4493.0,3358.0,2821.0,2373.0,2133.0
4,1-3 года,10736.0,9676.0,7219.0,6024.0,5456.0,4549.0
5,3 года и старше,3673.0,3314.0,3400.0,2685.0,2416.0,1893.0
6,Из общей численности детей – сироты и оставшие...,16317.0,12707.0,9333.0,6892.0,5439.0,4170.0
7,Поступило детей в течение года,15068.0,15010.0,13562.0,11655.0,11984.0,11375.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,3037.0,4907.0,5173.0,5091.0,5800.0,5907.0
10,сироты и оставшиеся без попечения родителей,12031.0,10071.0,8389.0,6564.0,6142.0,5468.0
11,Выбыло детей в течение года,13949.0,14988.0,15066.0,13068.0,13105.0,12899.0
12,из них:,NaN,NaN,NaN,NaN,NaN,NaN
13,взято родителями,2665.0,4332.0,4542.0,4494.0,5389.0,5963.0
14,взято для усыновления,7232.0,6452.0,5796.0,4853.0,4110.0,3451.0
15,"Численность детей, \nотстающих:",NaN,NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,9994.0,7681.0,5788.0,4884.0,3945.0,3407.0
17,в психическом развитии,15207.0,12231.0,9453.0,7737.0,6726.0,5727.0

Сделаем понятными названия столбцов - по годам

In [88]:
сhildren_homes_2017.columns = ['name', '2005', '2010', '2013', '2014', '2015', '2016']

сhildren_homes_2017.head()

,name,2005,2010,2013,2014,2015,2016
0,Число домов ребенка (на конец года),254.0,227.0,194.0,176.0,166.0,161.0
1,"В них детей, человек",20621.0,17483.0,13977.0,11530.0,10245.0,8575.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,6212.0,4493.0,3358.0,2821.0,2373.0,2133.0
4,1-3 года,10736.0,9676.0,7219.0,6024.0,5456.0,4549.0

In [89]:
сhildren_homes_2019 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2019/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.4. дома ребенка1).csv')

сhildren_homes_2019

,Unnamed: 0,2005,2010,2015,2016,2017,2018
0,Число домов ребенка \n(на конец года),254.0,227.0,166.0,161.0,154.0,145.0
1,"В них детей, человек",20621.0,17483.0,10245.0,8575.0,7774.0,7524.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0 – 12 месяцев,6212.0,4493.0,2373.0,2133.0,1989.0,1968.0
4,1 – 3 года,10736.0,9676.0,5456.0,4549.0,4077.0,3920.0
5,3 года и старше,3673.0,3314.0,2416.0,1893.0,1708.0,1636.0
6,Из общей численности детей – сироты и оставшие...,16317.0,12707.0,5439.0,4170.0,3543.0,3504.0
7,Поступило детей в течение года,15068.0,15010.0,11984.0,11375.0,11023.0,10994.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,3037.0,4907.0,5800.0,5907.0,6045.0,6187.0
10,сироты и оставшиеся без попечения родителей,12031.0,10071.0,6142.0,5468.0,4978.0,4807.0
11,Выбыло детей в течение года,13949.0,14988.0,13105.0,12899.0,11675.0,11204.0
12,из них:,NaN,NaN,NaN,NaN,NaN,NaN
13,взято родителями,2665.0,4332.0,5389.0,5963.0,6041.0,6257.0
14,взято для усыновления,7232.0,6452.0,4110.0,3451.0,2784.0,2739.0
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,9994.0,7681.0,3945.0,3407.0,2883.0,2775.0
17,в психическом развитии,15207.0,12231.0,6726.0,5727.0,4961.0,4647.0

Сделаем понятными названия столбцов - по годам

In [90]:
сhildren_homes_2019.columns = ['name', '2005', '2010', '2015', '2016', '2017', '2018']

сhildren_homes_2019.head()

,name,2005,2010,2015,2016,2017,2018
0,Число домов ребенка \n(на конец года),254.0,227.0,166.0,161.0,154.0,145.0
1,"В них детей, человек",20621.0,17483.0,10245.0,8575.0,7774.0,7524.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0 – 12 месяцев,6212.0,4493.0,2373.0,2133.0,1989.0,1968.0
4,1 – 3 года,10736.0,9676.0,5456.0,4549.0,4077.0,3920.0

In [91]:
сhildren_homes_2021 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2021/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.4. дома ребенка1).csv')

сhildren_homes_2021

,Unnamed: 0,2005,2010,2015,2018,2019,2020
0,Число домов ребенка \n(на конец года),254,227,166,145,139,136
1,"В них детей, человек",20 621,17 483,10 245,7 524,7 059,6 166
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0 – 12 месяцев,6 212,4 493,2 373,1 968,1 764,1 480
4,1 – 3 года,10 736,9 676,5 456,3 920,3 747,3 244
5,3 года и старше,3 673,3 314,2 416,1 636,1 548,1 442
6,Из общей численности детей – сироты и оставшие...,16 317,12 707,5 439,3 504,3 140,3 067
7,Поступило детей в течение года,15 068,15 010,11 984,10 994,11 304,8 602
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,3 037,4 907,5 800,6 187,6 767,4 368
10,сироты и оставшиеся без попечения родителей,12 031,10 071,6 142,4 807,4 537,4 234
11,Выбыло детей в течение года,13 949,14 988,13 105,11 204,11 603,9 372
12,из них:,NaN,NaN,NaN,NaN,NaN,NaN
13,взято родителями,2 665,4 332,5 389,6 257,6 563,5 390
14,взято для усыновления,7 232,6 452,4 110,2 739,2 702,1 939
15,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN
16,в физическом развитии,9 994,7 681,3 945,2 775,2 326,2 240
17,в психическом развитии,15 207,12 231,6 726,4 647,4 124,3 422

Сделаем понятными названия столбцов - по годам

In [92]:
сhildren_homes_2021.columns = ['name', '2005', '2010', '2015', '2018', '2019', '2020']

сhildren_homes_2021.head()

,name,2005,2010,2015,2018,2019,2020
0,Число домов ребенка \n(на конец года),254,227,166,145,139,136
1,"В них детей, человек",20 621,17 483,10 245,7 524,7 059,6 166
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0 – 12 месяцев,6 212,4 493,2 373,1 968,1 764,1 480
4,1 – 3 года,10 736,9 676,5 456,3 920,3 747,3 244

In [93]:
сhildren_homes_2023 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2023/3.4. ДОМА РЕБЕНКА1) - 3.4.csv')

сhildren_homes_2023

,3.4. ДОМА РЕБЕНКА1),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,2010,2015,2019,2020,2021,2022
1,Число домов ребенка (на конец года),227,166,139,136,134,116
2,"В них детей, человек",17 483,10 245,7 059,6 166,5 968,5 324
3,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
4,0 – 12 месяцев,4 493,2 373,1 764,1 480,1 444,1 282
5,1 – 3 года,9 676,5 456,3 747,3 244,3 069,2 770
6,3 года и старше,3 314,2 416,1 548,1 442,1 455,1 272
7,Из общей численности детей – сироты и оставшие...,12 707,5 439,3 140,3 067,2 721,2 310
8,Поступило детей в течение года,15 010,11 984,11 304,8 602,9 819,9 721
9,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN
10,поступившие от родителей,4 907,5 800,6 767,4 368,5 366,NaN
11,сироты и оставшиеся без по­печения родителей,10 071,6 142,4 537,4 234,4 453,4 494
12,Выбыло детей в течение года,14 988,13 105,11 603,9 372,9 950,9 841
13,из них:,NaN,NaN,NaN,NaN,NaN,NaN
14,взято родителями,4 332,5 389,6 563,5 390,5 488,5 531
15,взято для усыновления,6 452,4 110,2 702,1 939,2 276,382
16,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN
17,в физическом развитии,7 681,3 945,2 326,2 240,2 053,1 875
18,в психическом развитии,12 231,6 726,4 124,3 422,3 408,3 082

Сделаем понятными названия столбцов - по годам

In [94]:
сhildren_homes_2023.columns = ['name', '2010', '2015', '2019', '2020', '2021', '2022']

сhildren_homes_2023 = сhildren_homes_2023.drop(index = 0).reset_index(drop=True)

In [95]:
сhildren_homes_2023.head()

,name,2010,2015,2019,2020,2021,2022
0,Число домов ребенка (на конец года),227,166,139,136,134,116
1,"В них детей, человек",17 483,10 245,7 059,6 166,5 968,5 324
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN
3,0 – 12 месяцев,4 493,2 373,1 764,1 480,1 444,1 282
4,1 – 3 года,9 676,5 456,3 747,3 244,3 069,2 770

Для унификации названий в колонке name, возьмем за основу названия 2005 года, сохраним их в отдельную переменную и запишем по остальным годам эти названия в колонку name

In [96]:
name_unified = сhildren_homes_2005['name']

In [97]:
сhildren_homes_2007['name'] = name_unified

In [98]:
сhildren_homes_2009['name'] = name_unified

In [99]:
сhildren_homes_2011['name'] = name_unified

In [100]:
сhildren_homes_2013['name'] = name_unified

In [101]:
сhildren_homes_2015['name'] = name_unified

In [102]:
сhildren_homes_2017['name'] = name_unified

In [103]:
сhildren_homes_2019['name'] = name_unified

In [104]:
сhildren_homes_2021['name'] = name_unified

In [105]:
сhildren_homes_2023['name'] = name_unified

### Соединяем данные из всех папок в один датафрейм

In [106]:
сhildren_homes_1 = сhildren_homes_2005.merge(сhildren_homes_2007, how='left')

сhildren_homes_1

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0
5,3 года и старше,5994.0,5774.0,3662.0,4138.0,4233.0,4100.0,3943.0,3673.0,3563.0
6,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,14384.0,14660.0,14520.0,15215.0,16317.0,13873.0
7,Поступило детей в течение года,10987.0,11533.0,13291.0,13168.0,13959.0,14626.0,16550.0,15068.0,14440.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,поступившие от родителей,5777.0,4475.0,3471.0,3359.0,3368.0,3476.0,3654.0,3037.0,2995.0
11,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,9806.0,10591.0,11150.0,12824.0,12031.0,11445.0
12,Выбыло детей в течение года,10741.0,10349.0,12895.0,12636.0,13497.0,14231.0,15187.0,13949.0,14412.0
13,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0
16,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0
17,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0
19,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0

In [107]:
сhildren_homes_2 = сhildren_homes_1.merge(сhildren_homes_2009, how='left')

сhildren_homes_2

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,2007,2008
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,249.0,244.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,18480.0,17781.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,4768.0,5052.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,9856.0,8988.0
5,3 года и старше,5994.0,5774.0,3662.0,4138.0,4233.0,4100.0,3943.0,3673.0,3563.0,3856.0,3741.0
6,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,14384.0,14660.0,14520.0,15215.0,16317.0,13873.0,14792.0,13588.0
7,Поступило детей в течение года,10987.0,11533.0,13291.0,13168.0,13959.0,14626.0,16550.0,15068.0,14440.0,14039.0,14823.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,поступившие от родителей,5777.0,4475.0,3471.0,3359.0,3368.0,3476.0,3654.0,3037.0,2995.0,3188.0,4236.0
13,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,9806.0,10591.0,11150.0,12824.0,12031.0,11445.0,10851.0,10587.0
14,Выбыло детей в течение года,10741.0,10349.0,12895.0,12636.0,13497.0,14231.0,15187.0,13949.0,14412.0,15543.0,15186.0
15,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,2672.0,3202.0
20,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,7979.0,7318.0
21,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,9303.0,8637.0
23,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,13912.0,13377.0

In [108]:
сhildren_homes_3 = сhildren_homes_2.merge(сhildren_homes_2011, how='left')

сhildren_homes_3

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,249.0,244.0,243.0,227.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,18480.0,17781.0,17767.0,17483.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,4768.0,5052.0,4942.0,4493.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,9856.0,8988.0,9322.0,9676.0
5,3 года и старше,5994.0,5774.0,3662.0,4138.0,4233.0,4100.0,3943.0,3673.0,3563.0,3856.0,3741.0,3503.0,3314.0
6,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,14384.0,14660.0,14520.0,15215.0,16317.0,13873.0,14792.0,13588.0,13062.0,12707.0
7,Поступило детей в течение года,10987.0,11533.0,13291.0,13168.0,13959.0,14626.0,16550.0,15068.0,14440.0,14039.0,14823.0,15166.0,15010.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,поступившие от родителей,5777.0,4475.0,3471.0,3359.0,3368.0,3476.0,3654.0,3037.0,2995.0,3188.0,4236.0,4485.0,4907.0
17,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,9806.0,10591.0,11150.0,12824.0,12031.0,11445.0,10851.0,10587.0,10681.0,10071.0
18,Выбыло детей в течение года,10741.0,10349.0,12895.0,12636.0,13497.0,14231.0,15187.0,13949.0,14412.0,15543.0,15186.0,14814.0,14988.0
19,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,2672.0,3202.0,3506.0,4332.0
28,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,7979.0,7318.0,6912.0,6452.0
29,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,9303.0,8637.0,7867.0,7681.0
31,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,13912.0,13377.0,12596.0,12231.0

In [109]:
сhildren_homes_4 = сhildren_homes_3.merge(сhildren_homes_2013, how='left')

сhildren_homes_4

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,249.0,244.0,243.0,227.0,218.0,207.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,18480.0,17781.0,17767.0,17483.0,16296.0,15993.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,4768.0,5052.0,4942.0,4493.0,3998.0,3977.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,9856.0,8988.0,9322.0,9676.0,8884.0,8427.0
5,3 года и старше,5994.0,5774.0,3662.0,4138.0,4233.0,4100.0,3943.0,3673.0,3563.0,3856.0,3741.0,3503.0,3314.0,3414.0,3589.0
6,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,14384.0,14660.0,14520.0,15215.0,16317.0,13873.0,14792.0,13588.0,13062.0,12707.0,11803.0,11145.0
7,Поступило детей в течение года,10987.0,11533.0,13291.0,13168.0,13959.0,14626.0,16550.0,15068.0,14440.0,14039.0,14823.0,15166.0,15010.0,13941.0,13762.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,поступившие от родителей,5777.0,4475.0,3471.0,3359.0,3368.0,3476.0,3654.0,3037.0,2995.0,3188.0,4236.0,4485.0,4907.0,4580.0,4863.0
25,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,9806.0,10591.0,11150.0,12824.0,12031.0,11445.0,10851.0,10587.0,10681.0,10071.0,9361.0,8899.0
26,Выбыло детей в течение года,10741.0,10349.0,12895.0,12636.0,13497.0,14231.0,15187.0,13949.0,14412.0,15543.0,15186.0,14814.0,14988.0,14842.0,13767.0
27,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,2672.0,3202.0,3506.0,4332.0,4274.0,4047.0
44,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,7979.0,7318.0,6912.0,6452.0,6514.0,5639.0
45,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,9303.0,8637.0,7867.0,7681.0,7339.0,6512.0
47,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,13912.0,13377.0,12596.0,12231.0,11339.0,10829.0

In [110]:
сhildren_homes_5 = сhildren_homes_4.merge(сhildren_homes_2015, how='left')

сhildren_homes_5

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,249.0,244.0,243.0,227.0,218.0,207.0,194.0,176.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,18480.0,17781.0,17767.0,17483.0,16296.0,15993.0,13977.0,11530.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,4768.0,5052.0,4942.0,4493.0,3998.0,3977.0,3358.0,2821.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,9856.0,8988.0,9322.0,9676.0,8884.0,8427.0,7219.0,6024.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,2672.0,3202.0,3506.0,4332.0,4274.0,4047.0,4542.0,4494.0
76,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,7979.0,7318.0,6912.0,6452.0,6514.0,5639.0,5796.0,4853.0
77,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,9303.0,8637.0,7867.0,7681.0,7339.0,6512.0,5788.0,4884.0
79,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,13912.0,13377.0,12596.0,12231.0,11339.0,10829.0,9453.0,7737.0

In [111]:
сhildren_homes_6 = сhildren_homes_5.merge(сhildren_homes_2017, how='left')

сhildren_homes_6

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,249.0,244.0,243.0,227.0,218.0,207.0,194.0,176.0,166.0,161.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,18480.0,17781.0,17767.0,17483.0,16296.0,15993.0,13977.0,11530.0,10245.0,8575.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,4768.0,5052.0,4942.0,4493.0,3998.0,3977.0,3358.0,2821.0,2373.0,2133.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,9856.0,8988.0,9322.0,9676.0,8884.0,8427.0,7219.0,6024.0,5456.0,4549.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,2672.0,3202.0,3506.0,4332.0,4274.0,4047.0,4542.0,4494.0,5389.0,5963.0
140,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,7979.0,7318.0,6912.0,6452.0,6514.0,5639.0,5796.0,4853.0,4110.0,3451.0
141,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,9303.0,8637.0,7867.0,7681.0,7339.0,6512.0,5788.0,4884.0,3945.0,3407.0
143,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,13912.0,13377.0,12596.0,12231.0,11339.0,10829.0,9453.0,7737.0,6726.0,5727.0

In [112]:
сhildren_homes_7 = сhildren_homes_6.merge(сhildren_homes_2019, how='left')

сhildren_homes_7

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,...,243.0,227.0,218.0,207.0,194.0,176.0,166.0,161.0,154.0,145.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,...,17767.0,17483.0,16296.0,15993.0,13977.0,11530.0,10245.0,8575.0,7774.0,7524.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,...,4942.0,4493.0,3998.0,3977.0,3358.0,2821.0,2373.0,2133.0,1989.0,1968.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,...,9322.0,9676.0,8884.0,8427.0,7219.0,6024.0,5456.0,4549.0,4077.0,3920.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,...,3506.0,4332.0,4274.0,4047.0,4542.0,4494.0,5389.0,5963.0,6041.0,6257.0
268,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,...,6912.0,6452.0,6514.0,5639.0,5796.0,4853.0,4110.0,3451.0,2784.0,2739.0
269,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,...,7867.0,7681.0,7339.0,6512.0,5788.0,4884.0,3945.0,3407.0,2883.0,2775.0
271,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,...,12596.0,12231.0,11339.0,10829.0,9453.0,7737.0,6726.0,5727.0,4961.0,4647.0

In [113]:
сhildren_homes_7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 272 entries, 0 to 271
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    272 non-null    object
 1   1990    14 non-null     float64
 2   1995    14 non-null     float64
 3   2000    14 non-null     float64
 4   2001    14 non-null     float64
 5   2002    14 non-null     float64
 6   2003    14 non-null     float64
 7   2004    14 non-null     float64
 8   2005    14 non-null     float64
 9   2006    14 non-null     float64
 10  2007    14 non-null     float64
 11  2008    14 non-null     float64
 12  2009    14 non-null     float64
 13  2010    14 non-null     float64
 14  2011    14 non-null     float64
 15  2012    14 non-null     float64
 16  2013    14 non-null     float64
 17  2014    14 non-null     float64
 18  2015    14 non-null     float64
 19  2016    14 non-null     float64
 20  2017    14 non-null     float64
 21  2018    14 non-null     float64
dtypes: float64(21), object(1)
memory usage: 46.9+ KB

Заменим неразрывный пробел в датафрейме `сhildren_homes_2021` для дальнейшего преобразования этих колонок к типу float с целью соединеия в общий датафрейм.

In [114]:
сhildren_homes_2021.iloc[:,1:] = сhildren_homes_2021.iloc[:,1:].apply(lambda x: x.str.replace('\xa0', ''))

Теперь произведём в цикле изменения всех записей в колонках по годам с типа object на тип float64

In [115]:
for names, values in сhildren_homes_2021.iloc[:,1:].items():
    сhildren_homes_2021[names] = values.astype('float')

In [116]:
сhildren_homes_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    18 non-null     object
 1   2005    14 non-null     float64
 2   2010    14 non-null     float64
 3   2015    14 non-null     float64
 4   2018    14 non-null     float64
 5   2019    14 non-null     float64
 6   2020    14 non-null     float64
dtypes: float64(6), object(1)
memory usage: 1.1+ KB

In [117]:
сhildren_homes_8 = сhildren_homes_7.merge(сhildren_homes_2021, how='left')

сhildren_homes_8

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,...,218.0,207.0,194.0,176.0,166.0,161.0,154.0,145.0,139.0,136.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,...,16296.0,15993.0,13977.0,11530.0,10245.0,8575.0,7774.0,7524.0,7059.0,6166.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,...,3998.0,3977.0,3358.0,2821.0,2373.0,2133.0,1989.0,1968.0,1764.0,1480.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,...,8884.0,8427.0,7219.0,6024.0,5456.0,4549.0,4077.0,3920.0,3747.0,3244.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,...,4274.0,4047.0,4542.0,4494.0,5389.0,5963.0,6041.0,6257.0,6563.0,5390.0
524,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,...,6514.0,5639.0,5796.0,4853.0,4110.0,3451.0,2784.0,2739.0,2702.0,1939.0
525,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,...,7339.0,6512.0,5788.0,4884.0,3945.0,3407.0,2883.0,2775.0,2326.0,2240.0
527,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,...,11339.0,10829.0,9453.0,7737.0,6726.0,5727.0,4961.0,4647.0,4124.0,3422.0

Изменим тип данных датафрейма `сhildren_homes_2023` в колонках по годам с object на тип float64 в цикле. Но перед этим удалим неразрывный пробел.

In [118]:
сhildren_homes_2023.iloc[:, 1:] = сhildren_homes_2023.iloc[:, 1:].apply(lambda x: x.str.replace('\xa0', ''))

In [119]:
for names, values in сhildren_homes_2023.iloc[:,1:].items():
    сhildren_homes_2023[names] = values.astype('float')

In [120]:
сhildren_homes_total = сhildren_homes_8.merge(сhildren_homes_2023, how='left')

сhildren_homes_total

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,...,194.0,176.0,166.0,161.0,154.0,145.0,139.0,136.0,134.0,116.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,...,13977.0,11530.0,10245.0,8575.0,7774.0,7524.0,7059.0,6166.0,5968.0,5324.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,...,3358.0,2821.0,2373.0,2133.0,1989.0,1968.0,1764.0,1480.0,1444.0,1282.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,...,7219.0,6024.0,5456.0,4549.0,4077.0,3920.0,3747.0,3244.0,3069.0,2770.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1035,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,...,4542.0,4494.0,5389.0,5963.0,6041.0,6257.0,6563.0,5390.0,5488.0,5531.0
1036,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,...,5796.0,4853.0,4110.0,3451.0,2784.0,2739.0,2702.0,1939.0,2276.0,382.0
1037,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1038,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,...,5788.0,4884.0,3945.0,3407.0,2883.0,2775.0,2326.0,2240.0,2053.0,1875.0
1039,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,...,9453.0,7737.0,6726.0,5727.0,4961.0,4647.0,4124.0,3422.0,3408.0,3082.0

Удалим образовавшиеся дубликаты

In [121]:
сhildren_homes_total = сhildren_homes_total.drop_duplicates().reset_index(drop=True)

сhildren_homes_total

,name,1990,1995,2000,2001,2002,2003,2004,2005,2006,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Число домов ребенка (на конец года),265.0,252.0,254.0,246.0,249.0,251.0,255.0,254.0,249.0,...,194.0,176.0,166.0,161.0,154.0,145.0,139.0,136.0,134.0,116.0
1,"В них детей, человек",18506.0,18346.0,19345.0,19356.0,19337.0,19113.0,19962.0,20621.0,20342.0,...,13977.0,11530.0,10245.0,8575.0,7774.0,7524.0,7059.0,6166.0,5968.0,5324.0
2,в том числе в возрасте:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0-12 месяцев,3229.0,3822.0,5178.0,5219.0,5289.0,5425.0,6370.0,6212.0,5598.0,...,3358.0,2821.0,2373.0,2133.0,1989.0,1968.0,1764.0,1480.0,1444.0,1282.0
4,1-3 года,9283.0,8750.0,10505.0,9999.0,9815.0,9588.0,9649.0,10736.0,11181.0,...,7219.0,6024.0,5456.0,4549.0,4077.0,3920.0,3747.0,3244.0,3069.0,2770.0
5,3 года и старше,5994.0,5774.0,3662.0,4138.0,4233.0,4100.0,3943.0,3673.0,3563.0,...,3400.0,2685.0,2416.0,1893.0,1708.0,1636.0,1548.0,1442.0,1455.0,1272.0
6,Из общей численности детей - сироты и оставшие...,4269.0,10455.0,14115.0,14384.0,14660.0,14520.0,15215.0,16317.0,13873.0,...,9333.0,6892.0,5439.0,4170.0,3543.0,3504.0,3140.0,3067.0,2721.0,2310.0
7,Поступило детей в течение года,10987.0,11533.0,13291.0,13168.0,13959.0,14626.0,16550.0,15068.0,14440.0,...,13562.0,11655.0,11984.0,11375.0,11023.0,10994.0,11304.0,8602.0,9819.0,9721.0
8,в том числе:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,поступившие от родителей,5777.0,4475.0,3471.0,3359.0,3368.0,3476.0,3654.0,3037.0,2995.0,...,5173.0,5091.0,5800.0,5907.0,6045.0,6187.0,6767.0,4368.0,5366.0,NaN
10,сироты и оставшиеся без попечения родителей,5210.0,6773.0,9820.0,9806.0,10591.0,11150.0,12824.0,12031.0,11445.0,...,8389.0,6564.0,6142.0,5468.0,4978.0,4807.0,4537.0,4234.0,4453.0,4494.0
11,Выбыло детей в течение года,10741.0,10349.0,12895.0,12636.0,13497.0,14231.0,15187.0,13949.0,14412.0,...,15066.0,13068.0,13105.0,12899.0,11675.0,11204.0,11603.0,9372.0,9950.0,9841.0
12,взято родителями,3643.0,3061.0,2871.0,2591.0,2546.0,2581.0,2780.0,2665.0,2666.0,...,4542.0,4494.0,5389.0,5963.0,6041.0,6257.0,6563.0,5390.0,5488.0,5531.0
13,взято для усыновления,2060.0,3727.0,6689.0,6665.0,5293.0,8094.0,8808.0,7232.0,7770.0,...,5796.0,4853.0,4110.0,3451.0,2784.0,2739.0,2702.0,1939.0,2276.0,382.0
14,"Численность детей, отстающих:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,в физическом развитии,8941.0,10545.0,11174.0,10807.0,10638.0,10267.0,9955.0,9994.0,9737.0,...,5788.0,4884.0,3945.0,3407.0,2883.0,2775.0,2326.0,2240.0,2053.0,1875.0
16,в психическом развитии,12999.0,15271.0,15872.0,15874.0,15553.0,15156.0,15221.0,15207.0,14956.0,...,9453.0,7737.0,6726.0,5727.0,4961.0,4647.0,4124.0,3422.0,3408.0,3082.0

Перед сохранением датафрейма изменим все значения float на int. Для этого сначала все nan заменим на "0"

In [122]:
сhildren_homes_total = сhildren_homes_total.fillna(0)

In [123]:
for names, values in сhildren_homes_total.iloc[:, 1:].items():
    сhildren_homes_total[names] = values.astype('int')

Перед сохранением таблицы, сначала её транспонируем

In [124]:
сhildren_homes_total = сhildren_homes_total.set_index('name')

сhildren_homes_total = сhildren_homes_total.T

Также приведём все названия к нижнему регистру

In [125]:
сhildren_homes_total.columns = [x.lower() for x in сhildren_homes_total.columns]

In [126]:
сhildren_homes_total

,число домов ребенка (на конец года),"в них детей, человек",в том числе в возрасте:,0-12 месяцев,1-3 года,3 года и старше,из общей численности детей - сироты и оставшиеся без попечения родителей,поступило детей в течение года,в том числе:,поступившие от родителей,сироты и оставшиеся без попечения родителей,выбыло детей в течение года,взято родителями,взято для усыновления,"численность детей, отстающих:",в физическом развитии,в психическом развитии
1990,265,18506,0,3229,9283,5994,4269,10987,0,5777,5210,10741,3643,2060,0,8941,12999
1995,252,18346,0,3822,8750,5774,10455,11533,0,4475,6773,10349,3061,3727,0,10545,15271
2000,254,19345,0,5178,10505,3662,14115,13291,0,3471,9820,12895,2871,6689,0,11174,15872
2001,246,19356,0,5219,9999,4138,14384,13168,0,3359,9806,12636,2591,6665,0,10807,15874
2002,249,19337,0,5289,9815,4233,14660,13959,0,3368,10591,13497,2546,5293,0,10638,15553
2003,251,19113,0,5425,9588,4100,14520,14626,0,3476,11150,14231,2581,8094,0,10267,15156
2004,255,19962,0,6370,9649,3943,15215,16550,0,3654,12824,15187,2780,8808,0,9955,15221
2005,254,20621,0,6212,10736,3673,16317,15068,0,3037,12031,13949,2665,7232,0,9994,15207
2006,249,20342,0,5598,11181,3563,13873,14440,0,2995,11445,14412,2666,7770,0,9737,14956
2007,249,18480,0,4768,9856,3856,14792,14039,0,3188,10851,15543,2672,7979,0,9303,13912
2008,244,17781,0,5052,8988,3741,13588,14823,0,4236,10587,15186,3202,7318,0,8637,13377
2009,243,17767,0,4942,9322,3503,13062,15166,0,4485,10681,14814,3506,6912,0,7867,12596
2010,227,17483,0,4493,9676,3314,12707,15010,0,4907,10071,14988,4332,6452,0,7681,12231
2011,218,16296,0,3998,8884,3414,11803,13941,0,4580,9361,14842,4274,6514,0,7339,11339
2012,207,15993,0,3977,8427,3589,11145,13762,0,4863,8899,13767,4047,5639,0,6512,10829
2013,194,13977,0,3358,7219,3400,9333,13562,0,5173,8389,15066,4542,5796,0,5788,9453
2014,176,11530,0,2821,6024,2685,6892,11655,0,5091,6564,13068,4494,4853,0,4884,7737
2015,166,10245,0,2373,5456,2416,5439,11984,0,5800,6142,13105,5389,4110,0,3945,6726
2016,161,8575,0,2133,4549,1893,4170,11375,0,5907,5468,12899,5963,3451,0,3407,5727
2017,154,7774,0,1989,4077,1708,3543,11023,0,6045,4978,11675,6041,2784,0,2883,4961
2018,145,7524,0,1968,3920,1636,3504,10994,0,6187,4807,11204,6257,2739,0,2775,4647
2019,139,7059,0,1764,3747,1548,3140,11304,0,6767,4537,11603,6563,2702,0,2326,4124
2020,136,6166,0,1480,3244,1442,3067,8602,0,4368,4234,9372,5390,1939,0,2240,3422
2021,134,5968,0,1444,3069,1455,2721,9819,0,5366,4453,9950,5488,2276,0,2053,3408
2022,116,5324,0,1282,2770,1272,2310,9721,0,0,4494,9841,5531,382,0,1875,3082

Сохраняем датасет в файл

In [127]:
сhildren_homes_total.to_csv('сhildren_homes_1990_2022.csv')

### Ссылка на дашборд

Дашборд выполнен в программе Tableau и доступен по [ссылке](https://public.tableau.com/views/hildren_homes_1990_2022/Dashboard1?:language=en-US&:sid=&:display_count=n&:origin=viz_share_link)

### Выводы по разделу

В период с 1990 по 2022 гг количество детей в домах ребенка снизилось в 3,5 раза

## Коечный фонд по специализации в Субъектах Российской Федерации. Ресурсы и деятельность организаций здравоохранения.

### Предположение

За период 2004 - 2012 в структуре коечного фонда количество онкологических и инфекционных коек выросло, а количество коек для беременных, рожениц и родильниц снизилось на 30%. Но при этом количество амбулаторных медицинских организаций (поликлиник) выросло более чем на 30%.

### Загрузка данных

In [128]:
bed_fund_2005 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2005/Ресурсы и деятельность учреждений здравоохранения/число больничных коек по специализации по регионам российской федерации в 2004 г..csv')

bed_fund_2005

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,Терапев- тические,Хирур- гические,Онколо- гические,Гинеко- логические,Туберку- лезные,Инфекци- онные,Офтальмо- логические,Отола- ринголо- гические,Дермато- венерологи- ческие,Психиат- рические,Нарколо- гические,Неврологи- ческие,Койки для беремен- ных жен- щин и рожениц,Койки для больных детей,Общие койки
1,Российская Федерация,340402,284959,38092,82306,84578,87995,26568,25171,22421,168771,29803,85967,83699,210373,21142
2,Центральный федеральный округ,94464,79474,11166,21166,18325,21506,7634,6934,4738,58447,9803,23906,20456,49082,2342
3,Белгородская область,3632,3060,365,828,705,960,287,293,160,1477,250,947,960,2298,-
4,Брянская область,3252,2861,335,871,820,907,227,330,191,1334,275,1082,923,2043,605
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,в том числе Корякский автономный округ,214,88,-,45,135,63,-,-,-,-,-,-,35,244,-
96,Магаданская область,557,466,75,171,197,226,NaN,35,53,209,148,115,145,442,5
97,Сахалинская область,1416,1228,250,440,370,421,107,65,197,777,229,331,392,908,-
98,Еврейская автономная область,281,336,44,86,600,170,20,39,100,335,36,71,126,375,-
99,Чукотский автономный округ,190,175,7,60,110,110,18,20,25,65,20,30,55,230,152

In [129]:
bed_fund_2007 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2007/Ресурсы и деятельность учреждений здравоохранения/число больничных коек по специализации по субъектам российской федерации в 2006 г..csv')

bed_fund_2007

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,Терапев- тические,Хирур- гические,Онколо- гические,Гинеко- логичес- кие,Туберку- лезные,Инфек- ционные,Офталь- мологи- ческие,Отоларин- гологи- ческие,Дермато- венеро- логичес- кие,Психиат- рические,Нарколо- гические,Невроло- гические,Койки для беремен- ных жен- щин и рожениц,Койки для больных детей,Общие койки
1,Российская Федерация,324507,277026,38813,79123,84067,81370,26029,23665,20426,165268,28752,86557,82216,194592,19610
2,Центральный федеральный округ,88038,76979,11231,20490,18010,19535,7686,6793,4225,57334,9213,24080,19932,44456,2927
3,Белгородская область,3268,2809,360,761,645,868,286,272,150,1382,180,1007,952,1838,30
4,Брянская область,3236,2808,335,890,820,843,245,321,161,1364,281,1075,889,1985,492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,в том числе Корякский автономный округ,159,79,-,38,86,49,-,-,-,-,-,-,30,138,-
95,Магаданская область,455,438,77,142,245,213,30,35,38,203,139,108,134,393,-
96,Сахалинская область,1481,1279,250,448,350,429,127,63,149,761,254,405,358,846,-
97,Еврейская автономная область,264,336,44,85,600,173,20,38,100,335,36,79,137,374,16
98,Чукотский автономный округ,198,169,10,71,106,85,11,17,25,46,35,21,51,191,157

In [130]:
bed_fund_2009 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2009/Ресурсы и деятельность учреждений здравоохранения/число больничных коек по специализации по субъектам российской федерации в 2008 г. начало.csv')

bed_fund_2009

,0,1,2,3,4,5,6
0,NaN,Терапев- тического профиля,Хирурги- ческого профиля,Онкологи- ческие,Гинеколо- гические,Туберку- лезные,Инфекци-онные
1,Российская Федерация,251264,264559,39018,72725,83811,73792
2,Центральный федеральный округ,69055,73783,11051,18724,18312,17991
3,Белгородская область,2486,2497,365,642,605,708
4,Брянская область,2411,2707,325,746,820,670
...,...,...,...,...,...,...,...
88,Амурская область,1827,1748,208,658,686,523
89,Магаданская область,424,393,77,122,270,197
90,Сахалинская область,1150,1311,250,456,350,409
91,Еврейская автономная область,230,336,59,85,600,112
92,Чукотский автономный округ,160,167,10,69,101,80

In [131]:
bed_fund_2011 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2011/Ресурсы и деятельность учреждений здравоохранения/число больничных коек по специализации по субъектам российской федерации в 2010 г. начало.csv')

bed_fund_2011

,0,1,2,3,4,5,6
0,NaN,Терапевтиче- ского профиля,Хирургиче- ского профиля,Онкологи- ческие,Гинеколо- гические,Туберкулез- ные,Инфекци- онные
1,Российская Федерация,296103,257185,39718,68779,83957,70530
2,Центральный федеральный округ,80054,71244,11277,17369,17815,16752
3,Белгородская область,2983,2493,400,601,575,690
4,Брянская область,2725,2542,325,652,585,534
...,...,...,...,...,...,...,...
89,Амурская область,2049,1684,209,630,686,528
90,Магаданская область,420,371,85,111,266,182
91,Сахалинская область,1401,1194,250,485,350,388
92,Еврейская автономная область,273,329,51,86,700,121
93,Чукотский автономный округ,116,116,11,53,65,53

In [132]:
bed_fund_2013 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2013/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.15. число больничных коек по специализации по субъектам российской федерации в 2012 г..csv')

bed_fund_2013

,Unnamed: 0,Терапевтического\nпрофиля,Хирургического\nпрофиля,Онкологические,Гинеколо-\nгические \n\n\n,Туберкулезные,Инфекци-онные,Офтальмологические,Отоларингологические,Дермато-венерологи-\nческие\n\n,Психиатрические,Наркологические,Неврологи-\nческие,Койки для \nберемен-\nных жен-\nщин и \nрожениц,Из всего \nчисла \nкоек – \nкойки для \nдетей
0,Российская Федерация,302797,256388,42755,64646,93188,70246,23730,20169,15967,149438,25496,86036,77425,177890
1,Центральный \nфедеральный округ,82632,70263,12626,16420,18315,16367,\n6596,5430,3421,47573,7731,24366,18311,40253
2,Белгородская область,3133,2471,405,585,600,772,222,219,104,1010,130,1021,872,1680
3,Брянская область,2787,2466,325,616,739,507,177,242,150,1037,230,1020,762,1575
4,Владимирская область,2823,2352,367,502,826,613,218,173,141,1612,222,1055,687,1260
5,Воронежская область,5381,4516,485,1131,1660,1262,512,367,245,1655,285,1880,1242,2772
6,Ивановская область,2775,1822,404,601,785,388,165,117,105,1116,362,899,654,1475
7,Калужская область,2245,1597,720,507,671,369,196,115,93,835,233,603,407,1057
8,Костромская область,1277,1053,153,254,280,266,102,136,69,1525,138,402,348,754
9,Курская область,2300,1982,390,448,640,433,145,135,80,1590,170,746,554,935
10,Липецкая область,2204,2025,333,434,556,591,125,133,50,1125,270,983,484,1273
11,Московская область,13440,11459,1679,2905,2163,2829,1231,1016,642,7671,1203,3935,2757,5954
12,Орловская область,1617,1275,226,320,320,309,120,116,100,1866,192,630,463,857
13,Рязанская область,2909,2020,415,523,525,592,213,205,151,1572,218,649,557,1240
14,Смоленская область,2358,2007,280,466,474,472,145,108,74,2406,176,631,505,1037
15,Тамбовская область,2473,1945,254,479,552,390,201,137,104,892,226,617,511,1012
16,Тверская область,2848,2533,460,640,965,706,205,180,108,1903,264,953,866,1621
17,Тульская область,3164,2307,455,672,873,763,212,226,175,1880,300,880,715,1784
18,Ярославская область,3308,2707,430,582,665,562,291,210,90,2081,290,1156,495,1341
19,г. Москва,25590,23726,4845,4755,5021,4543,2116,1595,940,15797,2822,6306,5432,12626
20,Северо-Западный \nфедеральный округ,27574,27243,5150,5051,7477,6673,\n2115,2204,1407,17460,2081,8468,6745,15218
21,Республика Карелия,1598,1295,185,263,280,454,80,54,33,764,114,645,322,853
22,Республика Коми,1845,2026,283,384,901,465,133,113,71,841,175,714,647,1410
23,Архангельская область,2895,2497,478,601,917,777,288,223,131,1221,236,805,730,1445
24,в том числе Ненецкий \nавтономный округ,40,60,-,35,110,30,\n-,-,-,15,15,15,40,135
25,Вологодская область,2029,2131,412,478,670,543,193,163,109,1350,190,727,632,1353
26,Калинингpадская область,1808,2111,130,453,403,441,130,150,234,1366,125,449,482,794
27,Ленинградская область,2631,2461,339,537,730,460,282,231,130,1411,357,687,671,1354
28,Мурманская область,1962,1800,342,402,425,651,89,162,120,746,183,739,511,951
29,Новгородская область,1441,1224,226,330,555,254,61,78,41,835,79,413,263,748
30,Псковская область,1486,1047,234,336,503,282,89,75,90,860,147,543,263,1005
31,г. Санкт-Петербург,9879,10651,2521,1267,2093,2346,770,955,448,8066,475,2746,2224,5305
32,Южный федеральный округ,25973,23057,3940,6882,10174,8015,2021,1942,1736,14803,2103,7650,7336,16685
33,Республика Адыгея,936,815,135,143,195,258,50,20,65,274,67,366,255,599
34,Республика Калмыкия,546,426,70,139,280,164,34,53,40,224,20,173,205,462
35,Краснодарский край,8930,7825,1117,2327,3260,3278,783,588,679,6210,962,2697,2597,5993
36,Астраханская область,2174,1783,260,457,842,1073,124,157,179,1140,207,772,503,1490
37,Волгоградская область,5950,4848,781,1311,2740,1308,435,386,198,3102,393,1119,1469,3770
38,Ростовская область,7437,7360,1577,2505,2857,1934,595,738,575,3853,454,2523,2307,4371
39,Северо-Кавказский\nфедеральный округ,19252,13122,1592,4232,4570,4856,\n1243,1181,1175,4729,576,5055,6280,11593
40,Республика Дагестан,5890,3501,200,976,1420,1365,385,212,425,1005,115,1173,2151,3586
41,Республика Ингушетия,520,375,20,150,190,110,25,20,36,-,-,120,230,328
42,Кабардино-Балкарская \nРеспублика,2368,1311,172,436,645,655,\n161,167,120,645,160,550,565,1430
43,Карачаево-Черкесская \nРеспублика,1118,739,75,213,160,220,\n60,100,55,215,20,308,271,539
44,Республика Северная \nОсетия - Алания,2074,1403,242,336,510,515,\n128,128,150,475,120,430,462,1316
45,Чеченская Республика,2475,1675,180,895,350,550,105,140,120,440,25,710,1190,1644
46,Ставропольский край,4807,4118,703,1226,1295,1441,379,414,269,1949,136,1764,1411,2750

In [133]:
bed_fund_2015 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2015/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.2. число больничных коек по специализации.csv')

bed_fund_2015

,Unnamed: 0,2005,2010,2011,2012,2013,2014
0,NaN,"Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек"
1,Всего больничных коек,"1575,4","1339,5","1347,1","1332,3","1301,9","1266,8"
2,из них:,NaN,NaN,NaN,NaN,NaN,NaN
3,терапевтического профиля,"329,7","296,1","299,2","302,8","294,3","280,3"
4,хирургического профиля,"279,7","257,2","259,5","256, 4","251,3","241,8"
5,онкологических,"38,3","39,7","40,4","42,8","43,4","44,3"
6,гинекологических,"81,7","68,8","66,9","64,6","61,1","57,5"
7,туберкулезных,"84,3","84,0","91,0","93,2","90,9","86,5"
8,инфекционных,"84,6","70,5","71,1","70,2","68,2","65,3"
9,офтальмологических,"26,3","25,8","25,4","23,7","23,1","22,1"
10,отоларингологических,"24,5","20,3","20,9","20,2","19,6","18,7"
11,дермато-венерологических,"21,6","16,4","16,5","16,0","15,2","13,9"
12,психиатрических,"167,0","153,4","153,2","149,4","147,6","142,9"
13,наркологических,"29,3","26,3","26,3","25,5","25,3","23,5"
14,неврологических,"86,3","83,5","84,7","86,0","84,4","81,6"
15,для беременных женщин \nи рожениц,"81,9","80,3","79,2","77,4","74,9","72,4"
16,Из всего числа коек – койки для \nдетей,"200,3","179,0","178,4","177,9","173,9","166,5"
17,NaN,На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1)
18,Всего больничных коек,"110,9","93,8","94,2","92,9","90,6","86,6"
19,из них:,NaN,NaN,NaN,NaN,NaN,NaN
20,терапевтического профиля,"23,2","20,7","20,9","21,1","20,5","19,2"
21,хирургического профиля,"19,7","18,0","18,1","17,9","17,5","16,5"
22,онкологических,"2,7","2,8","2,8","3,0","3,0","3,0"
23,гинекологических,"10,7","9,0","8,7","8,4","7,9","7,3"
24,туберкулезных,"5,9","5,9","6,4","6,5","6,3","5,9"
25,инфекционных,"6,0","4,9","5,0","4,9","4,7","4,5"
26,офтальмологических,"1,8","1,8","1,8","1,7","1,6","1,5"
27,отоларингологических,"1,7","1,4","1,5","1,4","1,4","1,3"
28,дермато-венерологических,"1,5","1,1","1,2","1,1","1,1","1,0"
29,психиатрических,"11,8","10,7","10,7","10,4","10,3","9,8"
30,наркологических,"2,1","1,8","1,8","1,8","1,8","1,6"
31,неврологических,"6,1","5,8","5,9","6,0","5,9","5,6"
32,для беременных женщин и рожениц,"21,0","21,6","21,7","21,5","21,0","20,3"
33,Из всего числа коек – койки для \nдетей,"94,7","82,2","80,4","66,1","63,5","58,7"

In [134]:
bed_fund_2017 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2017/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.2. число больничных коек по специализации.csv')

bed_fund_2017

,Unnamed: 0,2005,2010,2013,2014,2015,2016
0,NaN,"Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек"
1,Всего больничных коек,"1575,4","1339,5","1301,9","1266,8","1222,0","1197,2"
2,из них:,NaN,NaN,NaN,NaN,NaN,NaN
3,терапевтического профиля,"329,7","296,1","294,3","280,3","266,2","258,9"
4,хирургического профиля,"279,7","257,2","251,3","241,8","231,7","227,0"
5,онкологических,"38,3","39,7","43,4","44,3","44,4","44,5"
6,гинекологических,"81,7","68,8","61,1","57,5","53,2","51,0"
7,туберкулезных,"84,3","84,0","90,9","86,5","82,1","79,9"
8,инфекционных,"84,6","70,5","68,2","65,3","62,7","61,0"
9,офтальмологических,"26,3","25,8","23,1","22,1","20,6","20,3"
10,отоларингологических,"24,5","20,3","19,6","18,7","18,0","17,5"
11,дермато-венерологических,"21,6","16,4","15,2","13,9","13,0","12,3"
12,психиатрических,"167,0","153,4","147,6","142,9","141,7","138,1"
13,наркологических,"29,3","26,3","25,3","23,5","23,2","22,2"
14,неврологических,"86,3","83,5","84,4","81,6","77,7","76,0"
15,для беременных женщин \nи рожениц,"81,9","80,3","74,9","72,4","69,4","67,0"
16,Из всего числа коек – койки \nдля детей,"200,3","179,0","173,9","166,5","163,5","158,5"
17,NaN,На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1)
18,Всего больничных коек,"110,9","93,8","90,6","86,6","83,4","81,6"
19,из них:,NaN,NaN,NaN,NaN,NaN,NaN
20,терапевтического профиля,"23,2","20,7","20,5","19,2","18,2","17,6"
21,хирургического профиля,"19,7","18,0","17,5","16,5","15,8","15,5"
22,онкологических,"2,7","2,8","3,0","3,0","3,0","3,0"
23,гинекологических,"10,7","9,0","7,9","7,3","6,8","6,5"
24,туберкулезных,"5,9","5,9","6,3","5,9","5,6","5,4"
25,инфекционных,"6,0","4,9","4,7","4,5","4,3","4,2"
26,офтальмологических,"1,8","1,8","1,6","1,5","1,4","1,4"
27,отоларингологических,"1,7","1,4","1,4","1,3","1,2","1,2"
28,дермато-венерологических,"1,5","1,1","1,1","1,0","0,9","0,8"
29,психиатрических,"11,8","10,7","10,3","9,8","9,7","9,4"
30,наркологических,"2,1","1,8","1,8","1,6","1,6","1,5"
31,неврологических,"6,1","5,8","5,9","5,6","5,3","5,2"
32,для беременных женщин и \nрожениц,"21,0","21,6","21,0","20,3","19,6","19,1"
33,Из всего числа коек – койки \nдля детей,"94,7","82,2","63,5","58,7","56,3","53,6"

In [135]:
bed_fund_2019 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2019/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.2. число больничных коек по специализации.csv')

bed_fund_2019

,Unnamed: 0,2005,2010,2015,2016,2017,2018
0,NaN,"Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек"
1,Всего больничных коек,"1575,4","1339,5","1222,0","1197,2","1182,7","1172,8"
2,из них:,NaN,NaN,NaN,NaN,NaN,NaN
3,терапевтического профиля,"329,7","296,1","266,2","258,9","257,8","255,5"
4,хирургического профиля,"279,7","257,2","231,7","227,0","224,8","223,6"
5,онкологических,"38,3","39,7","44,4","44,5","44,5","45,2"
6,гинекологических,"81,7","68,8","53,2","51,0","49,1","48,2"
7,туберкулезных,"84,3","84,0","82,1","79,9","77,2","75,4"
8,инфекционных,"84,6","70,5","62,7","61,0","59,9","59,3"
9,офтальмологических,"26,3","25,8","20,6","20,3","20,4","19,9"
10,оториноларингологических,"24,5","20,3","18,0","17,5","17,1","17,0"
11,дермато-венерологических,"21,6","16,4","13,0","12,3","11,8","11,7"
12,психиатрических,"167,0","153,4","141,7","138,1","136,0","134,5"
13,наркологических,"29,3","26,3","23,2","22,2","21,5","21,1"
14,неврологических,"86,3","83,5","77,7","76,0","75,6","75,0"
15,"для беременных, рожениц \nи родильниц","81,9","80,3","69,4","67,0","64,3","62,1"
16,Из всего числа коек – койки \nдля детей,"200,3","179,0","163,5","158,5","158,4","157,3"
17,NaN,На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1)
18,Всего больничных коек,"110,9","93,8","83,4","81,6","80,5","79,9"
19,из них:,NaN,NaN,NaN,NaN,NaN,NaN
20,терапевтического профиля,"23,2","20,7","18,2","17,6","17,6","17,4"
21,хирургического профиля,"19,7","18,0","15,8","15,5","15,3","15,2"
22,онкологических,"2,7","2,8","3,0","3,0","3,0","3,1"
23,гинекологических,"10,7","9,0","6,8","6,5","6,2","6,1"
24,туберкулезных,"5,9","5,9","5,6","5,4","5,3","5,1"
25,инфекционных,"6,0","4,9","4,3","4,2","4,1","4,0"
26,офтальмологических,"1,8","1,8","1,4","1,4","1,4","1,4"
27,оториноларингологических,"1,7","1,4","1,2","1,2","1,2","1,2"
28,дермато-венерологических,"1,5","1,1","0,9","0,8","0,8","0,8"
29,психиатрических,"11,8","10,7","9,7","9,4","9,3","9,2"
30,наркологических,"2,1","1,8","1,6","1,5","1,5","1,4"
31,неврологических,"6,1","5,8","5,3","5,2","5,1","5,1"
32,"для беременных, рожениц \nи родильниц","21,0","21,6","19,6","19,1","18,4","17,9"
33,Из всего числа коек – койки \nдля детей,"94,7","82,2","56,3","53,6","52,8","52,1"

In [136]:
bed_fund_2021 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2021/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.2. число больничных коек по специализации.csv')

bed_fund_2021

,Unnamed: 0,2005,2010,2015,2018,2019,2020
0,NaN,"Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек","Всего, тыс. коек"
1,Всего больничных коек,"1 575,4","1 339,5","1 222,0","1 172,8","1 173,6","1 188,8"
2,из них:,NaN,NaN,NaN,NaN,NaN,NaN
3,терапевтического профиля,"329,7","296,1","266,2","255,5","254,3","199,0"
4,хирургического профиля,"279,7","257,2","231,7","223,6","222,1","181,3"
5,онкологических,"38,3","39,7","44,4","45,2","45,7","46,3"
6,гинекологических,"81,7","68,8","53,2","48,2","46,8","35,9"
7,туберкулезных,"84,3","84,0","82,1","75,4","72,6","68,7"
8,инфекционных,"84,6","70,5","62,7","59,3","58,5","220,8"
9,офтальмологических,"26,3","25,8","20,6","19,9","19,8","16,6"
10,оториноларингологических,"24,5","20,3","18,0","17,0","16,8","13,5"
11,дермато-венерологических,"21,6","16,4","13,0","11,7","11,3","10,1"
12,психиатрических,"167,0","153,4","141,7","134,5","138,0","132,9"
13,наркологических,"29,3","26,3","23,2","21,1","21,0","19,9"
14,неврологических,"86,3","83,5","77,7","75,0","74,3","57,8"
15,"для беременных, рожениц \nи родильниц","81,9","80,3","69,4","62,1","58,9","50,8"
16,Из всего числа коек – койки \nдля детей,"200,3","179,0","163,5","157,3","155,5","139,4"
17,NaN,На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1),На 10 000 человек населения1)
18,Всего больничных коек,"110,9","93,8","83,4","79,9","80,0","81,3"
19,из них:,NaN,NaN,NaN,NaN,NaN,NaN
20,терапевтического профиля,"23,2","20,7","18,2","17,4","17,3","13,6"
21,хирургического профиля,"19,7","18,0","15,8","15,2","15,1","12,4"
22,онкологических,"2,7","2,8","3,0","3,1","3,1","3,2"
23,гинекологических,"10,7","9,0","6,8","6,1","6,0","4,6"
24,туберкулезных,"5,9","5,9","5,6","5,1","5,0","4,7"
25,инфекционных,"6,0","4,9","4,3","4,0","4,0","15,1"
26,офтальмологических,"1,8","1,8","1,4","1,4","1,4","1,1"
27,оториноларингологических,"1,7","1,4","1,2","1,2","1,1","0,9"
28,дермато-венерологических,"1,5","1,1","0,9","0,8","0,8","0,7"
29,психиатрических,"11,8","10,7","9,7","9,2","9,4","9,1"
30,наркологических,"2,1","1,8","1,6","1,4","1,4","1,4"
31,неврологических,"6,1","5,8","5,3","5,1","5,1","4,0"
32,"для беременных, рожениц \nи родильниц","21,0","21,6","19,6","17,9","17,1","14,9"
33,Из всего числа коек – койки \nдля детей,"94,7","82,2","56,3","52,1","51,2","45,9"

In [137]:
bed_fund_2023 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2023/3.2. ЧИСЛО БОЛЬНИЧНЫХ КОЕК ПО СПЕЦИАЛИЗАЦИИ - 3.2.csv')

bed_fund_2023

,3.2. ЧИСЛО БОЛЬНИЧНЫХ КОЕК ПО СПЕЦИАЛИЗАЦИИ,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,2010,2015,2019,2020,2021,2022
1,NaN,"Всего, тыс. коек",NaN,NaN,NaN,NaN,NaN
2,Всего больничных коек,"1 339,5","1 222,0","1 173,6","1 188,8","1 162,1","1 141,9"
3,из них:,NaN,NaN,NaN,NaN,NaN,NaN
4,терапевтического профиля,"296,1","266,2","254,3","199,0","213,9","248,5"
5,хирургического профиля,"257,2","231,7","222,1","181,3","192,5","217,6"
6,онкологических,"39,7","44,4","45,7","46,3","46,8","47,3"
7,гинекологических,"68,8","53,2","46,8","35,9","38,9","43,7"
8,туберкулезных,"84,0","82,1","72,6","68,7","63,9","61,6"
9,инфекционных,"70,5","62,7","58,5","220,8","166,1","72,9"
10,офтальмологических,"25,8","20,6","19,8","16,6","16,9","18,7"
11,оториноларингологических,"20,3","18,0","16,8","13,5","14,3","16,1"
12,дермато-венерологических,"16,4","13,0","11,3","10,1","9,9","10,3"
13,психиатрических,"153,4","141,7","138,0","132,9","132,3","128,4"
14,наркологических,"26,3","23,2","21,0","19,9","20,1","20,0"
15,неврологических,"83,5","77,7","74,3","57,8","61,6","70,9"
16,"для беременных, рожениц и родильниц","80,3","69,4","58,9","50,8","50,7","52,3"
17,Из всего числа коек – койки для детей,"179,0","163,5","155,5","139,4","142,5","149,6"
18,NaN,На 10 000 человек населения1),NaN,NaN,NaN,NaN,NaN
19,Всего больничных коек,"93,8","83,0","79,3","80,6","79,1","78,0"
20,из них:,NaN,NaN,NaN,NaN,NaN,NaN
21,терапевтического профиля,"20,7","18,1","17,2","13,5","14,6","17,0"
22,хирургического профиля,"18,0","15,7","15,0","12,3","13,1","14,9"
23,онкологических,"2,8","3,0","3,1","3,1","3,2","3,2"
24,гинекологических,"9,0","6,7","5,9","4,5","4,9","5,6"
25,туберкулезных,"5,9","5,6","4,9","4,7","4,4","4,2"
26,инфекционных,"4,9","4,3","4,0","15,0","11,3","5,0"
27,офтальмологических,"1,8","1,4","1,3","1,1","1,1","1,3"
28,оториноларингологических,"1,4","1,2","1,1","0,9","1,0","1,1"
29,дермато-венерологических,"1,1","0,9","0,8","0,7","0,7","0,7"
30,психиатрических,"10,7","9,6","9,3","9,0","9,0","8,8"
31,наркологических,"1,8","1,6","1,4","1,4","1,4","1,4"
32,неврологических,"5,8","5,3","5,0","3,9","4,2","4,8"
33,"для беременных, рожениц и родильниц","21,6","19,4","16,8","14,6","14,6","15,2"
34,Из всего числа коек – койки для детей,"82,2","56,0","51,0","45,9","47,0","49,6"
35,1) Число коек для гинекологических пациентов р...,NaN,NaN,NaN,NaN,NaN,NaN

### Предобработка данных

#### Данные из папки за 2005 год

Возьмем первую строку датафрейма и сделаем название колонок ею и потом сразу удалим её

In [138]:
bed_fund_2005.columns = list(bed_fund_2005.iloc[0])

In [139]:
bed_fund_2005 = bed_fund_2005.drop(index = 0)

Теперь удалим все тире в названиях колонок

In [140]:
bed_fund_2005.columns = bed_fund_2005.columns.fillna('субъект')

In [141]:
bed_fund_2005.columns = [x.replace('-', '') for x in bed_fund_2005.columns]

Также удалим все пробелы между словами, сохраним их в отдельную переменную и передадим ей новый список названий колонок и запишем эти новые названия колонок в датафрейм

In [142]:
column = list(bed_fund_2005.columns)

new_column = [i.replace(' ', '') for i in column]

bed_fund_2005.columns = new_column

Добавим самым первым столбцов год, из которого мы берём данные для дальнейшей визуализации в динамике

In [143]:
bed_fund_2005.insert(0, 'год', '2004')

In [144]:
bed_fund_2005.head()

,год,субъект,Терапевтические,Хирургические,Онкологические,Гинекологические,Туберкулезные,Инфекционные,Офтальмологические,Отоларингологические,Дерматовенерологические,Психиатрические,Наркологические,Неврологические,Койкидлябеременныхженщинирожениц,Койкидлябольныхдетей,Общиекойки
1,2004,Российская Федерация,340402,284959,38092,82306,84578,87995,26568,25171,22421,168771,29803,85967,83699,210373,21142
2,2004,Центральный федеральный округ,94464,79474,11166,21166,18325,21506,7634,6934,4738,58447,9803,23906,20456,49082,2342
3,2004,Белгородская область,3632,3060,365,828,705,960,287,293,160,1477,250,947,960,2298,-
4,2004,Брянская область,3252,2861,335,871,820,907,227,330,191,1334,275,1082,923,2043,605
5,2004,Владимирская область,3624,2792,365,829,711,906,325,268,268,1545,261,996,862,1783,-

#### Данные из папки 2007 года

In [145]:
bed_fund_2007.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,Терапев- тические,Хирур- гические,Онколо- гические,Гинеко- логичес- кие,Туберку- лезные,Инфек- ционные,Офталь- мологи- ческие,Отоларин- гологи- ческие,Дермато- венеро- логичес- кие,Психиат- рические,Нарколо- гические,Невроло- гические,Койки для беремен- ных жен- щин и рожениц,Койки для больных детей,Общие койки
1,Российская Федерация,324507,277026,38813,79123,84067,81370,26029,23665,20426,165268,28752,86557,82216,194592,19610
2,Центральный федеральный округ,88038,76979,11231,20490,18010,19535,7686,6793,4225,57334,9213,24080,19932,44456,2927
3,Белгородская область,3268,2809,360,761,645,868,286,272,150,1382,180,1007,952,1838,30
4,Брянская область,3236,2808,335,890,820,843,245,321,161,1364,281,1075,889,1985,492

Для датафрейма `bed_fund_2007` проведем аналогичные операции по данным из папки за 2005 год

In [146]:
bed_fund_2007.columns = list(bed_fund_2007.iloc[0])

In [147]:
bed_fund_2007 = bed_fund_2007.drop(index = 0)

In [148]:
bed_fund_2007.columns = bed_fund_2007.columns.fillna('субъект')

In [149]:
bed_fund_2007.columns = [x.replace('-', '') for x in bed_fund_2007.columns]

In [150]:
column = list(bed_fund_2007.columns)

new_column = [i.replace(' ', '') for i in column]

bed_fund_2007.columns = new_column

In [151]:
bed_fund_2007.insert(0, 'год', '2006')

bed_fund_2007.head()

,год,субъект,Терапевтические,Хирургические,Онкологические,Гинекологические,Туберкулезные,Инфекционные,Офтальмологические,Отоларингологические,Дерматовенерологические,Психиатрические,Наркологические,Неврологические,Койкидлябеременныхженщинирожениц,Койкидлябольныхдетей,Общиекойки
1,2006,Российская Федерация,324507,277026,38813,79123,84067,81370,26029,23665,20426,165268,28752,86557,82216,194592,19610
2,2006,Центральный федеральный округ,88038,76979,11231,20490,18010,19535,7686,6793,4225,57334,9213,24080,19932,44456,2927
3,2006,Белгородская область,3268,2809,360,761,645,868,286,272,150,1382,180,1007,952,1838,30
4,2006,Брянская область,3236,2808,335,890,820,843,245,321,161,1364,281,1075,889,1985,492
5,2006,Владимирская область,3138,2574,354,623,621,695,280,198,219,1525,266,972,753,1535,-

#### Данные из папки 2009 года

In [152]:
bed_fund_2009.head()

,0,1,2,3,4,5,6
0,NaN,Терапев- тического профиля,Хирурги- ческого профиля,Онкологи- ческие,Гинеколо- гические,Туберку- лезные,Инфекци-онные
1,Российская Федерация,251264,264559,39018,72725,83811,73792
2,Центральный федеральный округ,69055,73783,11051,18724,18312,17991
3,Белгородская область,2486,2497,365,642,605,708
4,Брянская область,2411,2707,325,746,820,670

In [153]:
bed_fund_2009.columns = list(bed_fund_2009.iloc[0])

bed_fund_2009 = bed_fund_2009.drop(index = 0)

bed_fund_2009.columns = bed_fund_2009.columns.fillna('субъект')

bed_fund_2009.columns = [x.replace('-', '') for x in bed_fund_2009.columns]

column = list(bed_fund_2009.columns)

new_column = [i.replace(' ', '') for i in column]

bed_fund_2009.columns = new_column

In [154]:
bed_fund_2009.insert(0, 'год', '2008')

bed_fund_2009.head()

,год,субъект,Терапевтическогопрофиля,Хирургическогопрофиля,Онкологические,Гинекологические,Туберкулезные,Инфекционные
1,2008,Российская Федерация,251264,264559,39018,72725,83811,73792
2,2008,Центральный федеральный округ,69055,73783,11051,18724,18312,17991
3,2008,Белгородская область,2486,2497,365,642,605,708
4,2008,Брянская область,2411,2707,325,746,820,670
5,2008,Владимирская область,2117,2378,361,515,508,659

#### Данные из папки за 2011 год

In [155]:
bed_fund_2011

,0,1,2,3,4,5,6
0,NaN,Терапевтиче- ского профиля,Хирургиче- ского профиля,Онкологи- ческие,Гинеколо- гические,Туберкулез- ные,Инфекци- онные
1,Российская Федерация,296103,257185,39718,68779,83957,70530
2,Центральный федеральный округ,80054,71244,11277,17369,17815,16752
3,Белгородская область,2983,2493,400,601,575,690
4,Брянская область,2725,2542,325,652,585,534
...,...,...,...,...,...,...,...
89,Амурская область,2049,1684,209,630,686,528
90,Магаданская область,420,371,85,111,266,182
91,Сахалинская область,1401,1194,250,485,350,388
92,Еврейская автономная область,273,329,51,86,700,121
93,Чукотский автономный округ,116,116,11,53,65,53

In [156]:
bed_fund_2011.columns = list(bed_fund_2011.iloc[0])

bed_fund_2011 = bed_fund_2011.drop(index = 0)

bed_fund_2011.columns = bed_fund_2011.columns.fillna('субъект')

bed_fund_2011.columns = [x.replace('-', '') for x in bed_fund_2011.columns]

column = list(bed_fund_2011.columns)

new_column = [i.replace(' ', '') for i in column]

bed_fund_2011.columns = new_column

In [157]:
bed_fund_2011.insert(0, 'год', '2010')

bed_fund_2011.head()

,год,субъект,Терапевтическогопрофиля,Хирургическогопрофиля,Онкологические,Гинекологические,Туберкулезные,Инфекционные
1,2010,Российская Федерация,296103,257185,39718,68779,83957,70530
2,2010,Центральный федеральный округ,80054,71244,11277,17369,17815,16752
3,2010,Белгородская область,2983,2493,400,601,575,690
4,2010,Брянская область,2725,2542,325,652,585,534
5,2010,Владимирская область,2560,2264,368,499,453,581

#### Данные из папки за 2013 год

In [158]:
bed_fund_2013.head()

,Unnamed: 0,Терапевтического\nпрофиля,Хирургического\nпрофиля,Онкологические,Гинеколо-\nгические \n\n\n,Туберкулезные,Инфекци-онные,Офтальмологические,Отоларингологические,Дермато-венерологи-\nческие\n\n,Психиатрические,Наркологические,Неврологи-\nческие,Койки для \nберемен-\nных жен-\nщин и \nрожениц,Из всего \nчисла \nкоек – \nкойки для \nдетей
0,Российская Федерация,302797,256388,42755,64646,93188,70246,23730,20169,15967,149438,25496,86036,77425,177890
1,Центральный \nфедеральный округ,82632,70263,12626,16420,18315,16367,\n6596,5430,3421,47573,7731,24366,18311,40253
2,Белгородская область,3133,2471,405,585,600,772,222,219,104,1010,130,1021,872,1680
3,Брянская область,2787,2466,325,616,739,507,177,242,150,1037,230,1020,762,1575
4,Владимирская область,2823,2352,367,502,826,613,218,173,141,1612,222,1055,687,1260

Для начала удалим символ "\n" в названиях колонок датафрейма

In [159]:
bed_fund_2013.columns = [x.replace('\n',' ') for x in bed_fund_2013.columns]

Теперь удалим все тире между названиями колонок

In [160]:
bed_fund_2013.columns = [x.replace('-', '') for x in bed_fund_2013.columns]

Теперь удалим все пробелы в названиях колонок

In [161]:
column = list(bed_fund_2013.columns)

new_column = [i.replace(' ', '') for i in column]

bed_fund_2013.columns = new_column

In [162]:
bed_fund_2013 = bed_fund_2013.rename(columns={'Unnamed:0':'субъект'})

bed_fund_2013.head()

,субъект,Терапевтическогопрофиля,Хирургическогопрофиля,Онкологические,Гинекологические,Туберкулезные,Инфекционные,Офтальмологические,Отоларингологические,Дерматовенерологические,Психиатрические,Наркологические,Неврологические,Койкидлябеременныхженщинирожениц,Извсегочислакоек–койкидлядетей
0,Российская Федерация,302797,256388,42755,64646,93188,70246,23730,20169,15967,149438,25496,86036,77425,177890
1,Центральный \nфедеральный округ,82632,70263,12626,16420,18315,16367,\n6596,5430,3421,47573,7731,24366,18311,40253
2,Белгородская область,3133,2471,405,585,600,772,222,219,104,1010,130,1021,872,1680
3,Брянская область,2787,2466,325,616,739,507,177,242,150,1037,230,1020,762,1575
4,Владимирская область,2823,2352,367,502,826,613,218,173,141,1612,222,1055,687,1260

Теперь удалим символ '\n' во всем датафрейме

In [163]:
bed_fund_2013 = bed_fund_2013.replace(r'\n', '', regex=True)

In [164]:
bed_fund_2013.insert(0, 'год', '2012')

bed_fund_2013.head()

,год,субъект,Терапевтическогопрофиля,Хирургическогопрофиля,Онкологические,Гинекологические,Туберкулезные,Инфекционные,Офтальмологические,Отоларингологические,Дерматовенерологические,Психиатрические,Наркологические,Неврологические,Койкидлябеременныхженщинирожениц,Извсегочислакоек–койкидлядетей
0,2012,Российская Федерация,302797,256388,42755,64646,93188,70246,23730,20169,15967,149438,25496,86036,77425,177890
1,2012,Центральный федеральный округ,82632,70263,12626,16420,18315,16367,6596,5430,3421,47573,7731,24366,18311,40253
2,2012,Белгородская область,3133,2471,405,585,600,772,222,219,104,1010,130,1021,872,1680
3,2012,Брянская область,2787,2466,325,616,739,507,177,242,150,1037,230,1020,762,1575
4,2012,Владимирская область,2823,2352,367,502,826,613,218,173,141,1612,222,1055,687,1260

### Сохранение данных

In [165]:
bed_fund_2005.to_csv('bed_fund_2005.csv')

In [166]:
bed_fund_2007.to_csv('bed_fund_2007.csv')

In [167]:
bed_fund_2009.to_csv('bed_fund_2009.csv')

In [168]:
bed_fund_2011.to_csv('bed_fund_2011.csv')

In [169]:
bed_fund_2013.to_csv('bed_fund_2013.csv')

### Дополнительное соединение и сохранение датасета

Соединение всеx таблиц "снизу"

In [170]:
s = pd.concat([bed_fund_2005, bed_fund_2007], axis=0)

In [171]:
s_1 = pd.concat([s, bed_fund_2009], axis=0)

In [172]:
s_2 = pd.concat([s_1, bed_fund_2011], axis=0)

In [173]:
s_3 = pd.concat([s_2, bed_fund_2013], axis=0)

Сохраним итоговую таблицы в датасет с названием test_3

In [174]:
s_3.to_csv('test_3.csv')

### Ссылка на дашборд

Дашборд выполнен в программе Tableau и доступен по [ссылке](https://public.tableau.com/views/bed_fund_corrected/sheet4?:language=en-US&:sid=&:display_count=n&:origin=viz_share_link)

### Выводы по разделу

За период 2004 - 2012:
- кол-во инфекционных коек:
    - по федеральным округам кол-во коек уменьшилось в 1,9 раза;
    - по областям кол-во коек уменьшилось в 2,9 раза;
    - по республикам кол-во коек уменьшилось в 3 раза;
    - по 2 городам федерального значения (Москва и СПб) кол-во коек уменьшилось в 1,06 раза;
    - по автономным округам кол-во коек уменьшилось в 1,2 раза.
- кол-во онкологических коек:
    - по федеральным округам кол-во коек уменьшилось в 1,3 раза;
    - по областям кол-во коек уменьшилось в 1,9 раза;
    - по республикам кол-во коек уменьшилось в 3,1 раза;
    - по 2 городам федерального значения (Москва и СПб) кол-во коек **увеличилось** в 1,2 раза;
    - по автономным округам кол-во коек **увеличилось** в 1.08 раза.
- кол-во коек для беременных, рожениц и родильниц:
    - по федеральным округам кол-во коек уменьшилось в 1.7 раза;
    - по областям кол-во коек уменьшилось в 2,5 раза;
    - по республикам кол-во коек уменьшилось в 2,4 раза;
    - по 2 городам федерального значения (Москва и СПб) кол-во коек уменьшилось в 1.022 раза;
    - по автономным округам данных недостаточно.
    
При этом количество амбулаторных медицинских организаций (поликлиник) уменьшилось на 6%.

## Техническое состояние и благоустройство зданий лечебно-профилактических учреждений здравоохранения. Ресурсы и деятельность организаций здравоохранения.

### Предположение

За период 1990 - 2022 какова динамика снижения процентного соотношения зданий больниц в которых отсутствует водопровод, горячее водоснабжение, центральное отопление, канализация, телефонная связь?

### Загрузка данных

In [175]:
technical_condition_2005 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2005/Ресурсы и деятельность учреждений здравоохранения/техническое состояние и благоустройство зданий лечебно-профилактических учреждений здравоохранения.csv')

technical_condition_2005

,0,1,2,3
0,NaN,1995,2001,2003
1,NaN,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары
2,"Всего зданий, тыс.",27.0,24.8,23.8
3,"в том числе по техническому состоянию, процентов:",NaN,NaN,NaN
4,находятся в аварийном состоянии,5.2,3.4,3.3
5,требуют реконструкции,7.7,6.1,6.4
6,требуют капитального ремонта,31.9,29.6,28.5
7,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN
8,водопровод,13.2,10.8,8.8
9,горячее водоснабжение,39.5,35.5,33.1
10,центральное отопление,14.7,10.1,9.6
11,канализация,18.7,13.2,12.2
12,телефонная связь,10.5,9.9,7.7
13,NaN,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения
14,"Всего зданий, тыс.",19.7,19.9,20.0
15,"в том числе по техническому состоянию, процентов:",NaN,NaN,NaN
16,находятся в аварийном состоянии,3.6,2.0,1.6
17,требуют реконструкции,5.5,4.8,4.8
18,требуют капитального ремонта,27.4,25.0,24.0
19,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN
20,водопровод,15.9,13.1,13.8
21,горячее водоснабжение,44.1,42.9,42.3
22,центральное отопление,16.3,14.3,14.4
23,канализация,22.6,18.2,17.9
24,телефонная связь,9.0,8.7,9.8

In [176]:
technical_condition_2007 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2007/Ресурсы и деятельность учреждений здравоохранения/техническое состояние и благоустройство зданий лечебно - профилактических учреждений здравоохранения.csv')

technical_condition_2007

,0,1,2,3,4
0,NaN,1995,2001,2003,2006
1,NaN,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары
2,"Всего зданий, тыс.",27.0,24.8,23.8,23.2
3,"в том числе по техническому состоянию, процен...",NaN,NaN,NaN,NaN
4,находятся в аварийном состоянии,5.2,3.4,3.3,3.7
5,требуют реконструкции,7.7,6.1,6.4,6.2
6,требуют капитального ремонта,31.9,29.6,28.5,27.9
7,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN
8,водопровод,13.2,10.8,8.8,8.9
9,горячее водоснабжение,39.5,35.5,33.1,31.7
10,центральное отопление,14.7,10.1,9.6,9.4
11,канализация,18.7,13.2,12.2,11.3
12,телефонная связь,10.5,9.9,7.7,7.5
13,NaN,Врачебные амбулаторно- поликлинические учреждения,Врачебные амбулаторно- поликлинические учреждения,Врачебные амбулаторно- поликлинические учреждения,Врачебные амбулаторно- поликлинические учреждения
14,"Всего зданий, тыс.",19.7,19.9,20.0,19.5
15,"в том числе по техническому состоянию, процен...",NaN,NaN,NaN,NaN
16,находятся в аварийном состоянии,3.6,2.0,1.6,1.6
17,требуют реконструкции,5.5,4.8,4.8,4.2
18,требуют капитального ремонта,27.4,25.0,24.0,23.1
19,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN
20,водопровод,15.9,13.1,13.8,13.0
21,горячее водоснабжение,44.1,42.9,42.3,40.0
22,центральное отопление,16.3,14.3,14.4,14.2
23,канализация,22.6,18.2,17.9,16.7
24,телефонная связь,9.0,8.7,9.8,10.2

In [177]:
technical_condition_2009 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2009/Ресурсы и деятельность учреждений здравоохранения/техническое состояние и благоустройство зданий лечебно- профилактических учреждений здравоохранения.csv')

technical_condition_2009

,0,1,2,3,4,5
0,NaN,1995,2001,2003,2007,2008
1,NaN,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары
2,"Всего зданий, тыс.",27.0,24.8,23.8,23.0,24.0
3,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN
4,находятся в аварийном состоянии,5.2,3.4,3.3,2.7,2.6
5,требуют реконструкции,7.7,6.1,6.4,6.0,6.2
6,требуют капитального ремонта,31.9,29.6,28.5,27.2,45.6
7,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
8,водопровод,13.2,10.8,8.8,7.4,7.6
9,горячее водоснабжение,39.5,35.5,33.1,30.6,29.7
10,центральное отопление,14.7,10.1,9.6,8.4,9.2
11,канализация,18.7,13.2,12.2,10.2,10.1
12,телефонная связь,10.5,9.9,7.7,5.9,7.3
13,NaN,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения
14,"Всего зданий, тыс.",19.7,19.9,20.0,19.1,19.3
15,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN
16,находятся в аварийном состоянии,3.6,2.0,1.6,1.4,1.4
17,требуют реконструкции,5.5,4.8,4.8,4.2,4.4
18,требуют капитального ремонта,27.4,25.0,24.0,23.9,23.6
19,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
20,водопровод,15.9,13.1,13.8,10.7,9.3
21,горячее водоснабжение,44.1,42.9,42.3,38.6,36.0
22,центральное отопление,16.3,14.3,14.4,11.9,11.5
23,канализация,22.6,18.2,17.9,14.5,12.6
24,телефонная связь,9.0,8.7,9.8,7.2,5.9

In [178]:
technical_condition_2011 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2011/Ресурсы и деятельность учреждений здравоохранения/техническое состояние и благоустройство зданий лечебно-профилактических учреждений здравоохранения.csv')

technical_condition_2011

,0,1,2,3,4,5
0,NaN,1995,2001,2003,2009,2010
1,NaN,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары
2,"Всего зданий, тыс.",27.0,24.8,23.8,17.2,18.8
3,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN
4,находятся в аварийном состоянии,5.2,3.4,3.3,2.3,2.0
5,требуют реконструкции,7.7,6.1,6.4,6.2,5.9
6,требуют капитального ремонта,31.9,29.6,28.5,27.7,32.9
7,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
8,водопровод,13.2,10.8,8.8,7.8,6.0
9,горячее водоснабжение,39.5,35.5,33.1,23.7,24.9
10,центральное отопление,14.7,10.1,9.6,7.6,9.5
11,канализация,18.7,13.2,12.2,7.7,8.3
12,телефонная связь,10.5,9.9,7.7,6.1,5.8
13,NaN,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения,Амбулаторно-поликлинические учреждения
14,"Всего зданий, тыс.",19.7,19.9,20.0,19.1,19.2
15,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN
16,находятся в аварийном состоянии,3.6,2.0,1.6,1.1,1.2
17,требуют реконструкции,5.5,4.8,4.8,3.5,3.4
18,требуют капитального ремонта,27.4,25.0,24.0,22.7,25.7
19,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
20,водопровод,15.9,13.1,13.8,8.3,6.6
21,горячее водоснабжение,44.1,42.9,42.3,32.8,31.8
22,центральное отопление,16.3,14.3,14.4,10.6,10.3
23,канализация,22.6,18.2,17.9,10.7,9.3
24,телефонная связь,9.0,8.7,9.8,7.0,5.8

In [179]:
technical_condition_2013 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2013/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.10. техническое состояние и благоустройство зданий  лечебно-профилактических организаций здравоохранения1).csv')

technical_condition_2013

,Unnamed: 0,2000,2005,2010,2011,2012
0,NaN,Больничные организации,Больничные организации,Больничные организации,Больничные организации,Больничные организации
1,"Всего зданий, тыс.","24,8","23,8","18,8","18,8","18,8"
2,"из них по техническому состоянию, \nпроцентов:",NaN,NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,"3,4","3,3","2,0","1,8","1,7"
4,требуют реконструкции,"6,1","6,4","5,9","5,0","4,9"
5,требуют капитального ремонта,"29,6","28,5","32,9","31,7","31,5"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
7,водопровод,"10,8","8,8","6,0","5,9","5,3"
8,горячее водоснабжение,"35,5","33,1","24,9","24,5","22,5"
9,центральное отопление,"10,1","9,6","9,5","8,5","7,4"
10,канализация,"13,2","12,2","8,3","7,6","6,5"
11,телефонная связь,"9,9","7,7","5,8","6,3","5,5"
12,NaN,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации
13,"Всего зданий, тыс.","19,9","20,0","19,2","18,8","18,8"
14,"из них по техническому состоянию, \nпроцентов:",NaN,NaN,NaN,NaN,NaN
15,находятся в аварийном состоянии,"2,0","1,6","1,2","1,1","1,1"
16,требуют реконструкции,"4,8","4,8","3,4","3,0","2,8"
17,требуют капитального ремонта,"25,0","24,0","25,7","24,6","23,3"
18,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
19,водопровод,"13,1","13,8","6,6","6,1","7,1"
20,горячее водоснабжение,"42,9","42,3","31,8","31,8","30,9"
21,центральное отопление,"14,3","14,4","10,3","10,6","10,6"
22,канализация,"18,2","17,9","9,3","8,9","9,2"
23,телефонная связь,"8,7","9,8","5,8","5,1","5,9"

In [180]:
technical_condition_2015 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2015/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.10. техническое состояние и благоустройство зданий  лечебно-профилактических организаций здравоохранения1).csv')

technical_condition_2015

,Unnamed: 0,2005,2010,2011,2012,2013
0,NaN,Больничные организации,Больничные организации,Больничные организации,Больничные организации,Больничные организации
1,"Всего зданий, тыс.","23,8","18,8","18,8","18,8","18,7"
2,"из них по техническому состоянию, \nпроцентов:",NaN,NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,"3,3","2,0","1,8","1,7","1,6"
4,требуют реконструкции,"6,4","5,9","5,0","4,9","4,1"
5,требуют капитального ремонта,"28,5","32,9","31,7","31,5","28,2"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
7,водопровод,"8,8","6,0","5,9","5,3","3,9"
8,горячее водоснабжение,"33,1","24,9","24,5","22,5","20,6"
9,центральное отопление,"9,6","9,5","8,5","7,4","7,0"
10,канализация,"12,2","8,3","7,6","6,5","6,2"
11,телефонная связь,"7,7","5,8","6,3","5,5","4,0"
12,NaN,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации,Амбулаторно-поликлинические организации
13,"Всего зданий, тыс.","20,0","19,2","18,8","19,4","18,9"
14,"из них по техническому состоянию, \nпроцентов:",NaN,NaN,NaN,NaN,NaN
15,находятся в аварийном состоянии,"1,6","1,2","1,1","1,1","1,1"
16,требуют реконструкции,"4,8","3,4","3,0","2,8","2,3"
17,требуют капитального ремонта,"24,0","25,7","24,6","23,3","21,8"
18,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
19,водопровод,"13,8","6,6","6,1","7,1","6,1"
20,горячее водоснабжение,"42,3","31,8","31,8","30,9","29,6"
21,центральное отопление,"14,4","10,3","10,6","10,6","10,2"
22,канализация,"17,9","9,3","8,9","9,2","7,9"
23,телефонная связь,"9,8","5,8","5,1","5,9","4,6"

In [181]:
technical_condition_2017 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2017/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.12. техническое состояние и благоустройство зданий  лечебно-профилактических организаций здравоохранения1).csv')

technical_condition_2017

,Unnamed: 0,2014,2015,2016
0,NaN,В стационарных условиях,В стационарных условиях,В стационарных условиях
1,"Всего зданий, тыс.","12,2","12,1","11,6"
2,"из них по техническому состоянию, процентов:",NaN,NaN,NaN
3,находятся в аварийном состоянии,"1,6","1,3","1,0"
4,требуют реконструкции,"4,1","2,9","2,4"
5,требуют капитального ремонта,"27,9","23,2","21,1"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN
7,водопровод,"3,5","4,4","3,9"
8,горячее водоснабжение,"17,9","18,7","18,5"
9,центральное отопление,"6,7","9,6","9,1"
10,канализация,"5,1","6,1","5,2"
11,телефонная связь,"5,1","6,9","6,2"
12,NaN,В амбулаторных условиях,В амбулаторных условиях,В амбулаторных условиях
13,"Всего зданий, тыс.","18,1","19,4","19,7"
14,"из них по техническому состоянию, процентов:",NaN,NaN,NaN
15,находятся в аварийном состоянии,"1,0","0,8","0,6"
16,требуют реконструкции,"2,6","1,7","1,2"
17,требуют капитального ремонта,"22,7","18,3","16,3"
18,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN
19,водопровод,"4,9","5,1","4,8"
20,горячее водоснабжение,"27,8","28,1","27,7"
21,центральное отопление,"11,2","12,3","12,6"
22,канализация,"7,5","7,7","7,1"
23,телефонная связь,"4,1","5,2","5,3"

In [182]:
technical_condition_2019 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2019/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.12. техническое состояние и благоустройство зданий  лечебно-профилактических организаций здравоохранения1).csv')

technical_condition_2019

,Unnamed: 0,2015,2016,2017,2018
0,NaN,В стационарных условиях,В стационарных условиях,В стационарных условиях,В стационарных условиях
1,"Всего зданий, тыс.","12,1","11,6","11,2","11,0"
2,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,"1,3","1,0","0,9","0,9"
4,требуют реконструкции,"2,9","2,4","1,5","1,0"
5,требуют капитального ремонта,"23,2","21,1","17,9","16,7"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN
7,водопровод,"4,4","3,9","3,0","2,9"
8,горячее водоснабжение,"18,7","18,5","17,1","16,6"
9,центральное отопление,"9,6","9,1","7,9","8,2"
10,канализация,"6,1","5,2","4,6","4,4"
11,телефонная связь,"6,9","6,2","4,8","5,2"
12,NaN,В амбулаторных условиях,В амбулаторных условиях,В амбулаторных условиях,В амбулаторных условиях
13,"Всего зданий, тыс.","19,4","19,7","20,2","20,1"
14,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN
15,находятся в аварийном состоянии,"0,8","0,6","0,5","0,9"
16,требуют реконструкции,"1,7","1,2","0,7","0,5"
17,требуют капитального ремонта,"18,3","16,3","12,8","11,8"
18,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN
19,водопровод,"5,1","4,8","4,4","4,3"
20,горячее водоснабжение,"28,1","27,7","26,7","26,2"
21,центральное отопление,"12,3","12,6","12,8","13,2"
22,канализация,"7,7","7,1","7,1","6,9"
23,телефонная связь,"5,2","5,3","5,4","5,3"

In [183]:
technical_condition_2021 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2021/РЕСУРСЫ И ДЕЯТЕЛЬНОСТЬ ОРГАНИЗАЦИЙ /3.12. техническое состояние и благоустройство зданий  медицинских организаций здравоохранения1).csv')

technical_condition_2021

,Unnamed: 0,2015,2018,2019,2020
0,NaN,В стационарных условиях,В стационарных условиях,В стационарных условиях,В стационарных условиях
1,"Всего зданий, тыс.","12,1","11,0","10,7","10,6"
2,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,"1,3","0,9","1,4","1,3"
4,требуют реконструкции,"2,9","1,0","1,2","1,2"
5,требуют капитального ремонта,"23,2","16,7","21,6","22,4"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN
7,водопровод,"4,4","2,9","2,8","2,8"
8,горячее водоснабжение,"18,7","16,6","16,2","15,8"
9,центральное отопление,"9,6","8,2","8,3","6,4"
10,канализация,"6,1","4,4","4,1","4,1"
11,телефонная связь,"6,9","5,2","5,0","5,0"
12,NaN,В амбулаторных условиях,В амбулаторных условиях,В амбулаторных условиях,В амбулаторных условиях
13,"Всего зданий, тыс.","19,4","20,1","20,3","20,2"
14,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN
15,находятся в аварийном состоянии,"0,8","0,9","2,1","2,4"
16,требуют реконструкции,"1,7","0,5","0,9","0,9"
17,требуют капитального ремонта,"18,3","11,8","20,3","21,0"
18,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN
19,водопровод,"5,1","4,3","4,2","4,0"
20,горячее водоснабжение,"28,1","26,2","25,4","24,7"
21,центральное отопление,"12,3","13,2","13,5","14,2"
22,канализация,"7,7","6,9","6,5","6,2"
23,телефонная связь,"5,2","5,3","5,0","4,9"

In [184]:
technical_condition_2023 = pd.read_csv('/Users/mac/Desktop/проекты в Яндекс Практикуме/Датасеты и проекты/Мастерская/данные/2023/3.12. ТЕХНИЧЕСКОЕ СОСТОЯНИЕ И БЛАГОУСТРОЙСТВО ЗДАНИЙ МЕДИЦИНСКИХ ОРГАНИЗАЦИЙ ЗДРАВООХРАНЕНИЯ1) - 3.12.csv')

technical_condition_2023

,3.12. ТЕХНИЧЕСКОЕ СОСТОЯНИЕ И БЛАГОУСТРОЙСТВО ЗДАНИЙ МЕДИЦИНСКИХ ОРГАНИЗАЦИЙ ЗДРАВООХРАНЕНИЯ1),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,2015,2019,2020,2021,2022
1,NaN,"Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ..."
2,"Всего зданий, тыс.","12,1","10,7","10,6","10,5","10,3"
3,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN
4,находятся в аварийном состоянии,"1,3","1,4","1,3","1,3","1,5"
5,требуют реконструкции,"2,9","1,2","1,2","1,3","1,2"
6,требуют капитального ремонта,"23,2","21,6","22,4","22,1","21,3"
7,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
8,водопровод,"4,4","2,8","2,8","2,8",…
9,горячее водоснабжение,"18,7","16,2","15,8","15,9",…
10,центральное отопление,"9,6","8,3","6,4","8,9",…
11,канализация,"6,1","4,1","4,1","4,1",…
12,телефонная связь,"6,9","5,0","5,0","5,1",…
13,NaN,"Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ...","Подразделения, оказывающие медицинскую помощь ..."
14,"Всего зданий, тыс.","19,4","20,3","20,2","20,2","20,2"
15,"из них по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN
16,находятся в аварийном состоянии,"0,8","2,1","2,4","2,3","1,9"
17,требуют реконструкции,"1,7","0,9","0,9","1,0","0,8"
18,требуют капитального ремонта,"18,3","20,3","21,0","19,7","17,2"
19,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN
20,водопровод,"5,1","4,2","4,0","3,9",…
21,горячее водоснабжение,"28,1","25,4","24,7","24,3",…
22,центральное отопление,"12,3","13,5","14,2","14,2",…
23,канализация,"7,7","6,5","6,2","5,9",…
24,телефонная связь,"5,2","5,0","4,9","5,0",…

### Предобработка данных

Возьмем первую строку датафрейма и сделаем из неё название колонок и потом сразу удалим её. Для этого напишем функцию и передадим ей датафреймы по очереди вплоть до 2011 года и для 2023 года тоже.

In [185]:
def column_new(data):
    data.columns = list(data.iloc[0])
    data = data.drop(index = 0).reset_index(drop=True)
    data.rename(columns = {np.nan:'name'}, inplace=True)
    return data

In [186]:
technical_condition_2005 = column_new(technical_condition_2005)

In [187]:
technical_condition_2007 = column_new(technical_condition_2007)

In [188]:
technical_condition_2009 = column_new(technical_condition_2009)

In [189]:
technical_condition_2011 = column_new(technical_condition_2011)

In [190]:
technical_condition_2023 = column_new(technical_condition_2023)

С датафреймами из папок с 2013 по 2021 изменим названия 1 колонки с `Unnamed: 0	` на `name` с целью дальнейшего корректного соединения.

In [191]:
technical_condition_2013.rename(columns={'Unnamed: 0':'name'}, inplace=True)

technical_condition_2015.rename(columns={'Unnamed: 0':'name'}, inplace=True)

technical_condition_2017.rename(columns={'Unnamed: 0':'name'}, inplace=True)

technical_condition_2019.rename(columns={'Unnamed: 0':'name'}, inplace=True)

technical_condition_2021.rename(columns={'Unnamed: 0':'name'}, inplace=True)

Создадим список датафреймов и проверим их длину

In [192]:
t = [technical_condition_2007, 
     technical_condition_2009,
    technical_condition_2011,
    technical_condition_2013,
    technical_condition_2015,
    technical_condition_2017,
    technical_condition_2019,
    technical_condition_2021,
    technical_condition_2023]

In [193]:
for el in t:
    print(len(el))

24
24
24
24
24
24
24
24
24

Все получившиеся датафреймы имеют одинаковую длину и для унификации строк с индексами 0 и 12 создадим список и передадим его каждому датафрейму. За образец возьмём названия этих строк по индексам за 2005-2009 года, так как они кажутся наиболее полными.

Напишем функцию, которая будет прпнимать датафрейм и шаблонный датафрейм (для названия колонок) из папки 2005 года и вернёт изменённые строки с индексами 0 и 12 на унифицированные. Также в этой функции предусмотрим изменение название колонки `name` во всех датасетах на наименования из колонки `name` шаблонного датафрейма (опять же с целью унификации названий и дальнейшего соединения).

In [194]:
technical_condition_2009.columns

Index(['name', '1995', '2001', '2003', '2007', '2008'], dtype='object')

In [195]:
def row_new(data, data_pattern):
    mask_row_0 = data_pattern['1995'].values[0]
    
    mask_row_12 = data_pattern['1995'].values[12]
    
    data.iloc[0,1:] = mask_row_0
    
    data.iloc[12,1:] = mask_row_12
    
    mask_column = data_pattern['name']
    
    data['name'] = mask_column
    
    return data

Теперь вновь написанной функции передадим все данные из папок с 2005 по 2023

In [196]:
с = row_new(technical_condition_2007, technical_condition_2005)

technical_condition_2009 = row_new(technical_condition_2009, technical_condition_2005)

technical_condition_2011 = row_new(technical_condition_2011, technical_condition_2005)

technical_condition_2013 = row_new(technical_condition_2013, technical_condition_2005)

technical_condition_2015 = row_new(technical_condition_2015, technical_condition_2005)

technical_condition_2017 = row_new(technical_condition_2017, technical_condition_2005)

technical_condition_2019 = row_new(technical_condition_2019, technical_condition_2005)

technical_condition_2021 = row_new(technical_condition_2021, technical_condition_2005)

technical_condition_2023 = row_new(technical_condition_2023, technical_condition_2005)

### Соединение в единый датасет

Соединими все таблицы в единый датасет

In [197]:
technical_condition_1 = pd.concat([technical_condition_2005, technical_condition_2007], axis=1)

In [198]:
technical_condition_2 = pd.concat([technical_condition_1, technical_condition_2009], axis=1)

In [199]:
technical_condition_3 = pd.concat([technical_condition_2, technical_condition_2011], axis=1)

In [200]:
technical_condition_4 = pd.concat([technical_condition_3, technical_condition_2013], axis=1)

In [201]:
technical_condition_5 = pd.concat([technical_condition_4, technical_condition_2015], axis=1)

In [202]:
technical_condition_6 = pd.concat([technical_condition_5, technical_condition_2017], axis=1)

In [203]:
technical_condition_7 = pd.concat([technical_condition_6, technical_condition_2019], axis=1)

In [204]:
technical_condition_8 = pd.concat([technical_condition_7, technical_condition_2021], axis=1)

In [205]:
technical_condition_total = pd.concat([technical_condition_8, technical_condition_2023], axis=1)

Теперь удалим дублирующиеся столбцы по наименванию года

In [206]:
technical_condition_total = technical_condition_total.loc[:,~technical_condition_total.columns.duplicated()].copy()

technical_condition_total

,name,1995,2001,2003,2006,2007,2008,2009,2010,2000,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,NaN,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,...,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары,Больничные учреждения и стационары
1,"Всего зданий, тыс.",27.0,24.8,23.8,23.2,23.0,24.0,17.2,18.8,"24,8",...,"18,7","12,2","12,1","11,6","11,2","11,0","10,7","10,6","10,5","10,3"
2,"в том числе по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,5.2,3.4,3.3,3.7,2.7,2.6,2.3,2.0,"3,4",...,"1,6","1,6","1,3","1,0","0,9","0,9","1,4","1,3","1,3","1,5"
4,требуют реконструкции,7.7,6.1,6.4,6.2,6.0,6.2,6.2,5.9,"6,1",...,"4,1","4,1","2,9","2,4","1,5","1,0","1,2","1,2","1,3","1,2"
5,требуют капитального ремонта,31.9,29.6,28.5,27.9,27.2,45.6,27.7,32.9,"29,6",...,"28,2","27,9","23,2","21,1","17,9","16,7","21,6","22,4","22,1","21,3"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,водопровод,13.2,10.8,8.8,8.9,7.4,7.6,7.8,6.0,"10,8",...,"3,9","3,5","4,4","3,9","3,0","2,9","2,8","2,8","2,8",…
8,горячее водоснабжение,39.5,35.5,33.1,31.7,30.6,29.7,23.7,24.9,"35,5",...,"20,6","17,9","18,7","18,5","17,1","16,6","16,2","15,8","15,9",…
9,центральное отопление,14.7,10.1,9.6,9.4,8.4,9.2,7.6,9.5,"10,1",...,"7,0","6,7","9,6","9,1","7,9","8,2","8,3","6,4","8,9",…
10,канализация,18.7,13.2,12.2,11.3,10.2,10.1,7.7,8.3,"13,2",...,"6,2","5,1","6,1","5,2","4,6","4,4","4,1","4,1","4,1",…
11,телефонная связь,10.5,9.9,7.7,7.5,5.9,7.3,6.1,5.8,"9,9",...,"4,0","5,1","6,9","6,2","4,8","5,2","5,0","5,0","5,1",…
12,NaN,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,...,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения,Врачебные амбулаторно-поликлинические учреждения
13,"Всего зданий, тыс.",19.7,19.9,20.0,19.5,19.1,19.3,19.1,19.2,"19,9",...,"18,9","18,1","19,4","19,7","20,2","20,1","20,3","20,2","20,2","20,2"
14,"в том числе по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,находятся в аварийном состоянии,3.6,2.0,1.6,1.6,1.4,1.4,1.1,1.2,"2,0",...,"1,1","1,0","0,8","0,6","0,5","0,9","2,1","2,4","2,3","1,9"
16,требуют реконструкции,5.5,4.8,4.8,4.2,4.2,4.4,3.5,3.4,"4,8",...,"2,3","2,6","1,7","1,2","0,7","0,5","0,9","0,9","1,0","0,8"
17,требуют капитального ремонта,27.4,25.0,24.0,23.1,23.9,23.6,22.7,25.7,"25,0",...,"21,8","22,7","18,3","16,3","12,8","11,8","20,3","21,0","19,7","17,2"
18,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,водопровод,15.9,13.1,13.8,13.0,10.7,9.3,8.3,6.6,"13,1",...,"6,1","4,9","5,1","4,8","4,4","4,3","4,2","4,0","3,9",…
20,горячее водоснабжение,44.1,42.9,42.3,40.0,38.6,36.0,32.8,31.8,"42,9",...,"29,6","27,8","28,1","27,7","26,7","26,2","25,4","24,7","24,3",…
21,центральное отопление,16.3,14.3,14.4,14.2,11.9,11.5,10.6,10.3,"14,3",...,"10,2","11,2","12,3","12,6","12,8","13,2","13,5","14,2","14,2",…
22,канализация,22.6,18.2,17.9,16.7,14.5,12.6,10.7,9.3,"18,2",...,"7,9","7,5","7,7","7,1","7,1","6,9","6,5","6,2","5,9",…
23,телефонная связь,9.0,8.7,9.8,10.2,7.2,5.9,7.0,5.8,"8,7",...,"4,6","4,1","5,2","5,3","5,4","5,3","5,0","4,9","5,0",…

### Сохранение получившихся датасетов и разделение их на стационар и амбулатории

Из исходного датафрейма сохраним стационарные учреждения в один датасет, а амбулаторные учреждения в другой датасет

Стационарные учреждения - technical_condition_hospital

In [207]:
technical_condition_hospital = technical_condition_total.iloc[:12,:].copy()

technical_condition_hospital.drop(index=0, inplace=True)

technical_condition_hospital

,name,1995,2001,2003,2006,2007,2008,2009,2010,2000,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,"Всего зданий, тыс.",27.0,24.8,23.8,23.2,23.0,24.0,17.2,18.8,"24,8",...,"18,7","12,2","12,1","11,6","11,2","11,0","10,7","10,6","10,5","10,3"
2,"в том числе по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,5.2,3.4,3.3,3.7,2.7,2.6,2.3,2.0,"3,4",...,"1,6","1,6","1,3","1,0","0,9","0,9","1,4","1,3","1,3","1,5"
4,требуют реконструкции,7.7,6.1,6.4,6.2,6.0,6.2,6.2,5.9,"6,1",...,"4,1","4,1","2,9","2,4","1,5","1,0","1,2","1,2","1,3","1,2"
5,требуют капитального ремонта,31.9,29.6,28.5,27.9,27.2,45.6,27.7,32.9,"29,6",...,"28,2","27,9","23,2","21,1","17,9","16,7","21,6","22,4","22,1","21,3"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,водопровод,13.2,10.8,8.8,8.9,7.4,7.6,7.8,6.0,"10,8",...,"3,9","3,5","4,4","3,9","3,0","2,9","2,8","2,8","2,8",…
8,горячее водоснабжение,39.5,35.5,33.1,31.7,30.6,29.7,23.7,24.9,"35,5",...,"20,6","17,9","18,7","18,5","17,1","16,6","16,2","15,8","15,9",…
9,центральное отопление,14.7,10.1,9.6,9.4,8.4,9.2,7.6,9.5,"10,1",...,"7,0","6,7","9,6","9,1","7,9","8,2","8,3","6,4","8,9",…
10,канализация,18.7,13.2,12.2,11.3,10.2,10.1,7.7,8.3,"13,2",...,"6,2","5,1","6,1","5,2","4,6","4,4","4,1","4,1","4,1",…
11,телефонная связь,10.5,9.9,7.7,7.5,5.9,7.3,6.1,5.8,"9,9",...,"4,0","5,1","6,9","6,2","4,8","5,2","5,0","5,0","5,1",…

Амбулаторные учреждения - technical_condition_outpatient_clinic

In [208]:
technical_condition_outpatient_clinic = technical_condition_total.iloc[12:,:].copy()

technical_condition_outpatient_clinic.reset_index(drop=True, inplace=True)

technical_condition_outpatient_clinic.drop(index=0, inplace=True)

In [209]:
technical_condition_outpatient_clinic

,name,1995,2001,2003,2006,2007,2008,2009,2010,2000,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
1,"Всего зданий, тыс.",19.7,19.9,20.0,19.5,19.1,19.3,19.1,19.2,"19,9",...,"18,9","18,1","19,4","19,7","20,2","20,1","20,3","20,2","20,2","20,2"
2,"в том числе по техническому состоянию, процентов:",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,находятся в аварийном состоянии,3.6,2.0,1.6,1.6,1.4,1.4,1.1,1.2,"2,0",...,"1,1","1,0","0,8","0,6","0,5","0,9","2,1","2,4","2,3","1,9"
4,требуют реконструкции,5.5,4.8,4.8,4.2,4.2,4.4,3.5,3.4,"4,8",...,"2,3","2,6","1,7","1,2","0,7","0,5","0,9","0,9","1,0","0,8"
5,требуют капитального ремонта,27.4,25.0,24.0,23.1,23.9,23.6,22.7,25.7,"25,0",...,"21,8","22,7","18,3","16,3","12,8","11,8","20,3","21,0","19,7","17,2"
6,"Удельный вес числа зданий, в которых отсутству...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,водопровод,15.9,13.1,13.8,13.0,10.7,9.3,8.3,6.6,"13,1",...,"6,1","4,9","5,1","4,8","4,4","4,3","4,2","4,0","3,9",…
8,горячее водоснабжение,44.1,42.9,42.3,40.0,38.6,36.0,32.8,31.8,"42,9",...,"29,6","27,8","28,1","27,7","26,7","26,2","25,4","24,7","24,3",…
9,центральное отопление,16.3,14.3,14.4,14.2,11.9,11.5,10.6,10.3,"14,3",...,"10,2","11,2","12,3","12,6","12,8","13,2","13,5","14,2","14,2",…
10,канализация,22.6,18.2,17.9,16.7,14.5,12.6,10.7,9.3,"18,2",...,"7,9","7,5","7,7","7,1","7,1","6,9","6,5","6,2","5,9",…
11,телефонная связь,9.0,8.7,9.8,10.2,7.2,5.9,7.0,5.8,"8,7",...,"4,6","4,1","5,2","5,3","5,4","5,3","5,0","4,9","5,0",…

Для корректной работы с данными при визуализации, изменим все символы запятых на точки. Основная цель этих изменений - запятые между цифрами.

In [210]:
technical_condition_hospital = technical_condition_hospital.apply(lambda x: x.str.replace(',', '.'))

technical_condition_outpatient_clinic = technical_condition_outpatient_clinic.apply(lambda x: 
                                                                                    x.str.replace(',', '.'))

Транспонируем датасеты и сохраняем для дальнейшей их визуализации и построение дашбордов.

In [211]:
technical_condition_hospital = technical_condition_hospital.set_index('name').T

In [212]:
technical_condition_outpatient_clinic = technical_condition_outpatient_clinic.set_index('name').T

In [213]:
technical_condition_hospital.to_csv('technical_condition_hospital.csv')

In [214]:
technical_condition_outpatient_clinic.to_csv('technical_condition_outpatient_clinic.csv')

### Ссылка на дашборд

Дашборд выполнен в программе Tableau и доступен по [ссылке](https://public.tableau.com/views/technical_condition_hospital/sheet13?:language=en-US&:sid=&:display_count=n&:origin=viz_share_link)

### Вывод по разделу

Стационарные медицинские учреждения и динамика % соотношения:

- % отсутствия горячего водоснабжения снизился на 23,6%;
- % отсутствия канализации снизился на 14,6%;
- % отсутствия центрального отопления снизился на 5,8%;
- % отсутствия водопровода снизился на 10,4%;
- % отсутствия телефонной связи снизился на 5,4%.  

Амбулаторные медицинские учреждения и динамика % соотношения:

- % отсутствия горячего водоснабжения снизился на 19,8%;
- % отсутствия канализации снизился на 16,7%;
- % отсутствия центрального отопления снизился на 2,1%;
- % отсутствия водопровода снизился на 12%;
- % отсутствия телефонной связи снизился на 4%.